### ISSUE TITLE
napcat-sign.wumiao.wang:2082/rkey存在问题

### ISSUE THREAD

**Issue by 738NGX** [NapNeko/NapCatQQ#101]
起因是尝试让bot将图片保存到本地时报错Bad Request
查看日志发现截取的图片链接为：
[rkey=CAISKKSBekjVG1fMDZprKQvYUSqmpFvj8pumL7YRs9LAoggV1C4yllIWBiY](https://[multimedia.nt.qq.com.cn/download?appid=1407&fileid=CgoyODU3MzIzMDIwEhSY405KBfVKmTYJSYIQlJf1ZTYMBhiotAQg_woo17zG45aLhwNQgL2jAQ&spec=0&rkey=CAISKKSBekjVG1fMDZprKQvYUSqmpFvj8pumL7YRs9LAoggV1C4yllIWBiY](https://multimedia.nt.qq.com.cn/download?appid=1407&fileid=CgoyODU3MzIzMDIwEhSY405KBfVKmTYJSYIQlJf1ZTYMBhiotAQg_woo17zG45aLhwNQgL2jAQ&spec=0&rkey=CAISKKSBekjVG1fMDZprKQvYUSqmpFvj8pumL7YRs9LAoggV1C4yllIWBiY))
点开之后没有图片，只有以下报错信息：
```
{
    "retcode": -5503007,
    "retmsg": "download url has expired",
    "retryflag": 0
}
```
这段链接的rkey与[napcat-sign.wumiao.wang:2082/rkey](http://napcat-sign.wumiao.wang:2082/rkey)给出的是一致的：
```
{
    "private_rkey": "&rkey=CAISKKSBekjVG1fMDZprKQvYUSqmpFvj8pumL7YRs9LAoggVhf-7-ORpQFU",
    "group_rkey": "&rkey=CAISKKSBekjVG1fMDZprKQvYUSqmpFvj8pumL7YRs9LAoggV1C4yllIWBiY",
    "expired_time": 1720017835
}
```
随后我尝试了QQ官方的接口，能正常保存图片。我将官方接口中链接的rkey强行替换了通过onebot获得的链接中的rkey，经过测试暂时可用，因此怀疑是napcat提供的rkey存在问题，希望能修复一下

**Comment by 738NGX** [comment]
qq官方接口的rkey还是会刷新的，隔段时间就失效了，强制替换也不成功

**Comment by linyuchen** [comment]
rkey服务器已恢复
