### ISSUE TITLE
[BUG] 撤回消息无论成功返回的数据时一样的

### ISSUE THREAD

**Issue by dazo6** [NapNeko/NapCatQQ#102]
### 系统版本

linux ubuntu

### QQNT 版本

Linux 3.2.9-24815

### NapCat 版本

NapCat V1.6.2

### OneBot 客户端

-

### 发生了什么?

1. 调用了 delete_msg 方法，后发现撤回失败了，但是返回的还是正确应答。

### 如何复现

1. 调用delete_msg 
2. 查看应答

### 期望的结果?

如果撤回成功返回正确，撤回失败返回错误。

**Comment by MliKiowa** [comment]
好的 下个版本优化

**Comment by MliKiowa** [comment]
试试这个版本 https://github.com/NapNeko/NapCatQQ/actions/runs/10259806848

**Comment by dazo6** [comment]
不好意思，前端时间比较忙，现在才更新版本，我直接更新到了2.0.21。但是撤回失败后依然返回ok。响应没有区别，请问是只有你发我的版本会附带撤回相应吗？
