### ISSUE TITLE
webui的开关控制bug

### ISSUE THREAD

**Issue by layvsan** [NapNeko/NapCatQQ#103]
https://github.com/NapNeko/NapCatQQ/actions/runs/9708040348 尝试测试版 如果还有问题 reopen

_Originally posted by @MliKiowa in https://github.com/NapNeko/NapCatQQ/issues/85#issuecomment-2196182245_
            
似乎并没有什么用（悲）
使用的版本是release里的1.6.4

**Comment by layvsan** [comment]
你关的issue我也眉法reopen

**Comment by MliKiowa** [comment]
哪些问题没有修复

**Comment by Guation** [comment]
看了下应该是把判断的变量写错了 所以没跑进close流程里 等等下一个release吧

**Comment by MliKiowa** [comment]
下个版本还有问题 咱们群里聊
