### ISSUE TITLE
[增强] 是否计划支持获取群子目录文件？

### ISSUE THREAD

**Issue by dogfusu** [NapNeko/NapCatQQ#107]
目前 NapCat 的 API 文档已有 get_group_file_list 来获取根目录文件及文件夹，该接口是否支持获取子目录文件？
如否，NapCat 有计划引入获取子目录文件，及群文件一系列 API 吗？
![屏幕截图 2024-07-05 195823](https://github.com/NapNeko/NapCatQQ/assets/91790619/6e056987-16b0-4eb1-9300-7d8155babd7b)

**Comment by MliKiowa** [comment]
可以

**Comment by MliKiowa** [comment]
get_group_file_list 就可以获取到所有文件

**Comment by MliKiowa** [comment]
如果还有问题提新的issue

**Comment by shangdev** [comment]
> get_group_file_list 就可以获取到所有文件

@MliKiowa 最新版本v2.1.0调用这个接口返回：Key: start_index, Message: must be number
请求参数：
![image](https://github.com/user-attachments/assets/4de66942-8276-4fa9-a0fa-90e0142f4ba5)

**Comment by MliKiowa** [comment]
下个版本支持哦

**Comment by MliKiowa** [comment]
https://github.com/NapNeko/NapCatQQ/commit/7f9da8cc2dc45418a0027c61296e14e149b5c2cc

**Comment by MliKiowa** [comment]
如有问题再开issue
