### ISSUE TITLE
【功能】可以增加cqhttp的 获取群文件

### ISSUE THREAD

**Issue by timibox** [NapNeko/NapCatQQ#109]
[https://docs.go-cqhttp.org/api/#%E8%8E%B7%E5%8F%96%E7%BE%A4%E6%96%87%E4%BB%B6%E8%B5%84%E6%BA%90%E9%93%BE%E6%8E%A5](url)

可以把这个接口集成进来吗  感谢开发

**Comment by MliKiowa** [comment]
实现有难度这个

**Comment by timibox** [comment]
加油  爱你么么哒
