### ISSUE TITLE
[建议]新增后台启用选项

### ISSUE THREAD

**Issue by lingdu2333** [NapNeko/NapCatQQ#112]
rt，目前服务器为终端环境 napcat使用的还是祖传的nohup挂后台运行
如果可以使用类似PM2管理后台就更好了 例如添加 ./napcat.sh -u 命令则将napcat置于后台运行（或等待用户扫码完毕成功上号之后再自动切入后台）

**Comment by MliKiowa** [comment]
你可以使用screen 之类的自行处理
