### ISSUE TITLE
建议为http上报加入异常情况下重新上报的功能

### ISSUE THREAD

**Issue by hanximeng** [NapNeko/NapCatQQ#114]
在上报时判断一下是否成功上报，否则重新上报，避免部分情况下服务器突然抽风导致机器人无响应。

**Comment by MliKiowa** [comment]
这样 容易造成任务堆积

**Comment by hanximeng** [comment]
那设置一个开关让用户自行选择怎么样，就像go-cqhttp那样，设置重试次数不为0就是开启
