### ISSUE TITLE
[BUG] 进退群消息没有用户昵称？

### ISSUE THREAD

**Issue by kaoet** [NapNeko/NapCatQQ#115]
### 系统版本

Linux 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

### QQNT 版本

QQ_3.2.9_240617

### NapCat 版本

1.6.5

### OneBot 客户端

koishi adapter-onebot 6.5.8

### 发生了什么?

我用了koishi + better-custom-welcome-message插件，配合NapCat发送进群欢迎和退群欢送消息。

我在better-custom-welcome-message中配置的欢迎语中写了`{user}`。按照道理应被替换为此QQ用户的昵称。但实际上会显示为QQ号。

我在https://github.com/dingyi222666/koishi-plugin-better-custom-welcome-message/issues/2 中反映了此问题。但better-custom-welcome-message的维护者称是因为无法从NapCat获取到用户昵称而导致的问题。其原话如下：
> 经过测试后发现是 NapCat 没有获取到用户的昵称导致的。（也就是使用此方式接入 QQ 没法获取到 QQ 昵称）

### 如何复现

1. 安装koishi + better-custom-welcome-message + adapter-onebot + NapCat.
2. 建立测试群，并加退群

### 期望的结果?

欢迎语中应为昵称的地方显示了QQ号。

**Comment by MliKiowa** [comment]
调用的接口是什么 是走的群成员信息获取吗

**Comment by kaoet** [comment]
看起来是监听了`guild-member-added` & `guild-member-removed`

https://github.com/dingyi222666/koishi-plugin-better-custom-welcome-message/blob/531572cb9984a3c300c1c03315ab3cbe305fa26a/src/index.ts#L76-L94

**Comment by MliKiowa** [comment]
先调取下群成员接口检查下是否正常

**Comment by MliKiowa** [comment]
长时间没跟进 先关了
