### ISSUE TITLE
[BUG] 启动的时候弹出窗口,按照文档要求并没有解决问题

### ISSUE THREAD

**Issue by KOKOMI12345** [NapNeko/NapCatQQ#116]
### 系统版本

Windows10

### QQNT 版本

9.9.12

### NapCat 版本

1.6.5

### OneBot 客户端

OneBot V11

### 发生了什么?

我按照你们的文档做了修补QQ的操作，但是仍然，当我启动Napcat的时候，QQ弹出了窗口而没有向照常一样,napcat会把qr码保存到目录

### 如何复现

1. 运行NapCat-utf8.bat

### 期望的结果?

运行后输出日志，QQ没弹出窗口并且输出二维码

### NapCat 运行日志

```shell
None
```

### OneBot 客户端运行日志

```shell
None
```

**Comment by MliKiowa** [comment]
需要修改index.js 启动脚本也不能使用 需要管理员权限启动命令行 再运行QQ.exe --enable-logging

**Comment by KOKOMI12345** [comment]
没事了，解决了，用了NapcatDesktop后，自动帮我修补了

**Comment by KOKOMI12345** [comment]
解决了
