### ISSUE TITLE
[Feat]: QQNT大约1个月会出现登录失效的弹窗

### ISSUE THREAD

**Issue by bianyuan456** [NapNeko/NapCatQQ#118]
QQNT大约1个月会出现登录失效的弹窗，我在想能不能再框架侧或者插件侧，在大概登录了29天时实现退出并重新登录QQNT，来避免出现QQNT登录失效，导致插件没有效果的情况？
<img src="https://pic.imgdb.cn/item/6676fcead9c307b7e94e893e.png" alt="QQ图片20240623003247.png">
我的意思是，NapCatQQ可不可以新增功能API，新增登录指定QQ号码的API和关闭指定号码QQNT的API，来完成这个功能？

**Comment by layvsan** [comment]
1.一个月登陆失效的情况并不是必定出现，我自己使用的几个号都至少用了3个月了，出现这个更大概率是你的号有问题

**Comment by bianyuan456** [comment]
> 1.一个月登陆失效的情况并不是必定出现。 2.我自己使用的几个号都至少用了3个月了，出现这个更大概率是你的号有问题。

有道理，的确很大概率是我的号有问题。
但是在机器人QQ号在这种情况下，NapCatQQ能不能增加登录指定QQ号码的API和关闭指定号码QQNT的API，使我的这种号能去避免被这样下线，然后机器人无效果的情况发生呢。

**Comment by yuanzui-cf** [comment]
> > 1.一个月登陆失效的情况并不是必定出现。 2.我自己使用的几个号都至少用了3个月了，出现这个更大概率是你的号有问题。
> 
> 有道理，的确很大概率是我的号有问题。感谢你的回答。 但是在机器人QQ号在这种情况下，NapCatQQ能不能增加登录指定QQ号码的API和关闭指定号码QQNT的API，使我的这种号能去避免被这样下线，然后机器人无效果的情况发生呢。

你可以试试 set_restart api 来重启（？）

**Comment by MliKiowa** [comment]
一个月手动重启一次为最佳方案
