### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by XM2510136957** [NapNeko/NapCatQQ#128]
### 系统版本

ubuntu server 22.04

### QQNT 版本

QQ_3.2.10_240715_amd64_01.deb

### NapCat 版本

1.6.6

### OneBot 客户端

shiro

### 发生了什么?

我刚才更新QQ_3.2.10_240715_amd64_01，然后就报错了
![image](https://github.com/user-attachments/assets/63307390-dabd-4e53-a8c3-1d4d828c9e3b)

### 如何复现

我刚才更新QQ_3.2.10_240715_amd64_01，然后就报错了

### 期望的结果?

![image](https://github.com/user-attachments/assets/5e63333b-45cc-407c-aefc-fe2426c18540)

**Comment by MliKiowa** [comment]
回滚3.2.9

**Comment by MliKiowa** [comment]
或者使用docker
