### ISSUE TITLE
[BUG] 戳一戳返回信息缺失

### ISSUE THREAD

**Issue by Agnes4m** [NapNeko/NapCatQQ#136]
### 系统版本

ubuntu22.04

### QQNT 版本

linuxqq (3.2.9-24815)。

### NapCat 版本

1.6.7

### OneBot 客户端

nonebot==2.3.2，nonebot-adapter-onebot==2.4.3

### 发生了什么?

在今天更新1.6.7之前，戳一戳会返回信息，但是更新1.6.7后，信息收发可以操作，但是戳戳没了

### 如何复现

从1.5.x（大概时间来看应该是1.5.6-1.5.7）更新到1.6.7，文件直接覆盖

### 期望的结果?

可以正确响应戳戳时间，并且可以判断戳戳对象是否是自己

### NapCat 运行日志

```shell
2024-07-20 18:54:34 [INFO] (2550131148) | 开始连接反向ws ws://127.0.0.1:29213/onebot/v11/ws/ 
2024-07-20 18:54:34 [INFO] (2550131148) | 登录成功! 
[BuglyManager.cpp][UploadBugly][107]!!!in UploadBugly.
[NativeCrashHandler.cpp][getCrashDetailBeanFromRecord][52]!!!! in NativeCrashHandler getCrashDetailBeanFromRecord, open file error!!!,dumpFilePath:/root/.config/QQ/crash_files/rqd_record.eup.
[NativeCrashHandler.cpp][uploadCrashEvent][331]get null crashDetailBean, return!
```

### OneBot 客户端运行日志

```shell
无异常
```

**Comment by MliKiowa** [comment]
新版nc需要抬高QQ版本 
具体参考docker的脚本 xvfb+dbus+nc+qq 即可 https://github.com/NapNeko/NapCat-Docker

官方文档 https://napneko.github.io/zh-CN/guide/BootWay03 (linux需要配置xvfb与dbus 参考docker)


如果不会 就直接使用docker跑

**Comment by Agnes4m** [comment]
docker我不会用。。总是链接超时，文档里那个镜像也下载不了。。之前就试过docker不会用才直接下linuxqq来使用的

安装你的说法，我下最新的linuxqq 3.2.10，然后发现qq启动都失败了，然后换之前版本反复卸载安装也没办法解决了。。
以下是使用指令qq的报错，希望可以帮忙看看谢谢
```bash
ubuntu@VM-4-7-ubuntu:~/bot/qq$ qq
version_config_filename :/home/ubuntu/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :25765
config_base_version :3.2.10-25765
config_current_version :3.2.10-25765
app_build_version :25765
version_config_filename :/home/ubuntu/.config/QQ/versions/config.json
app_package_filename :/opt/QQ/resources/app/package.json
version_config_filename :/home/ubuntu/.config/QQ/versions/config.json
config_build_id :25765
config_base_version :3.2.10-25765
config_current_version :3.2.10-25765
app_build_version :25765
app_package_filename :/opt/QQ/resources/app/package.json
config_build_id :25765
config_base_version :3.2.10-25765
config_current_version :3.2.10-25765
app_build_version :25765
[preload] succeeded. /opt/QQ/resources/app/major.node
[preload] succeeded. /opt/QQ/resources/app/major.node
[1481727:0720/214922.901159:ERROR:ozone_platform_x11.cc(245)] Missing X server or $DISPLAY
[1481727:0720/214922.901202:ERROR:env.cc(258)] The platform failed to initialize.  Exiting.
段错误 (核心已转储)
```

**Comment by MliKiowa** [comment]
docker现在国内镜像不太好了 需要自己找一找镜像 参考这个 https://github.com/NapNeko/NapCat-Docker?tab=readme-ov-file#tips

至于说你现在这个问题对应

安装 dbus-daemon和xvfb

https://github.com/NapNeko/NapCat-Docker/blob/main/entrypoint.sh#L87

参考这个87-92行代码启动qq

对了启动前需要修改/opt/QQ/resources/app/app_launcher/index.js文件 参考

https://github.com/NapNeko/NapCat-Docker/blob/main/Dockerfile#L12

https://napneko.github.io/zh-CN/guide/BootWay03

如果还是不懂可以到q群或者tg群找开发和群友解决

**Comment by Agnes4m** [comment]
- 1、docker试过你链接的指令是失败的，我也没有海外服务器可以做代理
```
ubuntu@VM-4-7-ubuntu:~$ sudo docker pull hub-latest-3q02.onrender.com/mlikiowa/napcat-docker
Using default tag: latest
Error response from daemon: error parsing HTTP 404 response body: invalid character 'N' looking for beginning of value: "Not Found\n"
ubuntu@VM-4-7-ubuntu:~$ 
```

 - 2、无论是readme还是文档都没有找到群聊

**Comment by MliKiowa** [comment]
> * 1、docker试过你链接的指令是失败的，我也没有海外服务器可以做代理
> 
> ```
> ubuntu@VM-4-7-ubuntu:~$ sudo docker pull hub-latest-3q02.onrender.com/mlikiowa/napcat-docker
> Using default tag: latest
> Error response from daemon: error parsing HTTP 404 response body: invalid character 'N' looking for beginning of value: "Not Found\n"
> ubuntu@VM-4-7-ubuntu:~$ 
> ```
> 
> * 2、无论是readme还是文档都没有找到群聊

545402644
