### ISSUE TITLE
最新镜像 webui 无法加载二维码

### ISSUE THREAD

**Issue by Lemon-412** [NapNeko/NapCatQQ#139]
### 系统版本

linux/amd64 dockerhub latest

### QQNT 版本

linux/amd64 dockerhub latest

### NapCat 版本

linux/amd64 dockerhub latest

### OneBot 客户端

linux/amd64 dockerhub latest

### 发生了什么?

Linux 平台部署，使用最新镜像 [2aa79ec2891c linux/amd64]( https://hub.docker.com/layers/mlikiowa/napcat-docker/latest/images/sha256-2aa79ec2891c60e8f45469234d88d30bceaf5123a08324e27ad9b350f617707d?context=explore)

根据[教程](https://napneko.github.io/zh-CN/guide/getting-started)使用一键部署脚本：

```
curl -o napcat.sh https://fastly.jsdelivr.net/gh/NapNeko/NapCat-Installer@master/script/install.sh && sudo bash napcat.sh
```

配置选项
```
是否使用Docker安装？(y/n)
y
Docker已安装
请输入QQ号：
123
请选择模式（ws/reverse_ws/reverse_http）
ws
即将执行以下命令：docker run -d -e ACCOUNT=123 -e WS_ENABLE=true -p 3001:3001 -p 6099:6099 --name napcat --restart=always mlikiowa/napcat-docker:latest
是否继续？(y/n)
Y
```

容器启动成功，正常进入webui，**输入token后无法加载二维码**，导致无法登陆。

现象：
![@F$3{RA@{RY3(I(%E~%T33F](https://github.com/user-attachments/assets/d83684e9-eb56-46c8-aec0-b2d10ed746b7)

`logs -f` 容器日志除了超时似乎没有提供有用的信息：
![QJZD DZ6EX{JP~4@YI ATT9](https://github.com/user-attachments/assets/8e30a3a6-3996-434c-9b53-0d96017ea99c)

`exec -it bash` 手动执行 `qq --no-sandbox` 报错：
![1JJ$ZG6IL)%)OG()UHHYX_G](https://github.com/user-attachments/assets/866746b0-129a-4c47-8823-e044245fde92)

### 如何复现

如上。

### 期望的结果?

期望加载二维码实现登录。

**Comment by Lemon-412** [comment]
排查容器内部不通外网，导致二维码刷不出，暂设置 `network=host` 解决问题

**Comment by orphanEva** [comment]
我也碰到了，主要原因是 容器内部无法解析dns，可以通过配置dns解决
/etc/docker/daemon.json 
添加dns
"dns": ["223.5.5.5", "8.8.8.8"]
重启docker
systemctl daemon-reload
systemctl restart docker
