### ISSUE TITLE
[BUG] uin转换到uid时异常

### ISSUE THREAD

**Issue by wozaiha** [NapNeko/NapCatQQ#142]
### 系统版本

Win 11 23H2

### QQNT 版本

9.9.12-25765 (64位)

### NapCat 版本

1.6.7

### OneBot 客户端

Dice!

### 发生了什么?

获取.group diver时有时会显示所有人最后发言时间为19926天前（1970-1-1？）

### 如何复现

1.选取一个人数较多的群
2.私聊机器人或在群中查询潜水员
3.部分群可以正常获取数据，但大多数群会获取到错误数据

### 期望的结果?

显示正常的潜水人员及其最后发言时间

### NapCat 运行日志

```shell
2024-07-22 12:02:24 [WARN] 骰娘(*********) | uin转换到uid时异常 [id]
```

**Comment by MliKiowa** [comment]
有管理员的群才行

**Comment by wozaiha** [comment]
> 有管理员的群才行

骰子是管理的群（甚至是群主的群）有的也不行，使用人也必须是管理员吗？

**Comment by MliKiowa** [comment]
> > 有管理员的群才行
> 
> 骰子是管理的群（甚至是群主的群）有的也不行，使用人也必须是管理员吗？

管理员才能完整获取这些信息

**Comment by MliKiowa** [comment]
如果有问题 再开issue哦

**Comment by wozaiha** [comment]
> 如果有问题 再开issue哦

麻烦查看一下邮箱，进行了一次测试，相关log已附上

**Comment by MliKiowa** [comment]
> > 如果有问题 再开issue哦
> 
> 麻烦查看一下邮箱，进行了一次测试，相关log已附上

无管理员权限 数据可能会由数据库记录（数据库时间戳就是1970起始的 没有发言的无法更新数据 所以人越多越难记录） 但是如果有管理权限是可以稳定由远程QQ的群管理接口获取到

**Comment by wozaiha** [comment]
> > > 如果有问题 再开issue哦
> 
> > 
> 
> > 麻烦查看一下邮箱，进行了一次测试，相关log已附上
> 
> 
> 
> 无管理员权限 数据可能会由数据库记录（数据库时间戳就是1970起始的 没有发言的无法更新数据 所以人越多越难记录） 但是如果有管理权限是可以稳定由远程QQ的群管理接口获取到

但本次测试的群骰娘是群主…所以无法理解为什么会出现这种情况

**Comment by MliKiowa** [comment]
> > > > 如果有问题 再开issue哦
> > 
> > 
> > > 
> > 
> > 
> > > 麻烦查看一下邮箱，进行了一次测试，相关log已附上
> > 
> > 
> > 无管理员权限 数据可能会由数据库记录（数据库时间戳就是1970起始的 没有发言的无法更新数据 所以人越多越难记录） 但是如果有管理权限是可以稳定由远程QQ的群管理接口获取到
> 
> 但本次测试的群骰娘是群主…所以无法理解为什么会出现这种情况

你可以到qun.qq.com查看数据是否正常

**Comment by MliKiowa** [comment]
> 数据正常，至少有2位显示为1970-1-1的群员是有最后发言时间的 ![image](https://private-user-images.githubusercontent.com/18161911/351741392-8025381c-dfa9-41cf-8f9d-97029e388309.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MzEwOTEsIm5iZiI6MTcyMTgzMDc5MSwicGF0aCI6Ii8xODE2MTkxMS8zNTE3NDEzOTItODAyNTM4MWMtZGZhOS00MWNmLThmOWQtOTcwMjllMzg4MzA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDE0MTk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ3NmY5ZDNjYmY4MTA4MmJkZWRlNzNhMzljYzJkOWU0ZjY0NDI4MTAwYTA5MWNiOTI1ZjVkZDIxZjkzZWNhMzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-EmTLGvGOlCXP0GYDhqQx64IVMjKtvaI3tI4E4kRo8c) 这是其中之一的入群和最后发言时间

那可能我需要测测大群 之后我测测
