### ISSUE TITLE
【功能】可以增加加群的功能吗

### ISSUE THREAD

**Issue by mogocheal** [NapNeko/NapCatQQ#149]
可以增加加群的接口吗？
1.通过搜索内容获取群信息
2.增加加群的接口，通过群信息申请加群

**Comment by airdm** [comment]
你是想搞广告BOT吗?

**Comment by mogocheal** [comment]
> 你是想搞广告BOT吗?

不是的，就是想单纯的想使用加群的功能
我使用这个框架主要是想采集群消息，做分析使用，所以需要拓展信息渠道

**Comment by Guation** [comment]
搜索并返回群信息功能可能会有，主动加群是不会有的，你只能自己先加群后拉机器人加群
