### ISSUE TITLE
会考虑加入频道的API吗，gocq的那种

### ISSUE THREAD

**Issue by alexskim** [NapNeko/NapCatQQ#15]

**Comment by MliKiowa** [comment]
不会 频道都快凉了

**Comment by DGCK81LNN** [comment]
> > > > > 有没有考虑过支持QQ频道的API? 我是指就是用普通QQ身份在频道收发消息，不是q.qq.com那种官方机器人身份收发消息的
> > > >
> > > > 没有
> > >
> > > go-cqhttp 是有相关 API 和事件的
> >
> > 谢谢，可是go-cqhttp 已经停止更新快1年了。。go-cqhttp 的作者都建议迁移到别的框架了[Mrs4s/go-cqhttp#2471](https://github.com/Mrs4s/go-cqhttp/issues/2471)
> > 更重要的是go-cqhttp基本登录不上去，或者说侥幸登录上了会被冻结qq。。
> 
> qq频道官方基本上也是半弃坑状态，而且用的人其实不多
> 
> _Originally posted by huankong233 in https://github.com/NapNeko/NapCatQQ/issues/413#issuecomment-2381129671_

现在频道似乎又允许创建新讨论组了，属于是一定程度上恢复了可用性的状态。个人还是很希望能够支持频道收发的。

我刚安装了最新的NapCat，看起来似乎其实是能收到频道消息的，在日志中显示为“接收 <- 临时消息 (0)”。

另外，对于以上引用的讨论需要反驳的是，gocq 废了不影响我们可以继续兼容它的 API，llob、nc 现今已经实现了 gocq 的很多 API。

> 套盾：以上只是表达本人的一点小小希望，不管怎样，能有这样一个已经很优秀的项目，还是要感谢开发者大大(们)的付出

**Comment by sisi0318** [comment]
没有兼容频道api的打算
