### ISSUE TITLE
[BUG] 邀请机器人入群时，并没有上报被邀请入群消息

### ISSUE THREAD

**Issue by CuteReimu** [NapNeko/NapCatQQ#150]
### 系统版本

Linux VM-4-10-centos 4.18.0-348.7.1.el8_5.x86_64 无GUI界面

### QQNT 版本

Linux 3.2.9-24568

### NapCat 版本

v1.5.x 。不是最新版本，但我看了一下源代码，最近在相关部分只有日志改动，没有其它改动

### OneBot 客户端

自己写的项目，用onebot直连\
https://github.com/CuteReimu/onebot/blob/c0ede07dcd93cf23bc3b6a8c6409699d5195c12d/event.go#L153-L177

### 发生了什么?

按理说机器人被邀请时，应该会上报被邀请入群的消息，我看了一下代码也没什么问题：
https://github.com/NapNeko/NapCatQQ/blob/6b3343e1e470dac4098362c1f62c9b35e5f496cc/src/onebot11/main.ts#L527-L536

但实际上确实没上报。我看了NapCat的日志，并没有找到”收到邀请我加群通知“。我自己的OneBot客户端日志，也没有对应的收到推送的日志。

（除此之外，我的QQ号还没有手动同意，就自动入群了，按理说我也没设置过自动同意入群。入群后有成员数量增加的推送。）

<details><summary>相关文档</summary>
<p>

[https://github.com/botuniverse/onebot-11/blob/master/event/request.md#加群请求／邀请](https://github.com/botuniverse/onebot-11/blob/master/event/request.md#%E5%8A%A0%E7%BE%A4%E8%AF%B7%E6%B1%82%E9%82%80%E8%AF%B7)

> | 字段名 | 数据类型 | 可能的值 | 说明 |
> | ----- | ------ | -------- | --- |
> | `time` | number (int64) | - | 事件发生的时间戳 |
> | `self_id` | number (int64) | - | 收到事件的机器人 QQ 号 |
> | `post_type` | string | `request` | 上报类型 |
> | `request_type` | string | `group` | 请求类型 |
> | `sub_type` | string | `add`、`invite` | 请求子类型，分别表示加群请求、邀请登录号入群 |
> | `group_id` | number (int64) | - | 群号 |
> | `user_id` | number (int64) | - | 发送请求的 QQ 号 |
> | `comment` | string | - | 验证信息 |
> | `flag` | string | - | 请求 flag，在调用处理请求的 API 时需要传入 |

</p>
</details> 

### 如何复现

1. 邀请机器人入群

### 期望的结果?

应该上报被邀请入群的消息

**Comment by MliKiowa** [comment]
有的邀请是这样的 但是确实nc没推送新版已经修了 之后试了新版 如果还有问题开新的issue
