### ISSUE TITLE
安装QQ提示 update-desktop-database: command not found[BUG] 

### ISSUE THREAD

**Issue by saferabbit** [NapNeko/NapCatQQ#151]
### 系统版本

Ubuntu22.04

### QQNT 版本

3.2.10-25765

### NapCat 版本

1.6.7

### OneBot 客户端

未连接

### 发生了什么?

正在设置 linuxqq (3.2.10-25765) ...
/var/lib/dpkg/info/linuxqq.postinst: line 10: update-desktop-database: command not found

是否现在需要桌面模式才能安装新版QQ？

### 如何复现

执行安装QQ时候发现有错误

### 期望的结果?

解决安装QQ问题

**Comment by MliKiowa** [comment]
使用docker 秒解决

**Comment by MliKiowa** [comment]
手动安装 需要完整QQ环境 然后修补index.js让QQ加载napcat

**Comment by UlicaLopez** [comment]
我debian11安装3.2.9版的qq也有这个报错，但是不影响使用，如果能正常使用napcat应该不用管？

**Comment by sckiyo** [comment]
update-desktop-database属于desktop-file-utils包
```
sudo apt install desktop-file-utils
```
然后可以手动运行一下，并重新配置
```
sudo update-desktop-database
sudo dpkg --configure -a
```

**Comment by saferabbit** [comment]
> update-desktop-database属于desktop-file-utils包
> 
> ```
> sudo apt install desktop-file-utils
> ```
> 
> 然后可以手动运行一下，并重新配置
> 
> ```
> sudo update-desktop-database
> sudo dpkg --configure -a
> ```

感谢大佬指引，已正常安装了
