### ISSUE TITLE
[BUG] 发送图片意外崩溃

### ISSUE THREAD

**Issue by Stapxs** [NapNeko/NapCatQQ#152]
### 系统版本
Docker

### NapCat 版本
1.6.6

### 发生了什么?
<img width="999" alt="image" src="https://github.com/user-attachments/assets/c112ca10-5333-482f-8ef9-f85f5047112f">

发送图片报错，log 显示的为旧图床链接 emmmm 不知道是不是因为和签名服务连接不稳定导致的（x
我这破网络有时候连不上签名服务（恼

参考消息：
~~~
{
    "action": "send_group_msg",
    "params": {
        "group_id": xxxxxxxxxx,
        "message": [
            {
                "type": "image",
                "data": {
                    "file": "base64://（230KB 的 base64 图片)"
                }
            }
        ]
    },
    "echo": "sendMsgBack_uuid_a468a07b-f5c1-4e4b-a813-a2ee9fd562d2"
}
~~~

**Comment by MliKiowa** [comment]
这个结束信号是管道破裂 可能是ws炸了

**Comment by Stapxs** [comment]
那可能是传的文件太大了？🤔
虽然说我会主动压一次图，看来得再压小一点了
