### ISSUE TITLE
看到了某个师傅的博客，想问问有没有基于Python+napcatQQ开发功能的文档可以看

### ISSUE THREAD

**Issue by W1ndys** [NapNeko/NapCatQQ#156]
看到了某个师傅的博客，用Python自己开发功能，想问问有没有基于Python+napcatQQ开发功能的文档可以看，比如语法怎么写，怎么收发消息，处理消息等的

**Comment by MliKiowa** [comment]
搜索nonebot2

**Comment by W1ndys** [comment]
> 搜索nonebot2

thank you!
