### ISSUE TITLE
[BUG] 调用get_group_list时会返回已被踢出/退出的群

### ISSUE THREAD

**Issue by yuuki-nya** [NapNeko/NapCatQQ#16]
### 系统版本

Windows Server 2022

### QQNT 版本

9.9.9-22741 

### NapCat 版本

1.2.0

### OneBot 客户端

nonebot2

### 发生了什么?

https://github.com/LLOneBot/LLOneBot/issues/193

和这个一样，后续ll修复了

### 如何复现

退群后调用get_group_list，已退的群还在

### 期望的结果?

退群后应该不在get_group_list里

**Comment by MliKiowa** [comment]
下个版本会尝试修复

**Comment by MliKiowa** [comment]
已修 抢先可以尝试 https://github.com/NapNeko/NapCatQQ/actions/runs/9051914376 下个版本发布会正式加入
