### ISSUE TITLE
Linux一直提示有新版

### ISSUE THREAD

**Issue by W1ndys** [NapNeko/NapCatQQ#161]
2024-07-27 14:09:46 [INFO] () | [NapCat] 当前版本: 1.6.7 
2024-07-27 14:09:46 [WARN] () | [NapCat] 检测到更新,请前往 https://github.com/NapNeko/NapCatQQ 下载 NapCatQQ V 1.6.9 

看到仓库里最新就是1.6.7

**Comment by Starrain08** [comment]
> 2024-07-27 14:09:46 [INFO] () | [NapCat] 当前版本: 1.6.7 2024-07-27 14:09:46 [WARN] () | [NapCat] 检测到更新,请前往 https://github.com/NapNeko/NapCatQQ 下载 NapCatQQ V 1.6.9
> 
> 看到仓库里最新就是1.6.7

不用管，这是开发者还没改，1.6.9出现很多bug，回退了

**Comment by W1ndys** [comment]
> > 2024-07-27 14:09:46 [INFO] () | [NapCat] 当前版本: 1.6.7 2024-07-27 14:09:46 [WARN] () | [NapCat] 检测到更新,请前往 https://github.com/NapNeko/NapCatQQ 下载 NapCatQQ V 1.6.9
> > 看到仓库里最新就是1.6.7
> 
> 不用管，这是开发者还没改，1.6.9出现很多bug，回退了

好的，谢谢
