### ISSUE TITLE
[功能请求] 请求支持接收和发送多层node的合并转发消息

### ISSUE THREAD

**Issue by 2455DD** [NapNeko/NapCatQQ#165]
如果可能的话，希望Napcat在未来的某个版本可以支持接收和发送多层node的合并转发消息，样例消息如下所示：
![image](https://github.com/user-attachments/assets/86883e05-d772-4c91-9e23-0820846a6708)

**Comment by MliKiowa** [comment]
未来几个版本支持

**Comment by MliKiowa** [comment]
现在新版本能否发送多层node

**Comment by MliKiowa** [comment]
多层合并转发解析已经完成

**Comment by MliKiowa** [comment]
多层合并发送下次做

**Comment by MliKiowa** [comment]
多层合并已经初步完成 ea678d805dd9f5e9f2f8d3980fe98adc3c2d243b

**Comment by MliKiowa** [comment]
v1.8.2已经完全支持多层合并解析和发送
