### ISSUE TITLE
请问有各种消息的JSON例子文档可以看吗👀

### ISSUE THREAD

**Issue by W1ndys** [NapNeko/NapCatQQ#166]
只找到了这个https://napneko.github.io/zh-CN/develop/event

我想找找各种事件所上报的JSON格式，便于开发的时候调试

**Comment by lingdu2333** [comment]
直接查看onebot开发文档 napcat只是前端

**Comment by W1ndys** [comment]
> 直接查看onebot开发文档 napcat只是前端

看了一下了解了，谢谢
