### ISSUE TITLE
[BUG] 无法获取到视频消息

### ISSUE THREAD

**Issue by W1ndys** [NapNeko/NapCatQQ#168]
### 系统版本

Linux Ubuntu

### QQNT 版本

ii  linuxqq                               3.2.9-24815                             amd64    

### NapCat 版本

1.6.7

### OneBot 客户端

自己写的Python

### 发生了什么?

视频消息获取错误

### 如何复现

发视频测试
或许与这个issues类似。https://github.com/NapNeko/NapCatQQ/issues/70#/

### 期望的结果?

应当接收到视频消息

### NapCat 运行日志

```shell
应该是视频的日志，但是显示下面
2024-07-28 23:00:05 [ERROR] 卷卷(3649056059) | constructMessage error:  {} 
2024-07-28 23:00:06 [ERROR] 卷卷(3649056059) | constructMessage error:  {} 
2024-07-28 23:00:06 [ERROR] 卷卷(3649056059) | constructMessage error:  {} 
2024-07-28 23:00:07 [ERROR] 卷卷(3649056059) | constructMessage error:  {}
```

### OneBot 客户端运行日志

```shell
不再赘述，没有cq的video类型的消息
```

**Comment by W1ndys** [comment]
消息没脱敏（），不过也无所谓了，没有什么太敏感的数据

**Comment by MliKiowa** [comment]
之后将进行测试

**Comment by MliKiowa** [comment]
之后的新版 如果还有问题 到官方群来进行测试

**Comment by W1ndys** [comment]
> 之后的新版 如果还有问题 到官方群来进行测试

好的，**感谢**

**Comment by W1ndys** [comment]
喜报，确认该bugbei被修复了
![image](https://github.com/user-attachments/assets/3c2ad145-fc18-4baf-9acf-e135a1ff3a96)
