### ISSUE TITLE
[BUG] 更新到最新版本后无法获取文件

### ISSUE THREAD

**Issue by Cola-Ace** [NapNeko/NapCatQQ#169]
### 系统版本

Ubuntu 22.04 Docker

### QQNT 版本

Linux 3.2.9-26000

### NapCat 版本

1.7.0

### OneBot 客户端

api调试工具

### 发生了什么?

在QQ群发送文件后，我像往常一样尝试获取文件，但无论使用哪个api，都会报file not found的错误，这在稍旧版本的NapCat上并不会出现

### 如何复现

尝试获取文件时会出现

### 期望的结果?

正常将文件下载到本地

**Comment by Cola-Ace** [comment]
另外，如果直接传入文件名的话就可以正常下载

**Comment by MliKiowa** [comment]
最近在重构这个 勉强用用吧

**Comment by MliKiowa** [comment]
已重构完成

**Comment by MliKiowa** [comment]
下个版本可以进行测试
