### ISSUE TITLE
yobot框架可以用napcatqq接收消息但无法发送消息

### ISSUE THREAD

**Issue by Linkiesr** [NapNeko/NapCatQQ#17]
### 系统版本

Ubuntu 20.04

### QQNT 版本

Linux QQ 2.3.7-23361

### NapCat 版本

NapCat V1.3.0

### OneBot 客户端

nonebot

### 发生了什么?

yobot可以从Napcat的反向websocket中获取消息，但没办法将消息通过Napcat发送出去

### 如何复现

all

### 期望的结果?

yobot通过Napcat的反向websocket正常收发消息

**Comment by MliKiowa** [comment]
请给出相关日志

**Comment by Linkiesr** [comment]
2024-05-09 22:52:11 [DEBUG] 康纳(206528765)
收到反向Websocket消息 {"action":".handle_quick_operation_async","params":{"context":{"self_id":2034711369,"user_id":951354255,"time":1715266330,"message_id":-2147483397,"real_id":-2147483397,"message_type":"group","sender":{"user_id":10255483,"nickname":"xxx","card":"xxx","role":"owner"},"raw_message":"状态","font":14,"sub_type":"normal","message":[{"data":{"text":"状态"},"type":"text"}],"message_format":"array","post_type":"message","group_id":961792584},"operation":{"reply":"[CQ:image,file=base64:///9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAIBAQEBAQIBAQECAgICAgQDAgICAgUEBAMEBgUGBgYFBgYGBwkIBgcJBwYGCAsICQoKCgoKBggLDAsKDAkKCgr/2wBDAQICAgICAgUDAwUKBwYHCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgr/wAARCAN1A44DASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLD...","at_sender":false}},"echo":{"seq":3}}
﻿
2024-05-09 22:52:11 [DEBUG] 康纳(206528765)
ws 消息上报 ws://119.23.108.174:9222/ws/ {"status":"failed","retcode":1404,"data":null,"message":"不支持的api .handle_quick_operation_async","wording":"不支持的api .handle_quick_operation_async","echo":{"seq":3}}
﻿

**Comment by Linkiesr** [comment]
2024-05-09 22:52:06 [DEBUG] 康纳(206528765)
ws 消息上报 ws://119.23.108.174:9222/ws/ {"self_id":206528765,"user_id":961792584,"time":1715266326,"message_id":-2147483398,"real_id":-2147483398,"message_type":"private","sender":{"user_id":961792584,"nickname":"愚かな人","card":""},"raw_message":"登录","font":14,"sub_type":"friend","message":[{"data":{"text":"登录"},"type":"text"}],"message_format":"array","post_type":"message"}
﻿
2024-05-09 22:52:06 [DEBUG] 康纳(206528765)
收到反向Websocket消息 {"action":".handle_quick_operation_async","params":{"context":{"self_id":206528765,"user_id":961792584,"time":1715266326,"message_id":-2147483398,"real_id":-2147483398,"message_type":"private","sender":{"user_id":961792584,"nickname":"愚かな人","card":"愚かな人"},"raw_message":"登录","font":14,"sub_type":"friend","message":[{"data":{"text":"登录"},"type":"text"}],"message_format":"array","post_type":"message"},"operation":{"reply":"如果无法打开，请仔细阅读教<feff>程中《链接无法打开》的说明","at_sender":false}},"echo":{"seq":2}}
﻿

**Comment by MliKiowa** [comment]
不支持异步快速操作

**Comment by MliKiowa** [comment]
最新版已支持
