### ISSUE TITLE
[feat] webui添加新功能，及一个bug

### ISSUE THREAD

**Issue by layvsan** [NapNeko/NapCatQQ#172]
### 系统版本

centos 7

### QQNT 版本

3.2.4

### NapCat 版本

1.6.4

### OneBot 客户端

11

### 发生了什么?

这是一个建议方向的issue
1.webui增加快速重启bot的功能
2.webui增加快速修改登陆密码的功能，（docker内改webui密码属实蛋疼）

bug
1.bot被tx踢下线后，会一直卡在最后一条消息没动静。必须重启bot了才会提示【当前登陆信息已失效，请重新扫码或修改密码后重新登陆】，但是napcat会将当前bot状态识别为在线，导致不会自动关闭bo

### 如何复现

部分风控较高的账号，得挂的久了才有概率被tx下线

### 期望的结果?

如建议

**Comment by MliKiowa** [comment]
未来会考虑的

**Comment by MliKiowa** [comment]
现在还没什么时间 因为在做其他的
