### ISSUE TITLE
一个对LinuxQQ安装的疑问

### ISSUE THREAD

**Issue by W1ndys** [NapNeko/NapCatQQ#174]
为什么我在Ubuntu安装的很顺利，在centos安装的报错百出。
centos安装时的报错
```
[root@ser630470926044 NapCat.linux.x64]# ./napcat.sh 
/opt/QQ/qq: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /opt/QQ/qq)
/opt/QQ/qq: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/QQ/qq)
```
在Ubuntu一气呵成直接安装完成

https://napneko.github.io/zh-CN/guide/getting-started#%E5%AE%89%E8%A3%85-qq
能否细说一下安装LinuxQQ这边的文档

而且我怀疑，我找的[LinuxQQ官网](https://im.qq.com/linuxqq/index.shtml#/)是不是找错了
官网里说了
```
每一个安装包会按照形如如下的格式命名：
linuxqq_3.0.0-100_x86_64.rpm
[产品名]_[版本号]_[架构].[格式]
```
但是最新版的命名却是`QQ_3.2.10_240715_amd64_01.rpm`，货不对板

最后我还是找tg群组找到一个专门存安装包的频道，才找到命名格式正确的安装包（）

**感觉这个问题可能没必要问，或者像个弱智问的问题，但我真的感觉我找错LinuxQQ了（**

**Comment by MliKiowa** [comment]
没有问题

**Comment by MliKiowa** [comment]
tg频道是对的

**Comment by W1ndys** [comment]
> tg频道是对的

那请问官网的安装包是有问题吗，他那个命名就不对

**Comment by W1ndys** [comment]
然后刚刚测试了一下，linuxqq_3.2.9-24815_amd64.deb 可以正常用，linuxqq_3.2.10-25765_arm64.deb 需要一些依赖导致安装失败，有点好奇，是因为腾讯加了新依赖吗

**Comment by W1ndys** [comment]
https://napneko.github.io/zh-CN/guide/version
原来这里有LinuxQQ的链接😁😁😁一直没发现，太赞了

**Comment by ZhaoZuohong** [comment]
> 在centos安装的报错百出
> ```
> `GLIBC_2.18' not found
> `GLIBC_2.25' not found
> ```

可能是因为 CentOS 的 glibc 版本太低，可以试试用容器。

**Comment by W1ndys** [comment]
> > 在centos安装的报错百出
> > ```
> > `GLIBC_2.18' not found
> > `GLIBC_2.25' not found
> > ```
> 
> 可能是因为 CentOS 的 glibc 版本太低，可以试试用容器。

谢谢，现在已经迁移到容器安装了
