### ISSUE TITLE
[BUG] 群聊戳一戳上报消息结构与onebot11标准不符，且字段raw_message为object类型 (FollowUp #173)

### ISSUE THREAD

**Issue by Fripine** [NapNeko/NapCatQQ#184]
### 系统版本

Windows Server 2022 Datacenter

### QQNT 版本

9.9.12-25765

### NapCat 版本

1.6.7和1.7.0

### OneBot 客户端

onebot v11

### 发生了什么?

群聊戳一戳上报消息结构与onebot11标准不符，根据onebot11标准，群聊戳一戳上报数据没有raw_message字段，详见https://github.com/botuniverse/onebot-11/blob/d4456ee706f9ada9c2dfde56a2bcfc69752600e4/event/notice.md?plain=1#L138-L151

而在napcat里群聊戳一戳上报数据多了raw_message，详见
https://github.com/NapNeko/NapCatQQ/blob/b3c7a91f3d826f343bbcf596e975f295204168d4/src/onebot11/event/notice/OB11PokeEvent.ts#L22C1-L33

**由于多出的raw_message导致一些onebot客户端对接napcat后无法正常解析群聊戳一戳事件**

且onebot11标准里有的raw_message字段类型应为string，详见
https://github.com/botuniverse/onebot-11/blob/d4456ee706f9ada9c2dfde56a2bcfc69752600e4/event/message.md?plain=1#L58

能否统一一下标准，删除群聊戳一戳上报数据中的raw_message字段，或是将raw_message字段改为string类型

### 如何复现

群聊进行戳一戳

### 期望的结果?

删除群聊戳一戳上报数据中的raw_message字段，或是将raw_message字段改为string类型

### NapCat 运行日志

```shell
ws 消息上报  {"time":1722245276,"self_id":1004205930,"post_type":"notice","notice_type":"notify","sub_type":"poke","target_id":644978184,"user_id":478931495,"group_id":883510605,"raw_message":[{"col":"1","nm":"","type":"qq","uid":"u_QfVhzzfXau71NW0Oetp-Vw"},{"jp":"https://zb.vip.qq.com/v2/pages/nudgeMall?_wv=2&actionId=1","src":"http://tianquan.gtimg.cn/nudgeaction/item/1/expression.jpg","type":"img"},{"txt":"拍了拍","type":"nor"},{"col":"1","nm":"","tp":"0","type":"qq","uid":"u_dN95nmkhDE962ezzl0WfyQ"},{"txt":"的希望肉罐头和希望大衣","type":"nor"}]}
```

### OneBot 客户端运行日志

```shell
无
```

**Comment by Fripine** [comment]
Follow up #173

**Comment by MliKiowa** [comment]
有道理的 我觉得改成 raw_info 避开这个问题
