### ISSUE TITLE
[Feat] 支持好友添加成功事件上报 (FollowUp #84)

### ISSUE THREAD

**Issue by Fripine** [NapNeko/NapCatQQ#185]
### 系统版本

Windows Server 2022 Datacenter

### QQNT 版本

9.9.12-25765

### NapCat 版本

1.6.7和1.7.0

### OneBot 客户端

onebot v11

### 发生了什么?

我在早期的napcat版本里提了PR https://github.com/NapNeko/NapCatQQ/pull/8 实现了这个事件的上报，不知道为什么后续哪个版本给删除了，刚刚看了一下字段数据全有，是出于什么原因或考虑删除了这个事件的上报？

  msgType: 5,
  subMsgType: 12,
  sendType: 3,
  peerUin: '1xxxxxx',

### 如何复现

添加好友

### 期望的结果?

好友添加成功后有事件上报

**Comment by MliKiowa** [comment]
我也不太清楚了

**Comment by Fripine** [comment]
> 我也不太清楚了

后续有计划继续支持这个事件的上报吗？
请注意，好友添加成功事件 与 好友添加事件 是两个不同的事件，可能当时重构时遗漏了？

**Comment by Fripine** [comment]
> 我也不太清楚了

已定位到该事件的实现于1.5.3版本被移除，是什么原因？

**Comment by MliKiowa** [comment]
> > 我也不太清楚了
> 
> 已定位到该事件的实现于1.5.3版本被移除，是什么原因？

应该是重构flag生成时移除了 你试试pr回来？

**Comment by Fripine** [comment]
> > > 我也不太清楚了
> > 
> > 
> > 已定位到该事件的实现于1.5.3版本被移除，是什么原因？
> 
> 应该是重构flag生成时移除了 你试试pr回来？

好的
