### ISSUE TITLE
[BUG] 邀请加群消息无法上报 (FollowUp #176)

### ISSUE THREAD

**Issue by Fripine** [NapNeko/NapCatQQ#193]
### 系统版本

Windows 10

### QQNT 版本

QQ9.9.12-26466

### NapCat 版本

1.7.3

### OneBot 客户端

无

### 发生了什么?

没有定位到是napcat的哪一个版本开始，邀请入群消息无法上报，导致BOT客户端无法响应入群邀请

在下面这段代码中可以看到群通知类型若包含**GroupNotifyTypes.INVITE_ME**，则不会进行post
https://github.com/NapNeko/NapCatQQ/blob/6c02cedb1ea8b09a3996f50c24ee6421155a19d8/src/onebot11/main.ts#L286-L291

进入**postGroupNotifies**的实现可以看到，有针对通知类型为GroupNotifyTypes.INVITE_ME的处理，那么逻辑上，GroupNotifyTypes.INVITE_ME类型事件不会得到处理（被过滤了）
https://github.com/NapNeko/NapCatQQ/blob/6c02cedb1ea8b09a3996f50c24ee6421155a19d8/src/onebot11/main.ts#L547-L556

postGroupNotifies除了在groupListener.onGroupNotifiesUpdated事件触发，还会在groupListener.onMemberInfoChange事件触发，根据名字推断应该是群成员信息变化事件，与邀请bot入群没有关联
https://github.com/NapNeko/NapCatQQ/blob/6c02cedb1ea8b09a3996f50c24ee6421155a19d8/src/onebot11/main.ts#L324

### 如何复现

邀请BOT入群

### 期望的结果?

正常上报邀请入群事件

**Comment by MliKiowa** [comment]
# 5fe3422469f14868fbfd450b6730ba33dce18546
