### ISSUE TITLE
[BUG] 无法在某些群内发送任何图片

### ISSUE THREAD

**Issue by cokll** [NapNeko/NapCatQQ#194]
### 系统版本

Windows server2022

### QQNT 版本

Windows 9.9.12-26000 

### NapCat 版本

V1.7.2

### OneBot 客户端

0f8af27

### 发生了什么?

` 获取rkey失败 {"errno":-4039,"code":"ETIMEDOUT","syscall":"connect","address":"172.67.154.239","port":2082}`

### 如何复现

发送图片 [CQ:image,file=http://127.0.0.1/images/xx.png]

### 期望的结果?

正常发送图片 或者 图片获取失败时忽略图片正常发送文字

### NapCat 运行日志

```shell
` 获取rkey失败 {"errno":-4039,"code":"ETIMEDOUT","syscall":"connect","address":"172.67.154.239","port":2082}`
```

**Comment by MliKiowa** [comment]
试试新版本呢

**Comment by lumia1998** [comment]
> 试试新版本呢

docker的1.7.3还是这样

**Comment by cokll** [comment]
@MliKiowa 新版本相同 手动访问url正常 但是就是报找不到图片 还有新版本也无法处理加群消息了

**Comment by lumia1998** [comment]
> @MliKiowa 新版本相同 手动访问url正常 但是就是报找不到图片 还有新版本也无法处理加群消息了

发图的rkey你看好没好?我换个科学就好了我看周围别的人的也好了
