### ISSUE TITLE
[Bug]1.7.4 BOT被踢出群会报错.

### ISSUE THREAD

**Issue by airdm** [NapNeko/NapCatQQ#196]
(node:1336) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'type')
    at groupListener.onGroupNotifiesUpdated (file:///C:/Program%20Files/Tencent/QQNT/resources/app/app_launcher/napcat/napcat.mjs:27590:128)
(node:1336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 26)

以上是日志

**Comment by MliKiowa** [comment]
尝试提升QQ版本

**Comment by airdm** [comment]
(node:4628) UnhandledPromiseRejectionWarning: TypeError: Cannot read properties of undefined (reading 'type')
    at groupListener.onGroupNotifiesUpdated (file:///C:/Program%20Files/Tencent/QQNT/resources/app/app_launcher/napcat/napcat.mjs:27664:128)
(node:4628) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 64)

升级1.7.6后 QQNT也是最新版本 踢出群后还会弹出这一段 程序没有崩溃 这个报错好像没有影响什么.

**Comment by MliKiowa** [comment]
降级回去

**Comment by MliKiowa** [comment]
好像是个bug

**Comment by MliKiowa** [comment]
暂时没有更多信息 先关闭 有问题群里at下我
