### ISSUE TITLE
[BUG] napcat运行报错，docker容器安装

### ISSUE THREAD

**Issue by W1ndys** [NapNeko/NapCatQQ#199]
### 系统版本

Linux Ubuntu

### QQNT 版本

docker镜像内的

### NapCat 版本

docker镜像内的

### OneBot 客户端

自己写的Python

### 发生了什么?

发生错误 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:
{
    "result": 1,
    "errMsg": ""
}

### 如何复现

偶然

### 期望的结果?

.

### NapCat 运行日志

```shell
发生错误 Error: Timeout: NTEvent EventName:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:
{
    "result": 1,
    "errMsg": ""
}
```

**Comment by MliKiowa** [comment]
重新拉取最新的试试

**Comment by lumia1998** [comment]
你对接koishi啥的试试

**Comment by W1ndys** [comment]
> 重新拉取最新的试试

测试发现，当机器人被禁言，需要发消息的时候会爆这个错误

**Comment by MliKiowa** [comment]
好的
