### ISSUE TITLE
[BUG] 没有收到群成员减少事件

### ISSUE THREAD

**Issue by 1411484730** [NapNeko/NapCatQQ#20]
### 系统版本

Ubuntu 22.04.4 LTS

### QQNT 版本

Linux 3.2.7-23361

### NapCat 版本

1.3.3

### OneBot 客户端

None

### 发生了什么?

Napcat没有接收到群成员减少事件，控制台无输出无日志

### 如何复现

群组成员主动退群/被踢出

### 期望的结果?

修复添加群成员减少事件的支持

**Comment by MliKiowa** [comment]
已初步定位到问题了 下个版本修复

**Comment by MliKiowa** [comment]
下个版本修复

**Comment by MliKiowa** [comment]
问一下 群成员减少是不是非管理员的群无法触发 你试试有管理权限的群

**Comment by 1411484730** [comment]
测试管理员下可触发，非管理员下则无法触发

**Comment by MliKiowa** [comment]
https://github.com/NapNeko/NapCatQQ/actions 试试这个版本

**Comment by 1411484730** [comment]
非管理员可以收到事件，但是事件子类型（leave、kick、kick_me）似乎不正常，没有区分出主动退群和踢出群组

**Comment by MliKiowa** [comment]
没办法区分 非管理看不到操作行为

**Comment by 1411484730** [comment]
好的

**Comment by 1411484730** [comment]
更新到1.3.6版本后

**Comment by 1411484730** [comment]
群成员减少事件再次失效，群组非管理员无法获取事件。nb日志提示超时。ncqq版本为1.4.0beta6

**Comment by MliKiowa** [comment]
好的 到时候测测 给出QQ版本

**Comment by 1411484730** [comment]
qq版本同原来不变

**Comment by MliKiowa** [comment]
已修 尝试https://github.com/NapNeko/NapCatQQ/actions/runs/9217890120

**Comment by 1411484730** [comment]
更新：更新到1.4.1后非群组管理员下群成员减少事件还是没有收到，并有
群成员名片变更事件失效

**Comment by MliKiowa** [comment]
稍后尝试v1.4.2

**Comment by 1411484730** [comment]
自测1.4.2可以了
