### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by xmexg** [NapNeko/NapCatQQ#207]
### 系统版本

不知道

### QQNT 版本

不知道

### NapCat 版本

不知道

### OneBot 客户端

不知道

### 发生了什么?

不知道，他没说

### 如何复现

不知道

### 期望的结果?

不知道
![image](https://github.com/user-attachments/assets/06bfa9ad-937f-4d9f-adfb-bcf10d9cb8b8)

![4c7ec5b2fe1ca37cfddcab0b7ddd0c09](https://github.com/user-attachments/assets/89302c58-ee97-4e39-a65d-c00d8d9e37d8)

**Comment by ttk886** [comment]
前来瞻仰

**Comment by MliKiowa** [comment]
已修
