### ISSUE TITLE
[BUG] 进入 web ui 报错

### ISSUE THREAD

**Issue by kanocence** [NapNeko/NapCatQQ#211]
### 系统版本

ubuntu 20

### QQNT 版本

-

### NapCat 版本

1.7.8

### OneBot 客户端

-

### 发生了什么?

![image](https://github.com/user-attachments/assets/97f312cf-6ec2-4f78-84a9-101889aeece4)
![image](https://github.com/user-attachments/assets/aef39396-251a-49dc-92de-5dcfead1afb1)

登陆成功后跳转 /webui/config.html 页面报错

### 如何复现

我使用的 docker compose

version: "3"
services:
    napcat:
        environment:
            - ACCOUNT=123
            - WS_ENABLE=true
            - HTTP_ENABLE=true
        ports:
            - 3000:3000
            - 3001:3001
            - 6099:6099
        container_name: napcat
        network_mode: bridge
        restart: always
        image: mlikiowa/napcat-docker:latest

### 期望的结果?

-

**Comment by MliKiowa** [comment]
network看看呢

**Comment by kanocence** [comment]
返回了这些
/api/OB11Config/GetConfig
```json
{
    "code": 0,
    "message": "success",
    "data": {
        "httpHost": "",
        "enableHttp": true,
        "httpPort": 3000,
        "wsHost": "",
        "enableWs": true,
        "wsPort": 3001,
        "enableWsReverse": false,
        "wsReverseUrls": [],
        "enableHttpPost": false,
        "httpPostUrls": [],
        "enableHttpHeart": false,
        "httpSecret": "",
        "messagePostFormat": "array",
        "reportSelfMessage": false,
        "debug": false,
        "enableLocalFile2Url": false,
        "heartInterval": 45000,
        "musicSignUrl": ""
    }
}
```

**Comment by MliKiowa** [comment]
删掉老的配置文件

**Comment by MliKiowa** [comment]
再次运行就可以了

**Comment by kanocence** [comment]
> 再次运行就可以了

已经可以了😘
