### ISSUE TITLE
[BUG] `message_id`字段与OneBot11标准不符

### ISSUE THREAD

**Issue by kuttakke** [NapNeko/NapCatQQ#213]
### 系统版本

Linux Docker

### QQNT 版本

3.2.12-26702

### NapCat 版本

v1.7.9

### OneBot 客户端

overflow-2.16.0-0142120-SNAPSHOT

### 发生了什么?

NapCat返回的`message_id`、`real_id`字段类型不符合OneBot-11标准规定的`Int32`

```json
{
  "self_id": XXXXXXXXX,
  "user_id": XXXXXXXXX,
  "time": 1722894913,
  "message_id": 3425462029,
  "message_seq": 3425462029,
  "real_id": 3425462029,
  "message_type": "group",
  "sender": {
    "user_id": XXXXXXXXX,
    "nickname": "XXXXXXXXX",
    "card": "",
    "role": "owner"
  },
  "raw_message": "createMsg",
  "font": 14,
  "sub_type": "normal",
  "message": [
    {
      "data": {
        "text": "createMsg"
      },
      "type": "text"
    }
  ],
  "message_format": "array",
  "post_type": "message",
  "group_id": XXXXXXXXX
}
```

[附上标准：](https://github.com/botuniverse/onebot-11/blob/master/api/public.md#get_msg-%E8%8E%B7%E5%8F%96%E6%B6%88%E6%81%AF)

| 字段名         | 数据类型    | 说明       |
| ------------ | ------- | ---------- |
| `time`       | number (int32) | 发送时间   |
| `message_type` | string | 消息类型，同 [消息事件](../event/message.md) |
| `message_id` | number (int32) | 消息 ID     |
| `real_id` | number (int32) | 消息真实 ID     |
| `sender`     | object  | 发送人信息，同 [消息事件](../event/message.md) |
| `message`    | message | 消息内容   |

### 如何复现

群聊和私聊都有大概率触发

### 期望的结果?

希望能够符合`Int32`

**Comment by MliKiowa** [comment]
事实上就是uint32 有什么问题吗

**Comment by kuttakke** [comment]
你好，请问是指onebot的`message_id`实际规定的是`uint32`吗？如果是的话，这与我找到并贴在上面的标准不同。
或许我犯了什么错误，比如该仓库并不是OneBot11标准，或者标准经过更新？

**Comment by MliKiowa** [comment]
我错了

**Comment by MliKiowa** [comment]
马上修复 1.8.0
