### ISSUE TITLE
[Refactor Needed] [疑问] 群文件API

### ISSUE THREAD

**Issue by chuxiaaaa** [NapNeko/NapCatQQ#232]
我看到NapCat只实现了go-cqhttp的上传群文件API。

但我在扩展API列表中看到其他群文件的API也实现了，但和go-cqhttp不一样，想知道这样设计的原因。后续有计划以go-cqhttp的方式实现吗

**NapCat群文件相关接口**
```
/get_group_file_count {group_id}
/get_group_file_list {group_id}
/set_group_file_folder {group_id}
/del_group_file {group_id,file_id}
/del_group_file_folder {group_id,folder_id}
```

**Comment by MliKiowa** [comment]
有的未标准化

**Comment by MliKiowa** [comment]
完全标准化还需要时间

**Comment by Wesley-Young** [comment]
目前 gocq 风格的群文件 API 实现情况：

* `/upload_group_file` - 已实现
* `/delete-group-file` - 已实现，复用逻辑
* `/create_group_file_folder` - 已实现，复用逻辑
* `/delete_group_folder` - 已实现，复用逻辑
* `/get_group_file_system_info` - **部分实现**，只能获取群文件总数
* `/get_group_root_files` - 已实现
* `/get_group_files_by_folder` - 已实现
* `/get_group_file_url` - **未实现**，因为 NTQQ 文件下载方式已不是直接通过链接下载，请使用 `/get_file`
* `/upload_private_file` - 已实现

综上所述，关闭此 Issue。

**Comment by Wesley-Young** [comment]
题外话，其实大伙早就想抛弃 Ob11 及其扩展 API 了，毕竟一些关键的功能实现方式有变化
