### ISSUE TITLE
[Bug] NapCat 控制台输出颜色缺失

### ISSUE THREAD

**Issue by Starrain08** [NapNeko/NapCatQQ#235]
如题，现在cmd输出日志看着有些别扭，也不方便找bug和错误
![image](https://github.com/user-attachments/assets/5552c3ab-6beb-48c3-a349-79d812b495a7)
希望哪位大佬能pr修改一下

**Comment by chuxiaaaa** [comment]
不是有ps1的脚本么

**Comment by MliKiowa** [comment]
你的终端不支持着色

**Comment by Starrain08** [comment]
> 你的终端不支持着色

MCSM面板的终端支持着色，看看能不能兼容一下

**Comment by Wesley-Young** [comment]
NapCat 所用的着色方法是通用的，不知你的 MCSM 是否兼容着色？

**Comment by Starrain08** [comment]
> NapCat 所用的着色方法是通用的，不知你的 MCSM 是否兼容着色？

之前napcat在mcsm上部署就出现了颜色显示，但自从后面1.6.3更新后，颜色显示就没了

**Comment by Wesley-Young** [comment]
是否能提供 MCSM 的显示？

控制台中是直接出现了未转义的控制字符（乱码），还是说并无乱码，只是颜色不正常？

**Comment by Starrain08** [comment]
> 是否能提供 MCSM 的显示？
> 
> 控制台中是直接出现了未转义的控制字符（乱码），还是说并无乱码，只是颜色不正常？

直接出现的未转义的控制字符
![image](https://github.com/user-attachments/assets/ea0ed87d-7cb8-4517-9ed8-515bda2eb372)

**Comment by Wesley-Young** [comment]
麻烦告知系统、所用 NapCat 版本以及所用的启动脚本名称（我猜不是 PowerShell 脚本），以及 MCSM 在 _下面_ 这个地方的配置

![image](https://github.com/user-attachments/assets/fcc44bbd-af91-454a-96f1-10c3be71aff2)

初步解决方案是换成 PowerShell 启动，或试着更改 MCSM 这个页面的设置，因为部分平台的 CMD 终端的确不支持 UNIX 风格的颜色控制字符，请尝试。进一步的兼容性需要调试。

至于是平台问题还是 Node.js 问题还是 NapCat 的问题，可以试试安装 Node，直接启动（这时候应该是控制台模式），然后输入 `console.log('\033[31mRed')` 并回车，看控制台打印出的字体是否带颜色。如果仍然出现乱码，则可以排除是 NapCat 的问题。

**Comment by Starrain08** [comment]
> 麻烦告知系统、所用 NapCat 版本以及所用的启动脚本名称（我猜不是 PowerShell 脚本），以及 MCSM 在 _下面_ 这个地方的配置
> 
> ![image](https://private-user-images.githubusercontent.com/25684570/357241321-fcc44bbd-af91-454a-96f1-10c3be71aff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MjI0MzMsIm5iZiI6MTcyMzUyMjEzMywicGF0aCI6Ii8yNTY4NDU3MC8zNTcyNDEzMjEtZmNjNDRiYmQtYWY5MS00NTRhLTk2ZjEtMTBjM2JlNzFhZmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA0MDg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMTUxMzBlMzRhYTIxZmE2MmU2OGY0YmE4ODFiYTlmZTQ2ZmY0NjBmMWE4MzQ2Nzg0ZWI4NjQwZDdkNmQ3MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.baHHakmSdQeSh79zLcC0UaZgjjdqBawqx0V75V9o0l8)
> 
> 初步解决方案是换成 PowerShell 启动，或试着更改 MCSM 这个页面的设置，因为部分平台的 CMD 终端的确不支持 UNIX 风格的颜色控制字符，请尝试。进一步的兼容性需要调试。
> 
> 至于是平台问题还是 Node.js 问题还是 NapCat 的问题，可以试试安装 Node，直接启动（这时候应该是控制台模式），然后输入 `console.log('\033[31mRed')` 并回车，看控制台打印出的字体是否带颜色。如果仍然出现乱码，则可以排除是 NapCat 的问题。
![image](https://github.com/user-attachments/assets/8a3adfaa-8ea2-4307-a650-a6f5ccec8516)

![image](https://github.com/user-attachments/assets/fe619042-e026-48b6-866f-f0ed7af8a87e)

**Comment by Starrain08** [comment]
node.js的话应该没问题，因为mcsm和云崽也用到node.js,并且也控制台正确显示颜色
这是控制台截图
![image](https://github.com/user-attachments/assets/518c6331-c6db-47d4-8758-03a4b01464af)
![image](https://github.com/user-attachments/assets/56306d1f-cee9-4e49-be1f-ba63e05d0692)

**Comment by Starrain08** [comment]
> 麻烦告知系统、所用 NapCat 版本以及所用的启动脚本名称（我猜不是 PowerShell 脚本），以及 MCSM 在 _下面_ 这个地方的配置
> 
> ![image](https://private-user-images.githubusercontent.com/25684570/357241321-fcc44bbd-af91-454a-96f1-10c3be71aff2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MjI0MzMsIm5iZiI6MTcyMzUyMjEzMywicGF0aCI6Ii8yNTY4NDU3MC8zNTcyNDEzMjEtZmNjNDRiYmQtYWY5MS00NTRhLTk2ZjEtMTBjM2JlNzFhZmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDA0MDg1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMTUxMzBlMzRhYTIxZmE2MmU2OGY0YmE4ODFiYTlmZTQ2ZmY0NjBmMWE4MzQ2Nzg0ZWI4NjQwZDdkNmQ3MWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.baHHakmSdQeSh79zLcC0UaZgjjdqBawqx0V75V9o0l8)
> 
> 初步解决方案是换成 PowerShell 启动，或试着更改 MCSM 这个页面的设置，因为部分平台的 CMD 终端的确不支持 UNIX 风格的颜色控制字符，请尝试。进一步的兼容性需要调试。
> 
> 至于是平台问题还是 Node.js 问题还是 NapCat 的问题，可以试试安装 Node，直接启动（这时候应该是控制台模式），然后输入 `console.log('\033[31mRed')` 并回车，看控制台打印出的字体是否带颜色。如果仍然出现乱码，则可以排除是 NapCat 的问题。

脚本的话是1.8.6修改过的utf8bat脚本
