### ISSUE TITLE
[BUG] Shell模式一键撸猫 Linux-键脚本 文件解压失败

### ISSUE THREAD

**Issue by LJ-XD** [NapNeko/NapCatQQ#241]
### 系统版本

Ubuntu 22.04.4 LTS

### QQNT 版本

3.2.12-26702

### NapCat 版本

v2.0.1

### OneBot 客户端

Overflow 2.16.0-2cf7991-SNAPSHOT

### 发生了什么?

Shell模式一键撸猫 Linux-键脚本 执行失败

### 如何复现

在lunix 服务器上执行 Shell模式一键撸猫 Linux-键脚本

### 期望的结果?

能够正常执行成功,希望作者把脚本更新一下,脚本中提供的下载链接是无效的:
https://github.moeyy.xyz/https://github.com/NapNeko/NapCatQQ/releases/download/v2.0.1/NapCat.linux.x64.zip

### NapCat 运行日志

```shell
目标linuxQQ版本：3.2.12-26702
linuxqq 已安装，版本: 3.2.12-26702
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5948  100  5948    0     0  12369      0 --:--:-- --:--:-- --:--:-- 12365
最新NapCatQQ版本：v2.0.1
安装NapCatQQ...
NapCatQQ下载链接：https://github.moeyy.xyz/https://github.com/NapNeko/NapCatQQ/releases/download/v2.0.1/NapCat.linux.x64.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0      3      0 --:--:--  0:00:02 --:--:--     3
NapCat.linux.zip 成功下载。
正在解压 NapCat.linux.zip...
[NapCat.linux.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of NapCat.linux.zip or
        NapCat.linux.zip.zip, and cannot find NapCat.linux.zip.ZIP, period.
文件解压失败，请检查错误。
```

### OneBot 客户端运行日志

```shell
无
```

**Comment by MliKiowa** [comment]
shell脚本 同步较慢 请耐心等待

**Comment by MliKiowa** [comment]
https://github.com/NapNeko/NapCat-Installer/commit/6b7600d4f6958c84131d6da78688823696346fed

**Comment by cnxysoft** [comment]
已经处理，再试试。

**Comment by flyqie** [comment]
缓存问题，如仍有异常，请将一键命令中的 `https://cdn.jsdelivr.net/gh/` 替换为 `https://raw.githubusercontent.com/`

**Comment by LJ-XD** [comment]
已经没问题了,辛苦

**Comment by mintianzan** [comment]
新版本遇到相同问题，就不单开issue了 @MliKiowa

**Comment by sporeking** [comment]
新版本也有同样问题，我在脚本的install_napcat函数这里不使用github_proxy，直接修改为 napcat_download_url="https://github.com/NapNeko/NapCatQQ/releases/download/$napcat_version/NapCat.Shell.zip"即可解决

**Comment by sporeking** [comment]
> 新版本遇到相同问题，就不单开issue了 @MliKiowa

新版本也有同样问题，我在脚本的install_napcat函数这里不使用github_proxy，直接修改为 napcat_download_url="[https://github.com/NapNeko/NapCatQQ/releases/download/$napcat_version/NapCat.Shell.zip"即可解决](https://github.com/NapNeko/NapCatQQ/releases/download/$napcat_version/NapCat.Shell.zip%22%E5%8D%B3%E5%8F%AF%E8%A7%A3%E5%86%B3)

**Comment by Charles-LF** [comment]
域名 ghproxy.com 已喜提 GFW,是不是将域名改为https://mirror.ghproxy.com?

**Comment by MliKiowa** [comment]
> 域名 ghproxy.com 已喜提 GFW,是不是将域名改为https://mirror.ghproxy.com?

已经改了吧

**Comment by Charles-LF** [comment]
> > 域名 ghproxy.com 已喜提 GFW,是不是将域名改为https://mirror.ghproxy.com?
> 
> 已经改了吧

刚刚还在用还没有哎

**Comment by MliKiowa** [comment]
> > > 域名 ghproxy.com 已喜提 GFW,是不是将域名改为https://mirror.ghproxy.com?
> > 
> > 
> > 已经改了吧
> 
> 刚刚还在用还没有哎

curl -o napcat.sh https://cdn.jsdelivr.net/gh/NapNeko/NapCat-Installer@main/script/install.sh && sudo bash napcat.sh

**Comment by Charles-LF** [comment]
> > > > 域名 ghproxy.com 已喜提 GFW,是不是将域名改为https://mirror.ghproxy.com?
> > > 
> > > 
> > > 已经改了吧
> > 
> > 刚刚还在用还没有哎
> 
> curl -o napcat.sh https://cdn.jsdelivr.net/gh/NapNeko/NapCat-Installer@main/script/install.sh && sudo bash napcat.sh

已经自己改了文件用上了,蟹蟹

**Comment by cnxysoft** [comment]
文件分发服务缓存问题，已处理。
