### ISSUE TITLE
[BUG] 获取群精华消息列表的 API `/get_essence_msg_list` 发生变动

### ISSUE THREAD

**Issue by SherkeyXD** [NapNeko/NapCatQQ#242]
### 系统版本

Debian 12

### QQNT 版本

Linux 3.2.12-26702 

### NapCat 版本

1.8.6

### OneBot 客户端

Nonebot 2.3.2

### 发生了什么?

此 API 属于 go-cqhttp 的拓展 API，而根据 [其文档](https://docs.go-cqhttp.org/api/#%E8%8E%B7%E5%8F%96%E7%B2%BE%E5%8D%8E%E6%B6%88%E6%81%AF%E5%88%97%E8%A1%A8)，返回值应该为一个 Json 数组
但 QQ 做出了更改，貌似是添加了一个 page 参数，报错信息如下

```json
{
  "status": "failed",
  "retcode": 1400,
  "data": null,
  "message": "Key: , Message: must have required property 'pages'",
  "wording": "Key: , Message: must have required property 'pages'",
  "echo": null
}
```

### 如何复现

在 Nonebot 中调用 `bot.get_essence_msg_list()`

### 期望的结果?

正常返回群精华列表

### NapCat 运行日志

```shell
如上
```

### OneBot 客户端运行日志

```shell
None
```

**Comment by MliKiowa** [comment]
好的会加上默认参数

**Comment by MliKiowa** [comment]
最新版已修复
