### ISSUE TITLE
是否考虑使用systemd来进行进程守护？

### ISSUE THREAD

**Issue by FOXBALL-ONE** [NapNeko/NapCatQQ#251]
个人用screen来维持瞌睡猫的进程有点不是很好，启动登录后基本上就不用再管理这个screen了，不如使用systemd来进行守护，写一个service文件就好，支持开机自启和日志保存，省去了手动打开screnn的问题

**Comment by FOXBALL-ONE** [comment]
journalctl -f --output cat -u xxx.service

**Comment by FOXBALL-ONE** [comment]
journalctl -f --output cat -u xxx.service    这个能较好的动态展示对应service的日志

**Comment by FOXBALL-ONE** [comment]
[Unit]
Description=bot Service
Documentation=https://napneko.github.io/zh-CN/
Wants=basic.target
After=network.target

[Service]
Type=idle
User=root
WorkingDirectory=/opt/QQ/resources/app/app_launcher/napcat
ExecStart=xvfb-run -a qq --no-sandbox -q 
ExecReload=/bin/kill -s HUP $MAINPID
RestartSec=30
Restart=on-failure
TimeoutSec=30

[Install]
WantedBy=multi-user.target

**Comment by FOXBALL-ONE** [comment]
> [Unit] Description=bot Service Documentation=https://napneko.github.io/zh-CN/ Wants=basic.target After=network.target
> 
> [Service] Type=idle User=root WorkingDirectory=/opt/QQ/resources/app/app_launcher/napcat ExecStart=xvfb-run -a qq --no-sandbox -q ExecReload=/bin/kill -s HUP $MAINPID RestartSec=30 Restart=on-failure TimeoutSec=30
> 
> [Install] WantedBy=multi-user.target

这是我自己写的service文件

**Comment by MliKiowa** [comment]
你可以进群里问问 有人配置过
