### ISSUE TITLE
[BUG] 安装2.0.19显示 Download failed. Not Found

### ISSUE THREAD

**Issue by MoncozGC** [NapNeko/NapCatQQ#255]
### 系统版本

Windows10

### QQNT 版本

9.9.15-26702

### NapCat 版本

NapCat V2.0.19

### OneBot 客户端

xxx

### 发生了什么?

根据NapCatQQ安装文档，根据命令行启动 Windows X64 一键安装教程。

```
curl -o install.ps1 https://cdn.jsdmirror.com/gh/NapNeko/NapCat-Installer@main/script/install.ps1
powershell -ExecutionPolicy ByPass -File ./install.ps1 -verb runas
```

这应该是两段命令，我在cmd中执行第二条命令的时候显示：Download failed. Not Found

![image](https://github.com/user-attachments/assets/1ee335e7-718a-429d-b8ef-007a2e799295)

### 如何复现

1. 执行： curl -o install.ps1 https://cdn.jsdmirror.com/gh/NapNeko/NapCat-Installer@main/script/install.ps1
2. 执行：powershell -ExecutionPolicy ByPass -File ./install.ps1 -verb runas

显示错误信息：
Download failed. Not Found

### 期望的结果?

根据官方文档，应该正常安装完成。

### NapCat 运行日志

```shell
无
```

### OneBot 客户端运行日志

```shell
无
```

**Comment by MliKiowa** [comment]
现在试试呢

**Comment by MliKiowa** [comment]
多次刷新文档 尝试最新脚本即可
