### ISSUE TITLE
[BUG] options请求HTTP服务产生跨域问题

### ISSUE THREAD

**Issue by starcollect** [NapNeko/NapCatQQ#257]
### 系统版本

Windows 10 Pro Workstation 22H2

### QQNT 版本

9.9.15-26909

### NapCat 版本

2.0.21

### OneBot 客户端

无

### 发生了什么?

options请求 产生跨域问题`Access to fetch at 'http://localhost:3000/' from origin 'null' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.`

### 如何复现

Fetch跨域访问HTTP服务

### 期望的结果?

希望可以正常访问获得数据

不知道这个链接是否有所帮助：https://blog.csdn.net/cc_King/article/details/110944681

**Comment by MliKiowa** [comment]
稍后版本将进行更新

**Comment by MliKiowa** [comment]
尝试使用 https://github.com/NapNeko/NapCatQQ/actions/runs/10398802993 替换测试

**Comment by starcollect** [comment]
> 尝试使用 https://github.com/NapNeko/NapCatQQ/actions/runs/10398802993 替换测试

替换后恢复正常，相关请求未再出现相关问题，感谢修正。
