### ISSUE TITLE
请求增加拉取已过滤的群请求或好友请求

### ISSUE THREAD

**Issue by rongrong1000** [NapNeko/NapCatQQ#258]
某些人被tx拉黑了 bot无法收到该人的请求
(玩机器人的大号, 不少都被tx拉黑了吧, 玩机器人玩的)

**Comment by Wesley-Young** [comment]
V1 曾经试图增加过类似 API，但支持不完整。

另外，我在测试 V1 的某个版本时候，能收到“已过滤”的请求，但曾经有人反馈这个请求有“一定概率”（略在 5%？无法复现）收不到。是否确认收不到一些已过滤的请求？

**Comment by MliKiowa** [comment]
请问能否进群测测呢

**Comment by MliKiowa** [comment]
下个版本支持

**Comment by rongrong1000** [comment]
> 下个版本支持

好耶

**Comment by Wesley-Young** [comment]
`GetGroupIgnoredNotifies`，目前只能拉取而不能批准或拒绝。

另外，经测试，最新版 NC 是**能**收到已过滤的申请且**正常上报**的，因此，增加该接口意义不大。
