### ISSUE TITLE
[BUG] 表情回应的消息ID不一致

### ISSUE THREAD

**Issue by eSakuras** [NapNeko/NapCatQQ#260]
### 系统版本

Windows server 2012 R2

### QQNT 版本

9.9.12.25765

### NapCat 版本

1.8.6

### OneBot 客户端

-

### 发生了什么?

表情回应事件的消息ID错误

### 如何复现

多次测试发现：
1. 如果机器人被 表情回应的消息是最新消息。发现所有回应消息ID都是不一样的（也没有和发送返回msgid一样的）。
2. 如果机器人发送消息后，有其他人发送消息。此时表情回应的消息ID和发送的消息一致，正常。

就是机器人是最新消息，如果被回应消息，那么消息id都是随机的，直到不是最新消息才会被固定。而固定的这个不是发送后返回的msgid

### 期望的结果?

回应表情的消息ID应该和机器人发送后返回的消息ID一样

**Comment by MliKiowa** [comment]
这个bug 早有发现 但是最近事情有点多

**Comment by MliKiowa** [comment]
2.0.26已修复

**Comment by MliKiowa** [comment]
再次reopen下 回复Id 仍然有问题
