### ISSUE TITLE
[BUG] napcat v2.0.12之后get_group_member_info接口响应时间秒级别

### ISSUE THREAD

**Issue by uosbox** [NapNeko/NapCatQQ#272]
### 系统版本

Ubuntu22.04

### QQNT 版本

26909

### NapCat 版本

V2.0.31

### OneBot 客户端

无

### 发生了什么?

![image](https://github.com/user-attachments/assets/302b687c-e4b3-4d6e-b562-7803a81e699f)
Napcat v2.0.12之后   http api接口 ：get_group_member_info【获取成员信息】  响应时间太慢，长达2-6秒。

### 如何复现

get_group_member_info 接口

### 期望的结果?

get_group_member_info 接口响应时间优化到毫秒级别
或者新开一个接口 毫秒级别能判断QQ号是否是群友

### NapCat 运行日志

```shell
无
```

**Comment by cnxysoft** [comment]
此问题目前正在跟进，下一版修复。

**Comment by cnxysoft** [comment]
> > 此问题目前正在跟进，下一版修复。
> 
> ![image](https://private-user-images.githubusercontent.com/18119846/358961361-5b449dfb-1fc8-451f-bad7-43743937a692.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQwMzU2OTUsIm5iZiI6MTcyNDAzNTM5NSwicGF0aCI6Ii8xODExOTg0Ni8zNTg5NjEzNjEtNWI0NDlkZmItMWZjOC00NTFmLWJhZDctNDM3NDM5MzdhNjkyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE5VDAyNDMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0YmU1YTRiZjQyMzQwODEzNzBhNzIyNjNiNjE0MTY2NTk1MTgxMTYzMzg5NTk1NTY1NWE0Mzk5ZTM5MzdmNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.e-h-l9GfW49NZL4dVxat7QelHbTYTTP9nJeb5MwMwzo) 问题在v2.0.32得到解决！！感谢！

你可以试试no_cache，说不定有惊喜（笑
