### ISSUE TITLE
[Feature]对sql进行支持 可自行关闭

### ISSUE THREAD

**Issue by yichen11818** [NapNeko/NapCatQQ#273]
如leveldb或sqlite3 后续是否考虑对其进行支持
  leveldb:
    # 是否启用内置leveldb数据库
    # 启用将会增加10-20MB的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: false
  sqlite3:
    # 是否启用内置sqlite3数据库
    # 启用将会增加一定的内存占用和一定的磁盘空间
    # 关闭将无法使用 撤回 回复 get_msg 等上下文相关功能
    enable: false
    cachettl: 3600000000000 # 1h

**Comment by MliKiowa** [comment]
请问你是哪个版本遇到 撤回/回复 问题 
并且怎么复现的

**Comment by MliKiowa** [comment]
长时间未跟进close了哦 需要的话可以进群询问与开新的issue 附带你的具体需求 而非代码层面要求
