### ISSUE TITLE
[BUG] 换行消息napcat，http事件无法正常上报，

### ISSUE THREAD

**Issue by uosbox** [NapNeko/NapCatQQ#274]
### 系统版本

Ubuntu22.04

### QQNT 版本

26909

### NapCat 版本

V2.0.31

### OneBot 客户端

无

### 发生了什么?

一次性发多行消息（换行消息） ，http事件上报不了。
发单行消息没问题，可以正常收到上报消息。

![)I7V8SPX% 0BF5W9A~CD9V](https://github.com/user-attachments/assets/45cf6c97-e42d-4f7a-9d2c-de014f8688c2)
545402644 群文件有我录制的测试视频  更直观

### 如何复现

QQ上发送 多行消息 
例如：
张三
李四
王麻子

### 期望的结果?

多行消息能正常上报

### NapCat 运行日志

```shell
无
```

**Comment by MliKiowa** [comment]
老QQ专属问题貌似

**Comment by cnxysoft** [comment]
这边经过多次复现，仍未能复现该现象。
换行符以及emoji都能正常上报，没有问题。

**Comment by cnxysoft** [comment]
我用的也是http事件上报，不同终端显示可能略有差异，在wt中表现为换行显示。
![image](https://github.com/user-attachments/assets/fc2abe77-7cec-4dfd-aa83-0bb0f60657b7)
![image](https://github.com/user-attachments/assets/2b1e0d87-43c7-4acc-9866-c841c452f9d6)
![image](https://github.com/user-attachments/assets/f8a3c757-51ec-4611-b678-234e47da7129)

**Comment by cnxysoft** [comment]
我在Deepin R23(Debian)下搭建了一个临时测试环境，NC以及HttpServ都在同一台机器上，上报表现均正常。
![image](https://github.com/user-attachments/assets/0b9e13db-a97f-4dc3-8e6c-6893af87e0ab)

**Comment by cnxysoft** [comment]
OK，届时欢迎分享经验。
