### ISSUE TITLE
[BUG] 收不到群成员名片更新事件

### ISSUE THREAD

**Issue by rongrong1000** [NapNeko/NapCatQQ#277]
### 系统版本

win server 2012

### QQNT 版本

9.9.15-26909 (64位)

### NapCat 版本

0.2.31

### OneBot 客户端

无

### 发生了什么?

收不到群成员名片更新事件

### 如何复现

改名片后. 发言

### 期望的结果?

收到群成员名片更新事件

**Comment by cnxysoft** [comment]
已复现，请等待修复。

**Comment by cnxysoft** [comment]
此问题将在下一版本修复。
