### ISSUE TITLE
[BUG]新QQ号加群 http事件上报 报错

### ISSUE THREAD

**Issue by uosbox** [NapNeko/NapCatQQ#280]
### 系统版本

Ubuntu22.04

### QQNT 版本

26909

### NapCat 版本

V2.0.33

### OneBot 客户端

无

### 发生了什么?

新注册了一个QQ号测试加群 事件通知
没想到申请加群 napcat终端日志报错
`获取加群人QQ号失败 Uid: u_n5mIBoVoSq9d2R262DN-xw Error: Timeout: NTEvent EventName:NodeIKernelProfileService/fetchUserDetailInfo ListenerName:NodeIKernelProfileListener/onUserDetailInfoChanged EventRet:
{
    "result": 0,
    "errMsg": "",
    "source": 0,
    "detail": {}
}

    at Timeout.databack [as _onTimeout] (file:///opt/QQ/resources/app/app_launcher/napcat/napcat.mjs:1119:18)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
`
![image](https://github.com/user-attachments/assets/b14ca9a8-ee39-4f42-88ad-4f6f71e4e037)
以前就在群里的群友 退群后重新加群就不报这个错

### 如何复现

随便注册一个QQ号加群

### 期望的结果?

不在报错

### NapCat 运行日志

```shell
无
```

**Comment by MliKiowa** [comment]
尝试更新新版本试试

**Comment by cnxysoft** [comment]
正在跟进，能否提供一下QQ号码？

**Comment by cnxysoft** [comment]
此问题将于下一版本修复。

**Comment by MliKiowa** [comment]
尝试新的版本试试

**Comment by MliKiowa** [comment]
如果仍然有问题请开新的issue哦
