### ISSUE TITLE
如何撤回群消息

### ISSUE THREAD

**Issue by Gaimoydev** [NapNeko/NapCatQQ#281]
我按照api文档去发送请求却没有撤回成功
可能只能撤回自己发送的消息

机器人账号是群管理
{
   "action": "delete_msg",
   "params": {
   "message_id": msg_id
    }
}

**Comment by cnxysoft** [comment]
不知道你用的什么版本和日志等详情（提交issue是有固定格式的哦）
NC2.0.33(搭配QQ9.9.15-26909)，测试没有复现，建议更新你的版本并检查BOT权限后再试。
如仍有问题请按照issue提交格式并给予足够信息。

**Comment by MliKiowa** [comment]
如果有问题按照规范提交测试内容 和 图例 版本等等 开新的issue
