### ISSUE TITLE
[BUG] 加QQ群事件消息延迟 很长时间！nc终端很久之后才报错

### ISSUE THREAD

**Issue by uosbox** [NapNeko/NapCatQQ#282]
### 系统版本

Ubuntu22.04

### QQNT 版本

26909

### NapCat 版本

V2.0.34

### OneBot 客户端

无

### 发生了什么?

napcat 加群事件 上报异常 ，其他通知消息一切正常 ，唯独加群 终端也很长时间才报
`[OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError:
    at node:internal/deps/undici/undici:12502:13
`
排除http服务器端问题！
![image](https://github.com/user-attachments/assets/2d05cdbf-9994-43a2-8d87-538544a76a4b)
报错之后 上报的事件消息正常传达
![image](https://github.com/user-attachments/assets/c1e9bc91-b4b8-4213-b00e-2c862c8246ef)
从上图可以看出 
`"comment": "问题：从何得知群，进群目的n答案：我要刷rk3399",
`
comment的值里面有换行符！但”\“不见了！
估计在传消息处理中被忽略了
  

### 如何复现

http事件上报 开启
     加群就知道了

### 期望的结果?

加群正常上报事件，不报错

**Comment by cnxysoft** [comment]
已知晓，请问普通消息的特殊/转义字符可以正常上报吗？
