### ISSUE TITLE
[BUG] 表情回应事件消息ID错误

### ISSUE THREAD

**Issue by eSakuras** [NapNeko/NapCatQQ#293]
### 系统版本

Windows server 2012 R2

### QQNT 版本

9.9.15.27206

### NapCat 版本

2.1.0

### OneBot 客户端

-

### 发生了什么?

表情回应事件消息ID错误，已多次复现

### 如何复现

1. 机器人发送消息后贴两个表情
2. 等待6分钟及以上（不确定是否可以再低一点）后再次贴表情

期间无其他消息和事件（不确定是不是必要条件）

### 期望的结果?

消息ID应一致

**Comment by MliKiowa** [comment]
5分钟 你说的没错

**Comment by MliKiowa** [comment]
> > 5分钟 你说的没错
> 
> 还有个小问题，在ws中/api 也会推送事件消息，在之前版本好像是只推送api消息（OneBot似乎也是这么写的）

新版偷懒了

**Comment by MliKiowa** [comment]
正在解决中

**Comment by MliKiowa** [comment]
尝试下新版本呢

**Comment by MliKiowa** [comment]
如果仍然有问题开issue
