### ISSUE TITLE
[BUG] NapCat 2.x版本event.message存在CQ字段，导致Nonebot1.x无法正常运行

### ISSUE THREAD

**Issue by zzpong** [NapNeko/NapCatQQ#294]
### 系统版本

Windows server 2012 R2

### QQNT 版本

27187

### NapCat 版本

2.1.0

### OneBot 客户端

无，直接使用Nonebot1.x对接

### 发生了什么?

Nonebot需要调用event.message字段以判断指令：
![图片](https://github.com/user-attachments/assets/35a58e83-8391-4d93-bcb4-71e0d85000a0)
![图片](https://github.com/user-attachments/assets/48749017-28f4-41cb-8c61-ec450db31608)

NapCat1.x版本所上报event.message字段不包含CQ码，一切正常：
![图片](https://github.com/user-attachments/assets/c3e33573-1102-422d-b58e-19793087f2de)
但NapCat2.x版本所上报event.message字段包含CQ码，导致所有包含at功能的指令完全无法执行：
![图片](https://github.com/user-attachments/assets/58262f2f-28cf-4775-b4b2-896b3e3f3661)

望修复。

### 如何复现

切换不同Napcat版本即可复现。

### 期望的结果?

NapCat2.x版本所上报event.message字段也应与1.x一样移除CQ码，以提高兼容性；
并且这点并不影响Onebot或Nonebot2的使用。

**Comment by MliKiowa** [comment]
尝试 https://github.com/NapNeko/NapCatQQ/actions/runs/10525979947

**Comment by zzpong** [comment]
> 尝试 https://github.com/NapNeko/NapCatQQ/actions/runs/10525979947

感谢您如此快速的修复，我这继续用1.x版本NapNeko了。只要这个上报信息event.message段不包含CQ码肯定没问题，这bug已在Nonebot那边修改测试过了。
