### ISSUE TITLE
无法启动Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by XiaoFeng-QWQ** [NapNeko/NapCatQQ#295]
## 我在使用Manyana的时候出现以下错误
我尝试在Manyana QQ群向管理员提问但是未能解决我的问题，我只能在这里提个issues了（脑）

## 日志：
[preload] succeeded. /opt/QQ/resources/app/major.node
[preload] succeeded. /opt/QQ/resources/app/major.node
[193459:0823/030017.051378:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
[193510:0823/030018.091525:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
NapCat Shell App Loading...
Illegal instruction (core dumped)

## 系统信息：
Linux ubuntu22 5.15.0-119-generic 129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
---
root@ubuntu22:~# cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 20
model           : 2
model name      : AMD C-70 APU with Radeon(tm) HD Graphics
stepping        : 0
microcode       : 0x5000119
cpu MHz         : 800.044
cache size      : 512 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni monitor ssse3 cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch ibs skinit wdt cpb hw_pstate vmmcall arat npt lbrv svm_lock nrip_save pausefilter
bugs            : fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 1999.91
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate cpb
processor       : 1
vendor_id       : AuthenticAMD
cpu family      : 20
model           : 2
model name      : AMD C-70 APU with Radeon(tm) HD Graphics
stepping        : 0
microcode       : 0x5000119
cpu MHz         : 800.608
cache size      : 512 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni monitor ssse3 cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch ibs skinit wdt cpb hw_pstate vmmcall arat npt lbrv svm_lock nrip_save pausefilter
bugs            : fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 1999.91
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate cpb

**Comment by MliKiowa** [comment]
使用docker

**Comment by XiaoFeng-QWQ** [comment]
> 使用docker

我也尝试过docker，也报同样错

**Comment by MliKiowa** [comment]
提高到root权限

**Comment by XiaoFeng-QWQ** [comment]
> 提高到root权限

没用啊😭

**Comment by MliKiowa** [comment]
提供你的QQ版本和NC版本

**Comment by XiaoFeng-QWQ** [comment]
> 提供你的QQ版本和NC版本
我用的是这个
[Manyana_deploy](https://github.com/lux-QAQ/Manyana_deploy)
他这里面使用了NapCat，可是我咋知道版本啊

**Comment by XiaoFeng-QWQ** [comment]
😭

**Comment by XiaoFeng-QWQ** [comment]
> > 提供你的QQ版本和NC版本
> > 我用的是这个
> > [Manyana_deploy](https://github.com/lux-QAQ/Manyana_deploy)
> > 他这里面使用了NapCat，可是我咋知道版本啊

呃……我已经向Manyana整合包作者询问了，当我没说（）

**Comment by xiaozhou233** [comment]
我遇到了同样的问题，原因是CPU太老不支持某些指令集，解决方法 ([参考](https://www.cnblogs.com/liuzengshuai/p/17324473.html)) :
```shell
#安装libvips42
sudo apt install libvips42
#备份
sudo cp /opt/QQ/resources/app/sharp-lib/libvips-cpp.so.42 /opt/QQ/resources/app/sharp-lib/libvips-cpp.so.42.bk
#替换原有的库
sudo cp /usr/lib/x86_64-linux-gnu/libvips-cpp.so.42.<实际版本> /opt/QQ/resources/app/sharp-lib/libvips-cpp.so.42
```

**Comment by XiaoFeng-QWQ** [comment]
> 我遇到了同样的问题，原因是CPU太老不支持某些指令集，解决方法 ([参考](https://www.cnblogs.com/liuzengshuai/p/17324473.html)) :
> 
> ```shell
> #安装libvips42
> sudo apt install libvips42
> #备份
> sudo cp /opt/QQ/resources/app/sharp-lib/libvips-cpp.so.42 /opt/QQ/resources/app/sharp-lib/libvips-cpp.so.42.bk
> #替换原有的库
> sudo cp /usr/lib/x86_64-linux-gnu/libvips-cpp.so.42.<实际版本> /opt/QQ/resources/app/sharp-lib/libvips-cpp.so.42
> ```

我去，感谢🙏🏻
