### ISSUE TITLE
[BUG] [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed

### ISSUE THREAD

**Issue by FadeJay** [NapNeko/NapCatQQ#296]
### 系统版本

CentOS8

### QQNT 版本

LinuxX64 RPM 27254

### NapCat 版本

V2.2.4

### OneBot 客户端

无

### 发生了什么?

通过http事件上报接口——>目标服务器无法正常接收到”napcat“post过来的数据，通过设置的HTTP上报事件地址也无法访问
![1724405082211](https://github.com/user-attachments/assets/705111b2-9a8e-4602-aa61-fd3d8f85599c)
![1724405236428](https://github.com/user-attachments/assets/82186fdb-bb1c-4604-a9b8-8ff8c4cf2418)

### 如何复现

HTTP上报事件地址设置为http://127.0.0.1:20010

### 期望的结果?

不再报错，能够通过HTTP上报事件地址获取到上报事件

### NapCat 运行日志

```shell
2024-08-23 17:22:35 [INFO] 纸灵灵の录播姬(2326637358) | 接收 <- 群聊 (群 902259381 的 1079527792) 测试 
2024-08-23 17:22:35 [ERROR] 纸灵灵の录播姬(2326637358) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
2024-08-23 17:22:35 [ERROR] 纸灵灵の录播姬(2326637358) | [OneBot] [Http Client] 新消息事件HTTP上报失败 TypeError: fetch failed
    at node:internal/deps/undici/undici:12502:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by MliKiowa** [comment]
docker?

**Comment by MliKiowa** [comment]
检查服务端 问题 nc是经过大量测试的

**Comment by FadeJay** [comment]
> 检查服务端 问题 nc是经过大量测试的

麻烦问下大佬怎么去检查呢？HTTP服务我测试是能用的，然后我试过把HTTP服务的端口给HTTP事件上报的端口，一样的问题，应该不是端口的问题

**Comment by Wesley-Young** [comment]
服务端指的是监听 POST 上报的服务端，而非 NapCat 本身，请检查你用于接收 POST 的服务端是否正常工作。

如有可能，也可尝试切换到 WS / 反向 WS 连接模式。

**Comment by FadeJay** [comment]
> 服务端指的是监听 POST 上报的服务端，而非 NapCat 本身，请检查你用于接收 POST 的服务端是否正常工作。
> 
> 如有可能，也可尝试切换到 WS / 反向 WS 连接模式。毕竟，这两个模式所经受的生产环境测试更多。

我好像理解错NapCatQQ的工作方式了，意思是除了在服务器上启动NatCatQQ，想要用HTTP事件上报的话还需要像这篇博客里https://mumuzi7179.github.io/docs/Blog/QQBot/%E4%BD%BF%E7%94%A8NapCatQQ%E6%90%AD%E5%BB%BAQQBot类似在服务器上做一个flask的服务器端去监听HTTP事件上报设置的端口吗？

**Comment by Wesley-Young** [comment]
是的，否则应该如何获取上报的事件呢？

如果希望在同一个连接中同时调用 Action 和接收事件上报，请考虑使用 WS / 反向 WS。

可以关闭此 issue 了。如有其他问题，欢迎 reopen 或进群反馈。
