### ISSUE TITLE
[Feature] 未来能支持 `get_csrf_token` 吗？

### ISSUE THREAD

**Issue by whitebloak** [NapNeko/NapCatQQ#297]
看到napcat的文档内标注的API支持情况

发现目前并没有支持 `get_csrf_token` 

未来会有计划支持吗？

---

**Comment by MliKiowa** [comment]
这个是干嘛的

**Comment by whitebloak** [comment]
在使用TRSS云崽通过‘反向WebSocket（WS）’连接到’napcat‘时，我遇到了频繁的连接断开与重连问题。报错是‘get_csrf_token’，而napcat日志展示意外断开，寻找到trss云崽的github仓库的Issue，有人提问过以下图像的情况，即‘get_csrf_token’的错误，trss云崽的开发者之一回复是建议联系napcat的维护者以获取帮助，而我查阅napcat开发文档得知，’napcat‘ 没支持 ‘get_csrf_token’，因此特来提交issue询问。

图像情况如下：
napcat端：
![_R9{X4%FD7$PO(@L3DJLA`N](https://github.com/user-attachments/assets/1ead6380-3809-447c-b872-d8b71734f7d6)

trss云崽端：
![N_FTC)43JXS2 AJQNNX(~B](https://github.com/user-attachments/assets/c939e7a8-0fcf-4280-93b8-1a72b2d7b182)

**Comment by MliKiowa** [comment]
提高版本

**Comment by MliKiowa** [comment]
新版好像已经兼容了

**Comment by whitebloak** [comment]
OK，下载了新版，根本正常运行了。

**Comment by whitebloak** [comment]
感激不尽。
