### ISSUE TITLE
[BUG] 在获取群成员列表时，部分键值出现问题

### ISSUE THREAD

**Issue by wling-art** [NapNeko/NapCatQQ#3]
### 系统版本

Debian 12 bookworm

### QQNT 版本

Docker

### NapCat 版本

Docker

### OneBot 客户端

Nonebot2 / 2.2.1

### 发生了什么?

在下面信息中last_sent_time为0，还有其它多个键值未正常显示，join_time等（已给测试群字符打码）
```
{
    "group_id": 9**01**20,
    "user_id": 1990248284,
    "nickname": "Mr.ling",
    "card": "",
    "sex": "unknown",
    "age": 0,
    "area": "",
    "level": 0,
    "qq_level": 0,
    "join_time": 0,
    "last_sent_time": 0,
    "title_expire_time": 0,
    "unfriendly": false,
    "card_changeable": true,
    "is_robot": false,
    "shut_up_timestamp": 0,
    "role": "member",
    "title": ""
  }
```

### 如何复现

https://github.com/CrashVibe/U1bot/blob/main/src/plugins/waifu/__init__.py#L176-L181

### 期望的结果?

构建出完整的信息，如go-cq返回的
```
  {
    "age": 0,
    "area": "",
    "card": "",
    "card_changeable": false,
    "group_id": 9**01**20,
    "join_time": 1675189660,
    "last_sent_time": 1713321801,
    "level": "1",
    "nickname": "Mr.ling",
    "role": "member",
    "sex": "male",
    "shut_up_timestamp": 0,
    "title": "",
    "title_expire_time": 0,
    "unfriendly": false,
    "user_id": 1990248284
  }
```

### NapCat 运行日志

```shell
无相关api日志输出
```

**Comment by MliKiowa** [comment]
部分信息拿不到，NTQQ本身未给出，部分数据如果以后能拿到会补齐

**Comment by wling-art** [comment]
tks，我了解了，待补全

**Comment by MliKiowa** [comment]
字段已经能拿到 下个版本支持

预计新增字段
![4de779f4fd02978fb0eec0fe7a4df042](https://github.com/NapNeko/NapCatQQ/assets/61873808/61bb210e-16bb-4f25-934d-fe624e9ae28b)

https://github.com/NapNeko/NapCatQQ/commit/94e1a6f0ba5a3a8283fd7122e4f7c1903b597c37

**Comment by MliKiowa** [comment]
已支持 下个版本

**Comment by MliKiowa** [comment]
可以在这里找到测试版本 https://github.com/NapNeko/NapCatQQ/actions/runs/8875930216

**Comment by po-lan** [comment]
我在使用Docker 版本的时候再次出现了该问题
![image](https://github.com/NapNeko/NapCatQQ/assets/42771836/8f49deb7-6246-4f5c-891c-8ab620d8563c)
我的Bot是真寻、使用娶群友插件时候发现无法成功使用遂发现该问题
服务器架构是Arm

**Comment by MliKiowa** [comment]
> 我在使用Docker 版本的时候再次出现了该问题 ![image](https://private-user-images.githubusercontent.com/42771836/332175730-8f49deb7-6246-4f5c-891c-8ab620d8563c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNTQ0NjgsIm5iZiI6MTcxNjI1NDE2OCwicGF0aCI6Ii80Mjc3MTgzNi8zMzIxNzU3MzAtOGY0OWRlYjctNjI0Ni00ZjVjLTg5MWMtOGFiNjIwZDg1NjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAxMTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMDYyMDkyODM1ZjA1ZDI3NjliMWE5MDExZjQ3OTQwZTY5YjY1YWM3NWM3YWNkMzdiNTUzMDY4MmQxOTE5MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jMIzKlRlqzgFzCNy8JBFa0plkQzN93CTVGgCJh1yWzI) 我的Bot是真寻、使用娶群友插件时候发现无法成功使用遂发现该问题 服务器架构是Arm

加入时间与退群时间 需要管理员权限

**Comment by po-lan** [comment]
> > 我在使用Docker 版本的时候再次出现了该问题 ![image](https://private-user-images.githubusercontent.com/42771836/332175730-8f49deb7-6246-4f5c-891c-8ab620d8563c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyNTQ0NjgsIm5iZiI6MTcxNjI1NDE2OCwicGF0aCI6Ii80Mjc3MTgzNi8zMzIxNzU3MzAtOGY0OWRlYjctNjI0Ni00ZjVjLTg5MWMtOGFiNjIwZDg1NjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIxVDAxMTYwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjMDYyMDkyODM1ZjA1ZDI3NjliMWE5MDExZjQ3OTQwZTY5YjY1YWM3NWM3YWNkMzdiNTUzMDY4MmQxOTE5MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jMIzKlRlqzgFzCNy8JBFa0plkQzN93CTVGgCJh1yWzI) 我的Bot是真寻、使用娶群友插件时候发现无法成功使用遂发现该问题 服务器架构是Arm
> 
> 加入时间与发言时间 需要管理员权限

感谢，那应该是langrange做了记录，从而可以获取到
