### ISSUE TITLE
[BUG] 系统强制重启后登录需要重新认证

### ISSUE THREAD

**Issue by Huasushis** [NapNeko/NapCatQQ#30]
### 系统版本

Ubuntu Server 18.04.1 LTS 64bit

### QQNT 版本

3.2.7-240428

### NapCat 版本

1.3.5

### OneBot 客户端

Python 3.7

### 发生了什么?

在没有正常结束napcat的情况下强制重启（就是内存不足系统卡住的情况下），重新登录账号需要重新认证。

没有验证过正常结束的情况下重启是否需要再次认证。

### 如何复现

- 在 tmux 中运行 napcat 并登录账号
- 直接重启
- 再次运行发现需要重新手机扫码，手机上查看登陆设备发现与之前不是同一个。

### 期望的结果?

无需认证，直接登录。

### NapCat 运行日志

```shell
无异常
```

### OneBot 客户端运行日志

```shell
没有
```

**Comment by MliKiowa** [comment]
能复现吗 尝试对比下前后Mac地址

**Comment by Huasushis** [comment]
> 能复现吗 尝试对比下前后Mac地址

是的，重启之后mac地址就变了

**Comment by MliKiowa** [comment]
> > 能复现吗 尝试对比下前后Mac地址
> 
> 是的，重启之后mac地址就变了

需要固定Mac地址哦

**Comment by Huasushis** [comment]
> > > 能复现吗 尝试对比下前后Mac地址
> > 
> > 
> > 是的，重启之后mac地址就变了
> 
> 需要固定Mac地址哦

固定以后就没问题了

**Comment by Do1e** [comment]
> 能复现吗 尝试对比下前后Mac地址

这个MAC地址是网卡的MAC地址吗？我也能复现出这个问题

**Comment by MliKiowa** [comment]
对的

**Comment by Do1e** [comment]
> 对的

不过我发现我的MAC地址没有变，重启napcat服务不同重新登录，但是重启主机需要，而且稳定复现

**Comment by Do1e** [comment]
> 对的

不过我发现我的MAC地址没有变，重启napcat服务不用重新登录，但是重启主机需要，而且稳定复现

**Comment by XokoukioX** [comment]
> Member
也出现了如下问题：服务器系统重启后会要求重新扫码登录 设备也不是同一个
