### ISSUE TITLE
请问是否支持企点？

### ISSUE THREAD

**Issue by leoguan88** [NapNeko/NapCatQQ#305]
### 系统版本

win server 2016

### QQNT 版本

9.9.7

### NapCat 版本

1.0.0

### OneBot 客户端

2.16

### 发生了什么?

请问是否支持企点？

### 如何复现

请问是否支持企点？

### 期望的结果?

请问是否支持企点？

### NapCat 运行日志

```shell
请问是否支持企点？
```

### OneBot 客户端运行日志

```shell
请问是否支持企点？
```

**Comment by MliKiowa** [comment]
不支持哦
