### ISSUE TITLE
[BUG] overflow无法获取onebot版本以及断连

### ISSUE THREAD

**Issue by Book-fall2wish** [NapNeko/NapCatQQ#307]
Linux armbian 6.6.35-ophub #1 SMP Fri Jun 21 20:58:43 EDT 2024 aarch64 aarch64 aarch64 GNU/Linux

QQNT版本:
3.2.12-27254

Napcatb版本：
v2.2.12

OneBot 客户端：
Overflow v2.16.0-795845b-SNAPSHOT以及2.16.0-d59fa60-SNAPSHOT都有这个问题

napcat和客户端配置：
napcat:
{
  "http": {
    "enable": true,
    "host": "",
    "port": 3000,
    "secret": "",
    "enableHeart": false,
    "enablePost": false,
    "postUrls": []
  },
  "ws": {
    "enable": true,
    "host": "",
    "port": 3001
  },
  "reverseWs": {
    "enable": false,
    "urls": []
  },
  "GroupLocalTime": {
    "Record": false,
    "RecordList": []
  },
  "debug": false,
  "heartInterval": 30000,
  "messagePostFormat": "array",
  "enableLocalFile2Url": true,
  "musicSignUrl": "",
  "reportSelfMessage": false,
  "token": "*token"
}

overflow:
{
    "ws_host": "ws://127.0.0.1:3001",
    "reversed_ws_port": -1,
    "token": "*token",
    "retry_times": 5,
    "retry_wait_mills": 5000,
    "retry_rest_mills": 60000
}

napcat运行日志：
[2024-08-26_17-46-54.767.log](https://github.com/user-attachments/files/16747636/2024-08-26_17-46-54.767.log)

overflow onebot日志：
[2024-08-26.log](https://github.com/user-attachments/files/16747640/2024-08-26.log)

**Comment by MliKiowa** [comment]
fix [#c0f5d3bd2eea82de78d883c515bb27124018cbfe](https://github.com/NapNeko/NapCatQQ/commit/c0f5d3bd2eea82de78d883c515bb27124018cbfe)
