### ISSUE TITLE
[BUG] 通过get_image接口获取图片信息时报错file not found

### ISSUE THREAD

**Issue by azmiao** [NapNeko/NapCatQQ#313]
### 系统版本

winsvr 2019

### QQNT 版本

最新

### NapCat 版本

2.2.12

### OneBot 客户端

最新

### 发生了什么?

通过/get_image接口获取图片时，报错：Error: file not found

或许和隔壁类似？[issue 287](https://github.com/NapNeko/NapCatQQ/issues/287)

原始issue来自[XQA issue 15](https://github.com/azmiao/XQA/issues/15)

另由于本人实际仍使用go_cqhttp，未使用napcat，对相关配置什么的不是很了解，因此本人仅为代提交issue，实际问题发起者：[@ragnarok6324]

### 如何复现

```python
async def doing_img(bot, img: str, is_ans: bool = False, save: bool = False) -> str:
    img_path = os.path.join(FILE_PATH, 'img/')
    if save:
        logger.info('开始调用get_image接口获取图片信息')
        img_url = await bot.get_image(file=img)
        logger.info('图片信息接口返回：' + str(img_url))
        file = os.path.join(img_path, img)
        if not os.path.isfile(img_path + img):
            urllib.request.urlretrieve(url=img_url['url'], filename=file)
            logger.critical(f'XQA: 已下载图片{img}')
    if is_ans:  # 保证保存图片的完整性，方便迁移和后续做操作
        return 'file:///' + os.path.abspath(img_path + img)
    return img
```

### 期望的结果?

正常获取图片信息

### NapCat 运行日志

```shell
2024-08-25 23:35:11 [ [91mERROR [39m] 芬里尔(438980368) | 发生错误 Error: file not found
at GetImage._handle (file:///C:/Users/Administrator/Desktop/%E8%BF%99%E4%B8%AA%E6%98%AF%E4%BD%A0%E7%9A%84%E6%9C%BA%E
5%99%A8%E4%BA%BA%E7%99%BB%E9%99%86/NapCat-new/NapCat.win32.x64/napcat.mjs:24445:11)
at async GetImage.websocketHandle (file:///C:/Users/Administrator/Desktop/%E8%BF%99%E4%B8%AA%E6%98%AF%E4%BD%A0%E7%9A
%84%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%99%BB%E9%99%86/NapCat-new/NapCat.win32.x64/napcat.mjs:21764:23)
at async ReverseWebsocket.onmessage (file:///C:/Users/Administrator/Desktop/%E8%BF%99%E4%B8%AA%E6%98%AF%E4%BD%A0%E7%
9A%84%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%99%BB%E9%99%86/NapCat-new/NapCat.win32.x64/napcat.mjs:27137:28)
at async WebSocket. (file:///C:/Users/Administrator/Desktop/%E8%BF%99%E4%B8%AA%E6%98%AF%E4%BD%A0%E7%9A%84
%E6%9C%BA%E5%99%A8%E4%BA%BA%E7%99%BB%E9%99%86/NapCat-new/NapCat.win32.x64/napcat.mjs:27177:7)
2024-08-25 23:35:11 [ [91mERROR [39m] 芬里尔(438980368) | 发生错误 Error: ENOENT: no such file or directory, open 'C:\Users\Adm
inistrator\Desktop\Resources\img\xqa\img{2A775A7B-C55E-ABDA-3BD8-D99697B3A993}.png'
```

### 稍微完整一点的日志
![1724756499021](https://github.com/user-attachments/assets/e368ec5d-90d5-4c2b-b7e0-d00db9e0a7f2)

### OneBot 客户端运行日志

具体的不贴了，aiocqhttp调用get_image接口报错返回上游实现异常
[ActionFailed, retCode=1200]

**Comment by MliKiowa** [comment]
通过 get_msg试试直接拿url

**Comment by azmiao** [comment]
> 通过 get_msg试试直接拿url

直接获取消息内容的话虽然接口应该是可以的，但我这里其实就是通过消息内容解析后去反查图片信息😘

**Comment by MliKiowa** [comment]
好的 最近将进行支持

**Comment by MliKiowa** [comment]
已修

**Comment by ragnarok6324** [comment]
![a920df2b5c05ec6392f5268a92df1a4722296467](https://github.com/user-attachments/assets/71842be7-f54f-4c64-bd5f-f2d2e3559e47)
更新至2.2.26后似乎出现了别的问题

**Comment by azmiao** [comment]
@MliKiowa 看起来。。。貌似有点其他问题？👀

**Comment by xmengnet** [comment]
用不了，我记得之前版本是可以用的

**Comment by Wesley-Young** [comment]
请使用 `file_id` （也就是图片中给出的 `NapCatOneBot-` 开头的字符串）

**Comment by azmiao** [comment]
> 请使用 `file_id` （也就是图片中给出的 `NapCatOneBot-` 开头的字符串）

哦这样吗，请问是指传参换 `file_id`吗？现在napcat的`get_image`接口不兼容onebot标准协议了吗
![image](https://github.com/user-attachments/assets/76f58296-e99e-4709-9aa7-8b4464cd603e)

**Comment by xmengnet** [comment]
> > 请使用 `file_id` （也就是图片中给出的 `NapCatOneBot-` 开头的字符串）
> 
> 哦这样吗，请问是指传参换 `file_id`吗？现在napcat的`get_image`接口不兼容onebot标准协议了吗 ![image](https://private-user-images.githubusercontent.com/54100327/363411519-76f58296-e99e-4709-9aa7-8b4464cd603e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxMDYxNjksIm5iZiI6MTcyNTEwNTg2OSwicGF0aCI6Ii81NDEwMDMyNy8zNjM0MTE1MTktNzZmNTgyOTYtZTk5ZS00NzA5LTlhYTctOGI0NDY0Y2Q2MDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEyMDQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZWI1MjEyYTNkODMyYzBlOGM3YWYxNjBhMDY2YTdkMjk0ZDRlYTdmMGI3YjdiYzY0ZWJkMDEzNGU2M2QwZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HbP5sv5y4N7Qx8YgFhRDbWi_4hOhLXJmqyva8XYO-dU)

试了下并不行，file字段是强制的，用file字段写file_id的值也不行

**Comment by Wesley-Young** [comment]
https://github.com/NapNeko/NapCatQQ/actions/runs/10645249057

**Comment by azmiao** [comment]
@ragnarok6324 你试试上面这个action编译的版本
![92bfc07d4a9b9fee94802449fff03468](https://github.com/user-attachments/assets/a20c2beb-046c-4858-9d37-defcbfd120e6)

**Comment by Wesley-Young** [comment]
2.2.30 已更新

**Comment by azmiao** [comment]
@Wesley-Young 请问这接口调用返回的URL变成路径了吗，拿不到url了吗
![image](https://github.com/user-attachments/assets/0b7335f5-70da-41fd-ab26-340f6b8e190e)

**Comment by MliKiowa** [comment]
> @Wesley-Young 请问这接口调用返回的URL变成路径了吗，拿不到url了吗 ![image](https://private-user-images.githubusercontent.com/54100327/363453419-0b7335f5-70da-41fd-ab26-340f6b8e190e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjM1MDYsIm5iZiI6MTcyNTE2MzIwNiwicGF0aCI6Ii81NDEwMDMyNy8zNjM0NTM0MTktMGI3MzM1ZjUtNzBkYS00MWZkLWFiMjYtMzQwZjZiOGUxOTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA0MDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMjIwNWRkNjQzZDA1MDc5Njc2MzllMGZkYzJlNTQ5NzM0ODU1OWRlZWU0YzczNzZkODI0ZmFhOGQ2NzFkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6UMuTWmkV_G7iByvr1mD6WqfthKgedwwH7ovEYZgUG4)

使用get_msg获取图片

**Comment by azmiao** [comment]
> > @Wesley-Young 请问这接口调用返回的URL变成路径了吗，拿不到url了吗 ![image](https://private-user-images.githubusercontent.com/54100327/363453419-0b7335f5-70da-41fd-ab26-340f6b8e190e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNjM1MDYsIm5iZiI6MTcyNTE2MzIwNiwicGF0aCI6Ii81NDEwMDMyNy8zNjM0NTM0MTktMGI3MzM1ZjUtNzBkYS00MWZkLWFiMjYtMzQwZjZiOGUxOTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA0MDAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiMjIwNWRkNjQzZDA1MDc5Njc2MzllMGZkYzJlNTQ5NzM0ODU1OWRlZWU0YzczNzZkODI0ZmFhOGQ2NzFkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6UMuTWmkV_G7iByvr1mD6WqfthKgedwwH7ovEYZgUG4)
> 
> 使用get_msg获取图片

`get_image`拿不到图片URL吧

**Comment by azmiao** [comment]
主要是消息的原始信息里的CQ码并不是一定包含url参数的，因为有缓存存在的原因，导致我需要根据CQ码中的file去调用`get_image`接口反查其URL，现在看来这个接口是修好了，能正常调用了，但是结果中的URL变成了缓存文件的路径了，话说这个napcat这边能否处理呢

**Comment by MliKiowa** [comment]
> 主要是消息的原始信息里的CQ码并不是一定包含url参数的，因为有缓存存在的原因，导致我需要根据CQ码中的file去调用`get_image`接口反查其URL，现在看来这个接口是修好了，能正常调用了，但是结果中的URL变成了缓存文件的路径了，话说这个napcat这边能否处理呢

可以下个版本

**Comment by MliKiowa** [comment]
> 主要是消息的原始信息里的CQ码并不是一定包含url参数的，因为有缓存存在的原因，导致我需要根据CQ码中的file去调用`get_image`接口反查其URL，现在看来这个接口是修好了，能正常调用了，但是结果中的URL变成了缓存文件的路径了，话说这个napcat这边能否处理呢

2.2.36 已支持
