### ISSUE TITLE
希望修改get_essence_msg_list，使其尽可能遵循gocq设计的返回值

### ISSUE THREAD

**Issue by BEISNWKZNAN** [NapNeko/NapCatQQ#315]
[gocq](https://docs.go-cqhttp.org/api/#%E8%8E%B7%E5%8F%96%E7%B2%BE%E5%8D%8E%E6%B6%88%E6%81%AF%E5%88%97%E8%A1%A8)
[问题](https://github.com/BEISNWKZNAN/nonebot-plugin-essence-message/issues/4)
（顺便问一下这个项目怎么调试）

**Comment by MliKiowa** [comment]
v2.2.21已修 请测试

**Comment by MliKiowa** [comment]
如果还有问题开issue

**Comment by SherkeyXD** [comment]
现在貌似最多只会返回 20 条？

**Comment by MliKiowa** [comment]
> 现在貌似最多只会返回 20 条？

tx的接口问题 到时候我再改改
