### ISSUE TITLE
[功能请求] 扩展 API: 设置bot自身信息

### ISSUE THREAD

**Issue by LingLambda** [NapNeko/NapCatQQ#318]
希望能增加一套设置bot自身信息的api,如昵称,签名等.  
或许可以和设置头像API合并一下?

**Comment by MliKiowa** [comment]
你好请翻阅nc和gocq文档 此类api已有set_qq_profile

**Comment by MliKiowa** [comment]
还有 单独的设置签名api set_self_longnick

**Comment by MliKiowa** [comment]
详细 请自行翻阅gocq napcat文档

**Comment by LingLambda** [comment]
谢谢,是我眼瞎了
