### ISSUE TITLE
[BUG] napcat的设精和取消设精华event没有返回管理员的id

### ISSUE THREAD

**Issue by BEISNWKZNAN** [NapNeko/NapCatQQ#320]
### 系统版本

NapCat-docker最新版

### QQNT 版本

NapCat-docker最新版

### NapCat 版本

NapCat-docker最新版

### OneBot 客户端

.

### 发生了什么?

napcat的设精和取消设精华event没有返回管理员的id([operator_id](https://docs.go-cqhttp.org/event/#%E7%B2%BE%E5%8D%8E%E6%B6%88%E6%81%AF%E5%8F%98%E6%9B%B4))
在src/onebot/event/notice/OB11GroupEssenceEvent.ts中
![image](https://github.com/user-attachments/assets/0dc35e37-5551-47d8-b175-6ae80c0ebb3c)

### 如何复现

调用

### 期望的结果?

[参考](https://docs.go-cqhttp.org/event/#%E5%85%B6%E4%BB%96%E5%AE%A2%E6%88%B7%E7%AB%AF%E5%9C%A8%E7%BA%BF%E7%8A%B6%E6%80%81%E5%8F%98%E6%9B%B4)

**Comment by Wesley-Young** [comment]
当前机制（通过 GrayTip 解析）不支持获取设置精华消息的管理员，支持需要时间。

**Comment by BEISNWKZNAN** [comment]
好的

**Comment by Wesley-Young** [comment]
应当以 Not planned 的形式 close。
