### ISSUE TITLE
群成员增加上报是否扩展了ob11？

### ISSUE THREAD

**Issue by W1ndys** [NapNeko/NapCatQQ#327]
我在调试的时候发现sub_type多了一个add类型，ob11没提到的，NapCatQQ的官方文档也没找到相关内容

> 其实主要原因是我写入群欢迎的时候，设置了if sub_type，不知道有add所以有的没触发，查日志才发现这个add

**Comment by MliKiowa** [comment]
是的

**Comment by Wesley-Young** [comment]
查看源代码发现并没有以 `sub_type: 'add'` 构造事件的情况，不知你所用的版本是什么？

**Comment by W1ndys** [comment]
> 是的

代表主动加群吗，还是啥🤔

**Comment by MliKiowa** [comment]
> > 是的
> 
> 代表主动加群吗，还是啥🤔

post_type呢

**Comment by MliKiowa** [comment]
给出详细日志和解释 以及尝试过程 期望结果

**Comment by W1ndys** [comment]
> > > 是的
> > 
> > 
> > 代表主动加群吗，还是啥🤔
> 
> post_type呢

不好意思，我的锅，刚看了一下文档发现问题了
https://github.com/botuniverse/onebot-11/blob/master/event/request.md#%E5%8A%A0%E7%BE%A4%E8%AF%B7%E6%B1%82%E9%82%80%E8%AF%B7
https://github.com/botuniverse/onebot-11/blob/master/event/notice.md#%E7%BE%A4%E6%88%90%E5%91%98%E5%A2%9E%E5%8A%A0
add字段属于request事件
我一直只考虑了notice事件

不过加群请求事件出现后，群增加事件就不上报了，不知道这是不是设计就是这样还是bug
