### ISSUE TITLE
[suggestion]建议给powershell加一个防止点击X导致误操作关闭框架的机制

### ISSUE THREAD

**Issue by bianyuan456** [NapNeko/NapCatQQ#331]
远程服务器，有时候要知道鼠标在哪，点击了一下屏幕，而恰好点到了cmd或者powershell的关闭区域，尽管点击的区域跟它沾一点点边。
我自己写的窗口，点击关闭按钮会弹出一个确认框，是否确认关闭，见下图
![截图20240902150548](https://github.com/user-attachments/assets/b296777b-03d1-4da3-9570-da054d228c08)

我希望咱们的框架也加上这样一个机制，我特意为作者搜了，百度搜索还有AI答案呢！我代码这块不熟，作者参考下下面代码，考虑下加一个防止误操作点击到关闭按钮的机制吧，谢谢！
![截图20240902150634](https://github.com/user-attachments/assets/f24d9f7c-c685-49f1-a3a2-238781d3108a)
![截图20240902150643](https://github.com/user-attachments/assets/b50c9277-9c24-4de5-a145-24ac4b86d5d0)
![截图20240902150649](https://github.com/user-attachments/assets/3b1e0aa0-ae4d-4b5d-a576-3213b5d0b868)

最后说一下这个需求的由来，我是插件作者，实际上我的插件本来是想把CMD窗口置父窗口形式放到我的窗口中的，如下图
![截图20240902151018](https://github.com/user-attachments/assets/e2fc53b7-ca70-4c33-8085-58063eb70888)

但是我担心我的插件问题崩溃导致框架也跟着崩溃，所以还是不要把框架的cmd跟我的插件窗口绑定到一起了，那么问题就来了，我的插件窗口带着关闭误操作提醒，但是框架不带这个呀，所以来提一个issue，让框架作者也考虑加一个这个

**Comment by yongheng1014** [comment]
所以你为什么启动之后不开最小化，不是所有人都跟你一样

**Comment by bianyuan456** [comment]
> 所以你为什么启动之后不开最小化，不是所有人都跟你一样

要看到运行日志，随时观察，所以不最小化。我这是提建议，你不要这么尖酸刻薄，你可以用不到，但是它有的话不是更好吗

**Comment by bianyuan456** [comment]
> 这边建议自己再套一个 ps1 脚本来启动 napcat 的脚本，这样就能解决了捏

谢谢，在脚本，特别是windows脚本这块我不会呀，特别是后缀为ps1类型的脚本，或者后缀为bat的脚本，我没写过。框架作者看来写过很多，他来写，应该是最合适的。如果框架作者说没想法，那就算了吧。

**Comment by bianyuan456** [comment]
> 这边建议自己再套一个 ps1 脚本来启动 napcat 的脚本，这样就能解决了捏

对了，我试过给ps1套一个bat脚本，但是我发现它在执行了ps1之后就忽略了bat脚本后面的内容，等于是重新打开一个powershell了。

**Comment by Wesley-Young** [comment]
如有相关需求请提 Pull Request，或考虑使用 Bat 脚本

**Comment by bianyuan456** [comment]
> 如有相关特性需求请提 Pull Request，或考虑使用 Bat 脚本

我试过给ps1套一个bat脚本，但是我发现它在执行了ps1之后就忽略了bat脚本后面的内容，等于是重新打开一个cmd窗口了。
好吧，谢谢你的解答。

**Comment by MliKiowa** [comment]
> > 如有相关特性需求请提 Pull Request，或考虑使用 Bat 脚本
> 
> 我试过给ps1套一个bat脚本，但是我发现它在执行了ps1之后就忽略了bat脚本后面的内容，等于是重新打开一个cmd窗口了。 好吧，谢谢你的解答。

里面有bat脚本
