### ISSUE TITLE
[BUG] 有段时间的表情回应事件WS不推送

### ISSUE THREAD

**Issue by eSakuras** [NapNeko/NapCatQQ#333]
### 系统版本

Windows server 2012 R2

### QQNT 版本

9.9.15.27597

### NapCat 版本

2.2.30

### OneBot 客户端

-

### 发生了什么?

在一些情况下，回应表情消息时在NC日志会正常显示灰条消息，移动端也有提示，但是没有推送到ws事件中

### 如何复现

回应有段时间的消息就会出现，可能是七八小时前？近期消息的回应都是正常推送

### 期望的结果?

事件正常推送

### NapCat 运行日志

```shell
接收 <- 群聊 (群 xxxx 的 0) [灰条消息]
```

**Comment by MliKiowa** [comment]
5分钟后的表情回应都会丢弃

**Comment by MliKiowa** [comment]
晚点的版本可能会优化 但这并不是一个bug 是太久远的消息带来的负担太大 nc限制到了5分钟

**Comment by MliKiowa** [comment]
> > 晚点的版本可能会优化 但这并不是一个bug 是太久远的消息带来的负担太大 nc限制到了5分钟
> 
> 麻烦大佬了，问下大佬如果太麻烦的话是否有可能做成可选项，比如服务器资源富裕而且群消息很少情况下，可以适当延长一段时间

正在修 刚重写了回复消息部分

**Comment by MliKiowa** [comment]
2.2.40 已修

> > 晚点的版本可能会优化 但这并不是一个bug 是太久远的消息带来的负担太大 nc限制到了5分钟
> 
> 麻烦大佬了，问下大佬如果太麻烦的话是否有可能做成可选项，比如服务器资源富裕而且群消息很少情况下，可以适当延长一段时间

2.2.40已修

**Comment by MliKiowa** [comment]
对了如果是别人的消息是收不到的哦
