### ISSUE TITLE
[BUG] get_msg 获取不到消息

### ISSUE THREAD

**Issue by eSakuras** [NapNeko/NapCatQQ#354]
### 系统版本

Windows server 2012 R2

### QQNT 版本

27597

### NapCat 版本

2.4.3

### OneBot 客户端

-

### 发生了什么?

get_msg 获取不到消息内容，返回的消息内容为空

### 如何复现

-

### 期望的结果?

-

**Comment by MliKiowa** [comment]
撤回的消息不行
