### ISSUE TITLE
[BUG] 更新到最新版后库库弹ERROR

### ISSUE THREAD

**Issue by fllesser** [NapNeko/NapCatQQ#359]
### 系统版本

debian 11

### QQNT 版本

-

### NapCat 版本

v2.4.9

### OneBot 客户端

-

### 发生了什么?

![Screenshot_20240912_215758_tech lolli toolbox_edit_34696844803036](https://github.com/user-attachments/assets/f4f2664e-65e7-43be-88e8-47a43ad3e4f6)

### 如何复现

-

### 期望的结果?

-

**Comment by MliKiowa** [comment]
不影响使用

**Comment by cnxysoft** [comment]
没有复现，建议尝试升级最新版。
另，如并非Docker/一键部署，请提供QQ版本。

**Comment by fllesser** [comment]
> 没有复现，建议尝试升级最新版。 另，如并非Docker/一键部署，请提供QQ版本。

是一键部署的，刚刚又升级了，还是这样，登录完就开始弹

**Comment by Image-Net** [comment]
![image](https://github.com/user-attachments/assets/7311e290-8037-4219-ba2d-7c393827f577)
也遇到了

**Comment by Image-Net** [comment]
每次加好友的时候必定出现

**Comment by cnxysoft** [comment]
已经复现，将在下一版本修复。
