### ISSUE TITLE
[BUG] `get_group_member_list`部分信息不能获取

### ISSUE THREAD

**Issue by Kittengarten** [NapNeko/NapCatQQ#361]
### 系统版本

Ubuntu 22.04

### QQNT 版本

3.2.12-27597

### NapCat 版本

2.5.0

### OneBot 客户端

OneBotv11 HTTP连接

### 发生了什么?

`get_group_member_list`返回的许多字段不正常，如`age`为`0`，`level`、`qq_level`为`0`，`sex`为`"unknown"`，`join_time`、`last_sent_time`均为当前时间戳。

### 如何复现

使用 http://host:port/get_group_member_list?group_id=example&access_token=example&no_cache=true
，在返回的响应中即可观察到，如图所示。
![image](https://github.com/user-attachments/assets/020c9a19-de24-4fae-9f59-17d07ff991fb)

### 期望的结果?

应当返回实际的值。

**Comment by MliKiowa** [comment]
获取详情走单成员获取 list提供这个api延迟会起飞

**Comment by Kittengarten** [comment]
> 获取详情走单成员获取 list提供这个api延迟会起飞

那将需要给每个群成员调用一遍 api，延迟只会更高（大悲）
