### ISSUE TITLE
[BUG] 通过好友请求QQ号为0

### ISSUE THREAD

**Issue by Image-Net** [NapNeko/NapCatQQ#368]
### 系统版本

Windows server 2016 datacenter

### QQNT 版本

27597

### NapCat 版本

2.5.0

### OneBot 客户端

自做

### 发生了什么?

通过好友请求QQ号显示为0

### 如何复现

通过好友请求

### 期望的结果?

正常显示QQ号
![P_N(LB88NLD @E}MYK NNJ9](https://github.com/user-attachments/assets/152cb185-ecff-40e3-800f-935c9cec1b7f)

### NapCat 运行日志

```shell
{"time":1726336673,"self_id":,"post_type":"notice","notice_type":"friend_add","user_id":0}
```

**Comment by MliKiowa** [comment]
还有别的日志吗

**Comment by Image-Net** [comment]
通过好友请求NapCat没有记录日志

**Comment by cnxysoft** [comment]
已复现，请等待修复。

**Comment by cnxysoft** [comment]
已修复，将于下一版本推送。
