### ISSUE TITLE
[BUG] 发送临时消息超时

### ISSUE THREAD

**Issue by Huasushis** [NapNeko/NapCatQQ#37]
### 系统版本

1

### QQNT 版本

1

### NapCat 版本

1

### OneBot 客户端

1

### 发生了什么?

在网页（http方式）上用send_msg发送临时消息返回发送超时。

### 如何复现

发送/send_msg?message_type=private&user_id=xxx&message=hello&group_id=xxx

### 期望的结果?

希望能正常发送，并且希望临时消息地上报中加入类似gocqhttp的temp_source的条目来获得临时消息的group_id。

**Comment by MliKiowa** [comment]
你去掉group_id发试试

**Comment by Huasushis** [comment]
> 你去掉group_id发试试

今天它显示“不能发送临时消息”，加不加group_id都是这样，send_msg和send_private_msg都返回这个。

**Comment by MliKiowa** [comment]
那就是不支持(临时消息风险大
