### ISSUE TITLE
[BUG] 推荐群聊/联系人存在的问题

### ISSUE THREAD

**Issue by Image-Net** [NapNeko/NapCatQQ#371]
### 系统版本

Windows server 2016 datacenter

### QQNT 版本

27597

### NapCat 版本

2.5.0

### OneBot 客户端

自做

### 发生了什么?

![image](https://github.com/user-attachments/assets/c8f96084-9cfe-4b4c-8b45-8eb59b063af7)
调用该接口提示不支持的api ArkShareGroupEx
查看文档发现类似名字的接口
![image](https://github.com/user-attachments/assets/b09093ee-982b-45d2-abed-19f73968f308)
调用这个接口可以正常返回推荐群聊，文档中写了推荐联系人/群聊，但是传入联系人QQ号会导致QQ卡死

![image](https://github.com/user-attachments/assets/2d2d423f-1c63-4409-844d-2e0c31707998)
调用该接口会提示必须传入group_id实际上其他两个参数没有用
相当于没有办法推荐好友

### 如何复现

调用接口ArkShareGroupEx/ArkShareGroup/ArkSharePeer

### 期望的结果?

修正文档，调用接口ArkSharePeer能够正常推送好友

**Comment by MliKiowa** [comment]
https://github.com/NapNeko/NapCatQQ/commit/f0e376d06bbc65adc198c4c94f29c5710026eec9

交换后 调用该接口 正常 无法复现卡住

测试环境: Win64QQ
![image](https://github.com/user-attachments/assets/eefccaaf-970b-4a0f-904a-d66838539c42)

**Comment by Image-Net** [comment]
接口名交换吗

**Comment by MliKiowa** [comment]
你使用 ArkShareGroup 请求带上user_id

**Comment by MliKiowa** [comment]
下个版本ArkShareGroup 换成ArkSharePeer了 这是我打错了

**Comment by MliKiowa** [comment]
如果仍然有疑问请前往官方群
