### ISSUE TITLE
[Question] go-cqhttp接口兼容性问题

### ISSUE THREAD

**Issue by VincentVanNF** [NapNeko/NapCatQQ#376]
### 系统版本

Win11 22H + WSL2 + Ubuntu 22.04

### QQNT 版本

Linuxqq 3.2.12-27597

### NapCat 版本

2.5.0

### OneBot 客户端

OneBot11

### 发生了什么?

go-cqhttp的群打卡接口貌似没有兼容实现？
![image](https://github.com/user-attachments/assets/3f86e4f3-3b02-45b9-84d1-0b4e704f556c)

### 如何复现

![image](https://github.com/user-attachments/assets/1193c41e-4a53-421d-9c65-4f9e5d4e2d0e)

### 期望的结果?

该如何解决。

**Comment by VincentVanNF** [comment]
gocq-http 接口文档：https://docs.go-cqhttp.org/api/#%E7%BE%A4%E6%89%93%E5%8D%A1

**Comment by Image-Net** [comment]
![image](https://github.com/user-attachments/assets/10709c3d-7252-47e2-ad91-f3de5a2388f5)

**Comment by Image-Net** [comment]
https://napneko.github.io/zh-CN/develop/compatibility/api#go-cqhttp-api

**Comment by VincentVanNF** [comment]
> https://napneko.github.io/zh-CN/develop/compatibility/api#go-cqhttp-api

这是移动端的很多功能PC 端的 NTQQ不支持吗🥲

**Comment by MliKiowa** [comment]
不能实现哦 gocq是Android协议为主
