### ISSUE TITLE
[BUG] QQ被冻结踢下线后 [API] get_status依然显示online: true

### ISSUE THREAD

**Issue by airdm** [NapNeko/NapCatQQ#39]
### 系统版本

Windows 10

### QQNT 版本

9.9.9_240507

### NapCat 版本

1.3.9

### OneBot 客户端

没有

### 发生了什么?

QQ被冻结踢下线后 [API] get_status依然显示online: true

### 如何复现

暂无

### 期望的结果?

希望可以和llob一样可以正常显示离线

### NapCat 运行日志

2024-05-26 07:01:51 [INFO] BOT(123456)
[KickedOffLine] [下线通知] 该账号因涉嫌业务违规操作被暂时冻结，请点击确定按钮后重新输入账号及密码了解详情。你也可以对账 号进行<TITLE="资金管理",URL="https://myun.tenpay.com/mqq/banneduser/index.shtml?_wv=1027">。

2024-05-26 07:01:53 [ERROR] BOT(123456)
发生错误 发送超时

**Comment by MliKiowa** [comment]
下个版本修

**Comment by szh-bash** [comment]
> 下个版本修

如何规避被冻结呢，有无其他缓解策略或设置
