### ISSUE TITLE
[Feature Request] 添加选中消息截图的功能

### ISSUE THREAD

**Issue by FoliageOwO** [NapNeko/NapCatQQ#390]
# 描述

有这样的需要：希望可以开发个 `NapCat API`，允许传入单个消息 ID 或多个消息 ID 组成的列表，然后对其对应的单个消息或多个消息进行截图。返回截图保存的文件地址，或直接返回图片的 `base64` 编码结果。

# 设想

由于本身 `NTQQ` 是 `Electron` 应用，我想应该可以实现类似于浏览器中的页面元素截图。

至于传入的消息 ID 列表，如果不是连续的（暂时不知道这个如何实现判断），按顺序截图后进行拼接。

**Comment by RTAkland** [comment]
自己get msg处理

**Comment by FoliageOwO** [comment]
> 自己get msg处理

可以是可以，文字和图片都好处理，但是表情怎么办？似乎没有现成的表情资源文件，估计要解包 `NTQQ`。还有小程序、特殊大表情、红包等等这些元素怎么办？

而且自己画图片和实际用户消息样式不能保证一定没有偏差，考虑的事情太多了。

我相信不止我，还有别的开发者也有类似的需求，不如直接将 `API` 写好大家都可以用。

所以 IMHO，利用 `NapCat` 层直接对 `NTQQ` 操作来实现消息截图是个更好的方案。

**Comment by rongrong1000** [comment]
你这是业务层的. 肯定不会批准的

**Comment by MliKiowa** [comment]
NapCat没办法做这种事情 考虑自行渲染或者使用第三方方案
