### ISSUE TITLE
[Refactor Needed] /get_record api好像不会转换文件

### ISSUE THREAD

**Issue by daizhuentou** [NapNeko/NapCatQQ#391]
已经安装了FFmpeg能正常发送语音
这是浏览器访问api的截图
<img width="841" alt="屏幕截图 2024-09-21 052058" src="https://github.com/user-attachments/assets/5d0735a6-2fd7-407e-905e-c6e8dd9db5e3">

**Comment by MliKiowa** [comment]
是的
