### ISSUE TITLE
[LiteLoaderQQNT](https://liteloaderqqnt.github.io/) 插件运行后，加载NapCat.Framework.zip运行成功后，运行的目录，配置，日志是在 哪个路径啊？

### ISSUE THREAD

**Issue by leoguan88** [NapNeko/NapCatQQ#393]
### 系统版本

win 10

### QQNT 版本

9.9.15-28060 (64位)

### NapCat 版本

2.6.10

### OneBot 客户端

2.16

### 发生了什么?

[LiteLoaderQQNT](https://liteloaderqqnt.github.io/) 插件运行后，加载NapCat.Framework.zip运行成功后，运行的目录，配置，日志是在 哪个路径啊？

### 如何复现

[LiteLoaderQQNT](https://liteloaderqqnt.github.io/) 插件运行后，加载NapCat.Framework.zip运行成功后，运行的目录，配置，日志是在 哪个路径啊？

### 期望的结果?

[LiteLoaderQQNT](https://liteloaderqqnt.github.io/) 插件运行后，加载NapCat.Framework.zip运行成功后，运行的目录，配置，日志是在 哪个路径啊？

**Comment by MliKiowa** [comment]
在LL插件目录-->NapCatQQ目录
LL设置页面可以查看目录
