### ISSUE TITLE
请问群聊记录存放在哪里，我想把他全放到数据库里可以吗

### ISSUE THREAD

**Issue by ggboles** [NapNeko/NapCatQQ#394]
### 系统版本

win10

### QQNT 版本

。

### NapCat 版本

。

### OneBot 客户端

。

### 发生了什么?

没有找到数据放在哪里

### 如何复现

   。

### 期望的结果?

   。

**Comment by cnxysoft** [comment]
NC无缓存，请接收后自行储存。
