### ISSUE TITLE
[BUG] 安装本插件后较高概率触发qq无法登陆

### ISSUE THREAD

**Issue by dahaozi777** [NapNeko/NapCatQQ#395]
### 系统版本

版本	Windows 11 家庭中文版 版本号	23H2 安装日期	‎2023/‎6/‎9 操作系统版本	22631.4037 体验	Windows Feature Experience Pack 1000.22700.1027.0

### QQNT 版本

9.9.15-28131

### NapCat 版本

2.6.2

### OneBot 客户端

onebot v11

### 发生了什么?

每次登录时，较高概率在qqnt触发正在登陆中页面后，但是qq并没有登录上。经过测试，删除本插件后每次均正常登录。

### 如何复现

用liteloader插件的napcat扩展，正常进行qq登录

### 期望的结果?

正常直接登录qq

**Comment by MliKiowa** [comment]
提高NapCat版本到最新

**Comment by dahaozi777** [comment]
> 提高NapCat版本到最新

不好意思写错了，用的就是napcat的最新版2.6.12

**Comment by MliKiowa** [comment]
命令行启动QQ 附加 --enable-logging 参数启动查看控制台日志和前往插件目录/logs/查看对应时间的日志

**Comment by dahaozi777** [comment]
目前又测试了几次，发现qq进程是登上了的，但是qq应用界面不会弹出，托盘图标也不存在。再次尝试登录也会提示已登录该账号。如果同时登陆了其他账号，结束无效进程后再次登录就不再出现，但是qq的界面经常出现卡顿。以下是报错信息
`Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82968)
    at WebContents.emit (node:events:519:28)
Proxy... Event: NodeIQQNTWrapperSession/create`

**Comment by MliKiowa** [comment]
来官方群
