### ISSUE TITLE
NapCat安装后无法启动

### ISSUE THREAD

**Issue by onerrk** [NapNeko/NapCatQQ#401]
Termux一键安装命令安装完成后，使用给出的启动命令没有正常启动。

**Comment by MliKiowa** [comment]
提示呢

**Comment by MliKiowa** [comment]
错误截图和日志

**Comment by MliKiowa** [comment]
稍等 你先进Q群

**Comment by MliKiowa** [comment]
![Screenshot_2024-09-26-12-44-18-02_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/620c8e66-a4a0-4025-96c5-9f1a7b0b3a4d)
无法复现

**Comment by MliKiowa** [comment]
由于你没有跟进

**Comment by MliKiowa** [comment]
先close了
