### ISSUE TITLE
[BUG] 无法启动napcat

### ISSUE THREAD

**Issue by Agnes4m** [NapNeko/NapCatQQ#403]
### 系统版本

ubuntu24.04

### QQNT 版本

linuxqq (3.2.12-28327)。

### NapCat 版本

2.6.15

### OneBot 客户端

nonebot==2.3.2，nonebot-adapter-onebot==2.4.3

## 我做的事情
    就是正常使用bot的时候，突然注意到bot没反应了，打开napcat端发现链接补上，于是终止程序准备重启，然后就发现不能重启了（因为之前用的时候是1.6.7版本，我还是linux指令安装的，至于原因自然是docker怎么都安装不了见下图）。
![image](https://github.com/user-attachments/assets/dbde2894-3d55-48ce-bd83-30e6f4b3e838)
   后面发现原来是nonebot2端没有启动，并不是napcat的问题，但是我已经没有办法启动napcat了，因为文档中已经删除了手动启动的部分，我自己也再尝试了使用docker也没有成功，我把napcat和liunx_qq更新到最新版本也没有办法

## 总结
   就是忘记手动启动的指令，docker不会用。

### 如何复现

复现如上说明

### 期望的结果?

我希望知道手动指令启动napcat的linux_qq，当前我启动`qq`的报错如下
![image](https://github.com/user-attachments/assets/c2d60d0b-2595-4a9f-b814-26d4d266e022)

### NapCat 运行日志

```shell
不涉及报错信息
```

### OneBot 客户端运行日志

```shell
不涉及报错信息
```

**Comment by cnxysoft** [comment]
鉴于你的网络环境和本地已经存在QQ这个情况，建议再次使用一键脚本安装进行尝试，启动命令会在安装完成后给出，请牢记。
命令如下（直接粘贴运行）：
curl -o napcat.sh https://nclatest.znin.net/NapNeko/NapCat-Installer/main/script/install.sh && sudo bash napcat.sh --docker n --proxy 1 --force

**Comment by Agnes4m** [comment]
我要的指令`xvfb-run -a qq --no-sandbox`好像就是这个，谢谢
