### ISSUE TITLE
[BUG] 初始化NapCat失败 fetchServices Timeout!

### ISSUE THREAD

**Issue by minecraft4668** [NapNeko/NapCatQQ#407]
### 系统版本

Windows Server 2022

### QQNT 版本

9.9.15-28060

### NapCat 版本

2.6.14

### OneBot 客户端

/

### 发生了什么?

初始化NapCat失败 fetchServices Timeout!

### 如何复现

使用NapCat.FrameWork出现错误，按照llqqnt官方修补后仍然出现错误。

### 期望的结果?

正常启动QQ

### NapCat 运行日志

```shell
[LiteLoader] Found Plugin: 彻底禁用更新
[LiteLoader] Found Plugin: 插件列表查看
[LiteLoader] Found Plugin: LLOneBot
[LiteLoader] Found Plugin: NapCatQQ
[NapCat] [Info] 开始初始化NapCat
Error occurred in handler for 'get-remote-win': Error: No handler registered for 'get-remote-win'
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:82968)
    at WebContents.emit (node:events:519:28)
(node:15760) UnhandledPromiseRejectionWarning: Error: node-loader:
RangeError: Maximum call stack size exceeded
    at 15797 (C:\Program Files\Tencent\QQNT\versions\9.9.15-28060\resources\app\application\790.background.js)
    at s (C:\Program Files\Tencent\QQNT\versions\9.9.15-28060\resources\app\application\background.js)
    at 16232 (C:\Program Files\Tencent\QQNT\versions\9.9.15-28060\resources\app\application\790.background.js)
    at s (C:\Program Files\Tencent\QQNT\versions\9.9.15-28060\resources\app\application\background.js)
    at o (C:\Program Files\Tencent\QQNT\versions\9.9.15-28060\resources\app\application\790.background.js)
    at get session (C:\Program Files\Tencent\QQNT\versions\9.9.15-28060\resources\app\application\790.background.js)
    at get ntSession (C:\Program Files\Tencent\QQNT\versions\9.9.15-28060\resources\app\application\790.background.js)
    at 25884 (C:\Program Files\Tencent\QQNT\versions\9.9.15-28060\resources\app\application\790.background.js)
    at s (C:\Program Files\Tencent\QQNT\versions\9.9.15-28060\resources\app\application\background.js)
    at 92103 (C:\Program Files\Tencent\QQNT\versions\9.9.15-28060\resources\app\application\790.background.js)
(Use `QQ --trace-warnings ...` to show where the warning was created)
(node:15760) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[NapCat] [Error] 初始化NapCat失败 fetchServices Timeout!
```

### OneBot 客户端运行日志

```shell
/
```

**Comment by MliKiowa** [comment]
冲突了 提升QQ 版本 关闭一些没用的插件

**Comment by MliKiowa** [comment]
没有跟进 暂时close

**Comment by minecraft4668** [comment]
![image](https://github.com/user-attachments/assets/079d1e2a-ec6b-4bec-ad28-55ab75e2f0a9)
28060不能用吗，一直都是这样，提升了NapCat也没用。而且好像最新的能够进行修补的LLQQNT方法只支持到28060。。。

**Comment by MliKiowa** [comment]
> ![image](https://private-user-images.githubusercontent.com/132268400/372175728-079d1e2a-ec6b-4bec-ad28-55ab75e2f0a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NDAyMjIsIm5iZiI6MTcyNzczOTkyMiwicGF0aCI6Ii8xMzIyNjg0MDAvMzcyMTc1NzI4LTA3OWQxZTJhLWVjNmItNGJlYy1hZDI4LTU1YWI3NWUyZjBhOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkzMFQyMzQ1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MThlNjg2ZDllN2JlNTVmMGVkYWE3Y2RhZmY0ZjE3NDlmNDI1MDQ4MmUxNjk2MmJiNGNhYmY2NTEwYzgyOGRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4SWmed5VuBEjBKKQ_CQn_A_lI2sBtAXQaQKZD9cudLU) 28060不能用吗，一直都是这样，提升了NapCat也没用。而且好像最新的能够进行修补的LLQQNT方法只支持到28060。。。

换个目录纯净安装QQ 使用once版本

**Comment by GongT** [comment]
我也遇到了，我是linux版，运行在docker里，除了QQ、LiteLoader、list-viewer以外什么也没装，下载NapCat就打不开（登陆界面空白），删了就恢复

**Comment by MliKiowa** [comment]
> 我也遇到了，我是linux版，运行在docker里，除了QQ、LiteLoader、list-viewer以外什么也没装，下载NapCat就打不开（登陆界面空白），删了就恢复

QQ版本多少

**Comment by GongT** [comment]
![image](https://github.com/user-attachments/assets/13567e4a-d8db-4800-a35a-9346172ba76c)

**Comment by MliKiowa** [comment]
> ![image](https://private-user-images.githubusercontent.com/2265048/372841172-13567e4a-d8db-4800-a35a-9346172ba76c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NjkyNzEsIm5iZiI6MTcyNzg2ODk3MSwicGF0aCI6Ii8yMjY1MDQ4LzM3Mjg0MTE3Mi0xMzU2N2U0YS1kOGRiLTQ4MDAtYTM1YS05MzQ2MTcyYmE3NmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMTEzNjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRiMDY3YTBmYzRiM2VjN2MwZWVjNTI1ZWMwNWU1YTRkY2FkMWVmNzQwZmQ3NzY4YWIwNWNkNGQwYTRmMGE4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.T2f4wHJ9Tna0zowHlo6ntz1R9mmwp-epo15Y_ZTBN2o)
> 
> https://dldir1.qq.com/qqfile/qq/QQNT/2b82dc28/linuxqq_3.2.12-26909_x86_64.rpm

https://dldir1.qq.com/qqfile/qq/QQNT/f60e8252/linuxqq_3.2.12-28327_amd64.deb

**Comment by MliKiowa** [comment]
> ![image](https://private-user-images.githubusercontent.com/2265048/372841172-13567e4a-d8db-4800-a35a-9346172ba76c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc4NjkyNzEsIm5iZiI6MTcyNzg2ODk3MSwicGF0aCI6Ii8yMjY1MDQ4LzM3Mjg0MTE3Mi0xMzU2N2U0YS1kOGRiLTQ4MDAtYTM1YS05MzQ2MTcyYmE3NmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMDJUMTEzNjExWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDRiMDY3YTBmYzRiM2VjN2MwZWVjNTI1ZWMwNWU1YTRkY2FkMWVmNzQwZmQ3NzY4YWIwNWNkNGQwYTRmMGE4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.T2f4wHJ9Tna0zowHlo6ntz1R9mmwp-epo15Y_ZTBN2o)
> 
> https://dldir1.qq.com/qqfile/qq/QQNT/2b82dc28/linuxqq_3.2.12-26909_x86_64.rpm

用下面这个 你看看release说的啥 最低28060你这才26909
