### ISSUE TITLE
[BUG] 无法获取历史消息事件

### ISSUE THREAD

**Issue by onerrk** [NapNeko/NapCatQQ#408]
### 系统版本

Termux一键安装脚本

### QQNT 版本

Termux一键安装脚本

### NapCat 版本

Termux一键安装脚本

### OneBot 客户端

没有框架，Nodejs的ws直连

### 发生了什么?

撤回历史消息时，没有上报撤回事件
图一是刚发的消息，是正常有事件上报的
图二是撤回的昨天的某条消息，没有事件上报
![Screenshot_20240928110434](https://github.com/user-attachments/assets/3d249a8b-f893-41aa-b034-89f426095d8c)
![Screenshot_20240928110514](https://github.com/user-attachments/assets/8af8d5ad-377f-42ef-9c96-0c370d57de11)

### 如何复现

撤回昨天或者更早的消息时

### 期望的结果?

应该有撤回事件上报

**Comment by MliKiowa** [comment]
好的 稍后测试

**Comment by MliKiowa** [comment]
过久的撤回消息确实不行 其实这也不算bug 超过太久 消息id失效了

**Comment by MliKiowa** [comment]
下个大版本修复
