### ISSUE TITLE
[V3 RoadMap] 规划

### ISSUE THREAD

**Issue by MliKiowa** [NapNeko/NapCatQQ#413]
- [x] 群Recall拦截
- [ ] 私聊Recall拦截
- [ ] 文件直链
- [ ] 伪造合并转发
- [ ] 优化被禁言后的处理
- [x] 新版本MacOs适配 
- [x] 跟进NT Core新版本
- [ ] Fuck O3
- [ ] Framework目录迁移
- [ ] Framework与Shell组合包
- [x] 替换ProtobufJS或者解决现有问题
- [x] 缓解Rkey网络问题
- [x] 发包
- [x] 收包

**Comment by bianyuan456** [comment]
有没有考虑过支持QQ频道的API?
我是指就是用普通QQ身份在频道收发消息，不是q.qq.com那种官方机器人身份收发消息的

**Comment by MliKiowa** [comment]
> 有没有考虑过支持QQ频道的API? 我是指就是用普通QQ身份在频道收发消息，不是q.qq.com那种官方机器人身份收发消息的

没有

**Comment by EatHatsuneShallots** [comment]
> 没有

go-cqhttp 是有相关 API 和事件的

**Comment by bianyuan456** [comment]
> go-cqhttp 是有相关 API 和事件的
谢谢，可是go-cqhttp 已经停止更新快1年了。。go-cqhttp 的作者都建议迁移到别的框架了(https://github.com/Mrs4s/go-cqhttp/issues/2471)。。。
更重要的是go-cqhttp基本登录不上去，或者说侥幸登录上了会被冻结qq。。

**Comment by huankong233** [comment]
> > go-cqhttp 是有相关 API 和事件的
> > 谢谢，可是go-cqhttp 已经停止更新快1年了。。go-cqhttp 的作者都建议迁移到别的框架了[Mrs4s/go-cqhttp#2471](https://github.com/Mrs4s/go-cqhttp/issues/2471)
> > 更重要的是go-cqhttp基本登录不上去，或者说侥幸登录上了会被冻结qq。。

qq频道官方基本上也是半弃坑状态，而且用的人其实不多

**Comment by bianyuan456** [comment]
> > > go-cqhttp 是有相关 API 和事件的
> > > 谢谢，可是go-cqhttp 已经停止更新快1年了。。go-cqhttp 的作者都建议迁移到别的框架了[Mrs4s/go-cqhttp#2471](https://github.com/Mrs4s/go-cqhttp/issues/2471)
> > > 更重要的是go-cqhttp基本登录不上去，或者说侥幸登录上了会被冻结qq。。
> 
> qq频道官方基本上也是半弃坑状态，而且用的人其实不多

感谢解答。。我反而是觉得就是因为qq频道官方由于国内和自己公司的原因限制的太严格了才导致它现在半弃坑状态，或者说正是由于对普通人申请官方频道机器人的限制太多，长久以来没有普通QQ号码就能收发消息的、稳定使用的qq频道机器人框架，这才导致了它现在半弃坑状态。qq频道官方基本上也是半弃坑状态是结果，没有稳定的、普通QQ号码就能收发消息的qq频道机器人框架是原因。。你的说法是倒果为因了，但是我也是承认结果这个事实的。。
不过真要是用的人多就做的话，我的插件还要做微信群的版本的，如果真是用的人多就做的话，咱们的框架有没有考虑做微信群的呢！？

whatever，感谢大家解答。找个能支持普通QQ收发QQ频道消息的稳定的框架好难呀。能做好一件事情就足够了，的确是不用事事都做。

**Comment by huankong233** [comment]
> > > > go-cqhttp 是有相关 API 和事件的
> > > > 谢谢，可是go-cqhttp 已经停止更新快1年了。。go-cqhttp 的作者都建议迁移到别的框架了[Mrs4s/go-cqhttp#2471](https://github.com/Mrs4s/go-cqhttp/issues/2471)
> > > > 更重要的是go-cqhttp基本登录不上去，或者说侥幸登录上了会被冻结qq。。
> > 
> > 
> > qq频道官方基本上也是半弃坑状态，而且用的人其实不多
> 
> 感谢解答。。我反而是觉得就是因为qq频道官方由于国内和自己公司的原因限制的太严格了才导致它现在半弃坑状态，或者说正是由于对普通人申请官方频道机器人的限制太多，长久以来没有普通QQ号码就能收发消息的、稳定使用的qq频道机器人框架，这才导致了它现在半弃坑状态。qq频道官方基本上也是半弃坑状态是结果，没有稳定的、普通QQ号码就能收发消息的qq频道机器人框架是原因。。你的说法是倒果为因了，但是我也是承认结果这个事实的。。 不过真要是用的人多就做的话，我的插件还要做微信群的版本的，如果真是用的人多就做的话，咱们的框架有没有考虑做微信群的呢！？
> 
> whatever，感谢大家解答。找个能支持普通QQ收发QQ频道消息的稳定的框架好难呀。能做好一件事情就足够了，的确是不用事事都做。

应该不会支持微信，微信要严格的多，做出来了可能也不会放出来

**Comment by ohmykreee** [comment]
有无规划类似于 go-cqhttp 的 [事件过滤器](https://docs.go-cqhttp.org/guide/eventfilter.html) 的功能，可以针对部分指定的通信方式应用自定规则。

因为有些公开的bot服务（比如公开一个反向的ws地址，然后需要使用的人自己申请QQ号和搭建bot应用，接入该反向ws地址），希望只上报指定格式的消息（比如开头是 `!` 的消息，或者不上报指定群聊的消息），以降低公共服务群的负载。

**Comment by Natsukage** [comment]
拦截群recall似乎失效许久了（在最新版本上）
对于已经被撤回的消息，get_msg只能获取到空内容
而recall事件本身又不上报被撤回的消息具体内容，所以即使在recall事件的响应中立刻get_msg也无法取得被撤回的消息内容了，只能在插件端自己单独记录所有聊天记录以备不时之需。
我记得之前隔壁llonebot是可以get_msg到撤回消息的。这个帖子的主楼在2周前编辑过，群recll拦截依然还是打钩状态，但是我在2周前测试时就已经是无法获取被撤回的群消息的状态了，不确定是bug还是napcat现在不支持了

**Comment by MliKiowa** [comment]
> 拦截群recall似乎失效许久了（在最新版本上） 对于已经被撤回的消息，get_msg只能获取到空内容 而recall事件本身又不上报被撤回的消息具体内容，所以即使在recall事件的响应中立刻get_msg也无法取得被撤回的消息内容了，只能在插件端自己单独记录所有聊天记录以备不时之需。 我记得之前隔壁llonebot是可以get_msg到撤回消息的。这个帖子的主楼在2周前编辑过，群recll拦截依然还是打钩状态，但是我在2周前测试时就已经是无法获取被撤回的群消息的状态了，不确定是bug还是napcat现在不支持了

暂时去掉了

**Comment by MliKiowa** [comment]
原因嘛 是因为不成熟 未来完整实现再端上来
