### ISSUE TITLE
加好友没有request事件，有notice或者message但不上报flag参数，

### ISSUE THREAD

**Issue by CoisionG** [NapNeko/NapCatQQ#418]

**Comment by MliKiowa** [comment]
版本呢

**Comment by CoisionG** [comment]
> 版本呢

NapCatQQ版本是 2.6.20  windows11 qq 版本9.9.15-28327    linux是ubuntu24.04 然后通过 mlikiowa/napcat-docker:latest 这个镜像部署的

**Comment by MliKiowa** [comment]
明天进行测试

**Comment by MliKiowa** [comment]
![87434a1da8d894bdebed52107b2ddb2c](https://github.com/user-attachments/assets/9d8d0ef0-19be-416c-9976-696291fb428d)

**Comment by MliKiowa** [comment]
无法复现
