### ISSUE TITLE
[ISSUE]希望给日志占用空间优化

### ISSUE THREAD

**Issue by cidaodao** [NapNeko/NapCatQQ#42]
### 系统版本

Windows Sever 2019 Datacenter

### QQNT 版本

QQ9.9.9.23361_x64

### NapCat 版本

NapCat V1.2.0

### OneBot 客户端

OneBot 11

### 发生了什么?

开发者你好，这个日志的功能可以优化么，我加的群比较多 挂在服务器上一天就要用掉一G的硬盘大小，空间用完了就会出现“SQLLITE FULL"错误
![3d48ed96a293aefa48989f7ccb45c4e7](https://github.com/NapNeko/NapCatQQ/assets/65718636/830366ca-b22e-4712-ac78-3820cf9a527c)
![image](https://github.com/NapNeko/NapCatQQ/assets/65718636/979ebbb6-254c-4c14-aa07-6832d5904d33)

![19d5da174b1f7acd497b42bd9ae5283f](https://github.com/NapNeko/NapCatQQ/assets/65718636/aff1f9ee-10ef-4c35-a6d7-b9ddf4522791)

### 如何复现

持续挂在服务器上超过24小时
空间占用超过1G（群聊多的情况下）

### 期望的结果?

减少硬盘占用的开销

**Comment by MliKiowa** [comment]
你把日志等级调整为 error https://napneko.github.io/zh-CN/guide/config
