### ISSUE TITLE
[BUG] 为什么接口又变动了(*'へ'*)

### ISSUE THREAD

**Issue by hhhhhge** [NapNeko/NapCatQQ#420]
### 系统版本

Win10 ltsc

### QQNT 版本

9.9.15 28327

### NapCat 版本

2.6.20

### OneBot 客户端

nonebot2

### 发生了什么?

不是为什么群文件的api没了

### 如何复现

(Ｔ▽Ｔ)

### 期望的结果?

之前版本好好的

**Comment by MliKiowa** [comment]
抱歉 现在接口是gocq风格

**Comment by MliKiowa** [comment]
摸摸头 qwq 如果还有问题和意见的话可以查看readme的群链接 进群问哦
