### ISSUE TITLE
[BUG] 安装中断后如何清理干净以便重新运行脚本安装

### ISSUE THREAD

**Issue by SkyIce0229** [NapNeko/NapCatQQ#422]
### 系统版本

debain11

### QQNT 版本

null

### NapCat 版本

最新脚本

### OneBot 客户端

null

### 发生了什么?

断开ssh连接后重新运行好像就没继续下载了

### 如何复现

1.在下载的途中断开ssh
2.重新运行一键脚本

### 期望的结果?

继续未安装的地方继续安装

**Comment by MliKiowa** [comment]
先清理安装的linuxqq 然后删除/opt/QQ的内容 最后在之前执行脚本的位置 ls 删除所有缓存文件 如果有疑问请看ReadMe（项目主页的） QQ群 进入 询问

**Comment by EatHatsuneShallots** [comment]
建议在 `tmux` 等终端复用器运行脚本
这个建议建议写到文档里
