### ISSUE TITLE
[BUG] 获取群成员信息接口的join_time字段是动态的

### ISSUE THREAD

**Issue by W1ndys** [NapNeko/NapCatQQ#424]
### 系统版本

docker最新

### QQNT 版本

docker最新

### NapCat 版本

docker最新

### OneBot 客户端

Python

### 发生了什么?

发了两次请求，返回的值两次的join_time不一致（实际显示为当前时间的时间戳），但该字段应该意为入群时间，应该是固定的

### 如何复现

发API请求

### 期望的结果?

返回正确的时间戳

### NapCat 运行日志

```shell
无
```

### OneBot 客户端运行日志

![image](https://github.com/user-attachments/assets/5314e130-59b0-45ac-a326-be9bfb84d802)

![image](https://github.com/user-attachments/assets/51a12b49-88b6-4639-bcdc-9bba28fee8fa)

**Comment by MliKiowa** [comment]
未获取到的结果兜底是现行时间

**Comment by W1ndys** [comment]
> 未获取到的结果兜底是现行时间

未获取到结果的发生率高不高，是否有必要自己写一个用来存储入群时间的功能（已实现了，是打算直接调用API获取的时候发现的这个）

ps（雪宝回复的好快qaq）

**Comment by MliKiowa** [comment]
> > 未获取到的结果兜底是现行时间
> 
> 未获取到结果的发生率高不高，是否有必要自己写一个用来存储入群时间的功能（已实现了，是打算直接调用API获取的时候发现的这个）
> 
> ps（雪宝回复的好快qaq）

没有测试新版 但之前的版本是几乎大部分没问题的

**Comment by MliKiowa** [comment]
你也可以群里直接问

**Comment by W1ndys** [comment]
> > > 未获取到的结果兜底是现行时间
> > 
> > 
> > 未获取到结果的发生率高不高，是否有必要自己写一个用来存储入群时间的功能（已实现了，是打算直接调用API获取的时候发现的这个）
> > ps（雪宝回复的好快qaq）
> 
> 没有测试新版 但之前的版本是几乎大部分没问题的

好的

> 你也可以群里直接问

好的喵
