### ISSUE TITLE
[BUG] 退群功能 set_group_leave 失效 

### ISSUE THREAD

**Issue by 1411484730** [NapNeko/NapCatQQ#43]
### 系统版本

Ubuntu 22.04.4 LTS

### QQNT 版本

Linux 3.2.8-23873 amd64

### NapCat 版本

1.4.0

### OneBot 客户端

None

### 发生了什么?

退群api超时失效

### 如何复现

1.使用 set_group_leave 离开某个群聊
2.群聊为临时讨论组（不确定）
3.群聊关闭搜索（不确定）

### 期望的结果?

账号退出指定群聊

### NapCat 运行日志

```shell
无错误日志被打印
```

### OneBot 客户端运行日志

```shell
退出群聊失败 || 错误 <class 'nonebot.adapters.onebot.v11.exception.NetworkError'>: NetWorkError(message='WebSocket call api set_group_leave timeout')
```

**Comment by MliKiowa** [comment]
在log文件夹找到日志

**Comment by 1411484730** [comment]
稍等

**Comment by MliKiowa** [comment]
适配器调用不够规范

**Comment by 1411484730** [comment]
了解了

**Comment by MliKiowa** [comment]
现在试试

**Comment by 1411484730** [comment]
可以了
