### ISSUE TITLE
关于“转发消息(forward)”处理顺序的疑问

### ISSUE THREAD

**Issue by Aimang2002** [NapNeko/NapCatQQ#430]
### 系统版本

Ubuntu22.04LTS

### QQNT 版本

QQ_3.2.12_240927_arm64

### NapCat 版本

NapCat V2.6.25

### OneBot 客户端

通过ws对接的程序

### 发生了什么?

我想知道转发消息的处理流程，是不是如下：
收到转发消息->打印INFO->处理转发消息->向API接口上报

我在对接的时候，NcpCat首先是输出了转发消息的INFO消息，之后过了一段时间后我才接收到“转发消息”的Json数据，在等待的这段时间中，NapCat是在处理数据吗？

### 如何复现

1.发送“转发消息”

### 期望的结果?

以下为个人建议：
1.发送“转发消息”
2.NapCat接收到消息并处理(不打印INFO)
3.“转发消息”处理完成，打印INFO
4.上报

**Comment by MliKiowa** [comment]
是的
