### ISSUE TITLE
[BUG] send_msg某些情况下出现Error: 请指定 group_id 或 user_id

### ISSUE THREAD

**Issue by 127Wzc** [NapNeko/NapCatQQ#431]
### 系统版本

docker

### QQNT 版本

docker- 2.6.25

### NapCat 版本

2.6.25

### OneBot 客户端

正向ws

### 发生了什么?

前两天升级后nc，trss的客户端触发私聊send_msg动作nc突然出现 Error: 请指定 group_id 或 user_id。
因为首次出现并没有记录到前置条件，后尝试手动触发send_msg发现一种必现的流程如下。

### 如何复现

1.send_msg先发送一个错误参数如下：(这里故意写 type =group 且不指定group_id)触发这个异常
```
{
    "action": "send_msg",
    "params": {
        "message_type": "group",
        "user_id": "1274925976",
        "message": [
            {
                "type": "text",
                "data": {
                    "text": "hai"
                }
            }
        ]
    }
}

```
2.send_msg省去message_type

> onebot11对这个参数(message_type)是可选的 然后根据*_id区分type，同时下面参数在异常未发生的时候是正常的。

> **但是在经过步骤1后 再发送下面同样隐去`message_type`会出现 Error: 请指定 group_id 或 user_id。
对此我的解决方案是：1.重启nc，2.或者客户端每次send_msg携带message_type** 

```
{
    "action": "send_msg",
    "params": {
        "user_id": "1274925976",
        "message": [
            {
                "type": "text",
                "data": {
                    "text": "hai"
                }
            }
        ]
    }
}

```

### 期望的结果?

猜测是异常污染了局部变量吧，给使用trss的出现该问题的提个醒。 给那边提pr添加type被拒了，期望nc这边可以增强下代码健壮性～
[问题issue](https://github.com/TimeRainStarSky/Yunzai/issues/131)

### NapCat 运行日志

```shell
2024-10-11 21:38:32 [ERROR] 2号(xxx) | 发生错误 Error: 请指定 group_id 或 user_id

    at createContext (file:///app/napcat/napcat.mjs:30676:9)

    at SendMsg._handle (file:///app/napcat/napcat.mjs:30701:24)

    at SendMsg.websocketHandle (file:///app/napcat/napcat.mjs:30619:34)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async OB11PassiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:13742:21) 
```
```


### OneBot 客户端运行日志

```shell
无
```

**Comment by MliKiowa** [comment]
暂时没有头绪

**Comment by MliKiowa** [comment]
下个大版本修复
