### ISSUE TITLE
[BUG] 运行NapCatWinBootMain后登录QQ点“设置”自动重启返回到QQ登录界面

### ISSUE THREAD

**Issue by lunaiger** [NapNeko/NapCatQQ#437]
### 系统版本

Windows service 2022

### QQNT 版本

9.9.15 28498

### NapCat 版本

2.6.27

### OneBot 客户端

/

### 发生了什么?

运行NapCatWinBootMain后登录QQ点“设置”自动重启返回到QQ登录界面

### 如何复现

运行NapCatWinBootMain后登录QQ点“设置”

### 期望的结果?

能够正常启动NapCat

**Comment by MliKiowa** [comment]
[LL.zip](https://github.com/user-attachments/files/17391267/LL.zip)

**Comment by lunaiger** [comment]
好的，谢谢，我试一下

**Comment by lunaiger** [comment]
问题依旧，还是会重启，是不是与LiteLoaderQQNT1.2.2插件有关

**Comment by MliKiowa** [comment]
关闭其它插件试试

**Comment by MliKiowa** [comment]
很奇怪的问题

**Comment by MliKiowa** [comment]
进群下 然后call下我

**Comment by lunaiger** [comment]
> 关闭其它插件试试

我没装其他插件

**Comment by MliKiowa** [comment]
我远程看看

**Comment by MliKiowa** [comment]
> 进群下 然后call下我

这里不好聊

**Comment by lunaiger** [comment]
> > 进群下 然后call下我
> 
> 这里不好聊

进了

**Comment by xiaofengv233** [comment]
请问解决了吗?我一样出现了这个问题

**Comment by xiaofengv233** [comment]
系统版本
Windows Server 2022 Standard

QQNT 版本
9.9.16-28788

NapCat 版本

NapCat V3.0.0
