### ISSUE TITLE
[BUG] get_group_msg_history并未向前回溯

### ISSUE THREAD

**Issue by Natsukage** [NapNeko/NapCatQQ#441]
### 系统版本

Windows Server 2022 Datacenter

### QQNT 版本

9.9.15-28498

### NapCat 版本

3.0.0

### OneBot 客户端

无（ws连接测试）

### 发生了什么?

和https://github.com/LLOneBot/LLOneBot/issues/472相同的问题

大概描述：

`get_group_msg_history`这个API在不提供message_seq时，会从最后一条向前回溯指定条消息（这里假设为100条），但是在提供了message_seq后，它就变成了取得给定id**之后**的消息而不是之前了，所以没法用递归的方法继续向前回溯。
例如我现在有`1-300`条消息，在不传递`message_seq`的情况下，用`get_group_msg_history`获得了`201-300`条以后，我提供第201条消息的messageId作为`message_seq`请求100条消息，`get_group_msg_history`方法会返回从201开始的**接下来**100条消息也就是`201-300`条，而不是`101-200`条，导致无论如何都没法回溯到201之前的消息。我尝试传递负值进去也没用
以前的逻辑好像是回溯的（也可能是我记错了），所以可以通过递归传递`message_seq`不断往前回溯，直到message的时间超出范围，但是现在不行了。所以无法通过递归实现"取得最近一天的所有消息“的操作。
我不确定这是bug还是为了迎合Onebot的正常特性，但是之前在LLOneBot那边反馈后修改了，所以姑且认为这是bug吧（
辛苦了！

### 如何复现

1. 使用`get_group_msg_history`获取最近N条消息（例如10条）
2. 将最早的一条消息（也就是上面获取的最后一条消息）作为`message_seq`传入`get_group_msg_history`继续调用获取10条消息
3. `get_group_msg_history`获取的是上一条消息**之后**的10条消息，而不是**之前**的，也就是这里获取的10条消息和第一步获取的消息完全相同

### 期望的结果?

在传入`message_seq`时，向前回溯寻找更早的消息而不是向后。
或者保留现在的特性，但是允许传入负值以允许向前查找消息。

### NapCat 运行日志

```shell
无（没有报错，上面反馈的是方法本身运行时表现的特性）
```

### OneBot 客户端运行日志

```shell
无
```

**Comment by MliKiowa** [comment]
https://github.com/NapNeko/NapCatQQ/blob/1e6116554f467a2bc206ed4578f39e624f7c524b/src/onebot/action/go-cqhttp/GetGroupMsgHistory.ts#L18

传入这个参数

**Comment by Natsukage** [comment]
> https://github.com/NapNeko/NapCatQQ/blob/1e6116554f467a2bc206ed4578f39e624f7c524b/src/onebot/action/go-cqhttp/GetGroupMsgHistory.ts#L18
> 
> 传入这个参数

传入这个参数只是让传递的表格反向了，并没有让查询向前回溯

例如，现在群里有3000条消息，我一次查询1000条，第一次我查询1000会查询到**3000-2001**这1000条消息。
然后我以第2001条消息为`message_seq`参数传入`get_group_msg_history`，这时获取到的是反向的**2001-3000**条消息
也就是这个参数仅仅只是把查询到的消息列表逆序了一下，并没有向前回溯
因此无法通过第2001条消息继续向前递归查询第**1002-2001**条消息。
因此无法实现类似于”获取最近一天内的所有消息“一类的功能。

**Comment by Natsukage** [comment]
[temp.log](https://github.com/user-attachments/files/17448570/temp.log)
我已经确认传入了reverseOrder
日志中，第一次的100个查询是不传入reverseOrder和message_seq的原本表现
第二次的100个查询是传入message_seq和reverseOrder（true）的表现。可以看到第二次实际上是查询了message_seq**之后**的消息，只是单纯把这100条消息反序了。
而issue中提到的问题和reverseOrder并没有关联
