### ISSUE TITLE
[BUG] 人机合一时查看旧聊天记录似乎会导致群名片修改事件被异常触发

### ISSUE THREAD

**Issue by Natsukage** [NapNeko/NapCatQQ#444]
### 系统版本

Windows Server 2022 Datacenter

### QQNT 版本

9.9.15-28498

### NapCat 版本

3.0.0

### OneBot 客户端

-

### 发生了什么?

![image](https://github.com/user-attachments/assets/39433065-9489-4477-881a-6b8dcc027ea5)

如图所示，图中bot在每天都会修改自己的群名片，所以每天的群名片是不同的
当在人机合一的QQNT中搜索特定关键字查看之前的聊天记录时，群名片更新事件似乎会被不断触发并上报。（上报的群名片可能是查看到对应消息时用的群名片，但是我不确定）
理论上来说如果是在无头状况下是不会触发这个bug的，只有人机合一时才能查看聊天记录

### 如何复现

人机合一的状况下，点开任意群组的聊天记录并搜索任意关键字向前跳转，跳转到之前群名片不同的时候的聊天记录

### 期望的结果?

在这种场合下不上报群名片更新事件

**Comment by MliKiowa** [comment]
好的

**Comment by MliKiowa** [comment]
这个问题 应该是历史消息意外流向ob事件了 我晚点看看
