### ISSUE TITLE
[BUG] log闹麻了

### ISSUE THREAD

**Issue by qhy040404** [NapNeko/NapCatQQ#446]
### 系统版本

Server 2022 21H2

### QQNT 版本

9.9.16-28788

### NapCat 版本

3.0.3

### OneBot 客户端

PRIVATE

### 发生了什么?

![image](https://github.com/user-attachments/assets/8bde1cdf-847a-4aff-8d61-fbb5945b259e)
像是verbose进info了

### 如何复现

启动 登录 收消息

### 期望的结果?

![image](https://github.com/user-attachments/assets/231921c5-c590-4d7c-b1a2-c831c098c022)
正常log

**Comment by qhy040404** [comment]
https://github.com/NapNeko/NapCatQQ/blob/main/src/onebot/index.ts#L579

**Comment by MliKiowa** [comment]
我忘记删了 抱歉
