### ISSUE TITLE
[Optimize]合并戳一戳接口

### ISSUE THREAD

**Issue by molanp** [NapNeko/NapCatQQ#447]
## 需求

将`private_poke`和`group_poke`合并为`poke`一个接口，便于调用

## 行为

传参第一个为`user_id`，第二个为`group_id`

只传入`user_id`时为`private_poke`，否则为`group_poke`

**Comment by molanp** [comment]
附：

文档不包含NapCat独有的接口传参说明，望补充

**Comment by MliKiowa** [comment]
此接口使用和lag一致 此需求必要性是否不大

**Comment by MliKiowa** [comment]
> 附：
> 
> 文档不包含NapCat独有的接口传参说明，望补充

至于这个后续补齐 还有别的问题吗

**Comment by molanp** [comment]
无
