### ISSUE TITLE
新版本支持的markdown应该如何发送

### ISSUE THREAD

**Issue by airdm** [NapNeko/NapCatQQ#449]
我按照官方的markdown文档的格式发送 和收到其他官方bot发送的markdown格式 都无法正常发送.
packet已经运行并连接成功 NC版本3.0.6 QQ28788

**Comment by MliKiowa** [comment]
这个功能16号被tx砍了一刀

**Comment by MliKiowa** [comment]
发送需要下个版本 合并转发套两层

**Comment by airdm** [comment]
> 发送需要下个版本 合并转发套两层

已经更新了吗,要怎么发呢?
