### ISSUE TITLE
[BUG] 依旧无法使用MCSM面板类工具启动

### ISSUE THREAD

**Issue by 164ebr** [NapNeko/NapCatQQ#450]
### 系统版本

WIN 11 23H2

### QQNT 版本

9.9.15-28498

### NapCat 版本

3.0.6

### OneBot 客户端

无

### 发生了什么?

![image](https://github.com/user-attachments/assets/c960f39e-ec2b-4054-b599-5bc9b6d4005d)

### 如何复现

![image](https://github.com/user-attachments/assets/d2190c08-0c86-406a-a135-b76a82674ab9)

### 期望的结果?

无

**Comment by MliKiowa** [comment]
你应该直接启动bat试试？ bat里面有环境变量

**Comment by 164ebr** [comment]
> 你应该直接启动bat试试？ bat里面有环境变量

![image](https://github.com/user-attachments/assets/5fe5c1ea-fe11-4310-a840-890d7610d76f)
![image](https://github.com/user-attachments/assets/3f40f288-32d2-4bae-9af3-4b1ca9883861)

 但是会自动弹出一个cmd.. 实际是不希望的

**Comment by MliKiowa** [comment]
好的 你可以改下bat 把单独弹窗去掉

**Comment by maoyuna0w0** [comment]
在命令前面加上sudo就可以了
