### ISSUE TITLE
Packet在连接20多个NC时延迟卡顿很严重.

### ISSUE THREAD

**Issue by airdm** [NapNeko/NapCatQQ#453]
发送戳一戳等需要Packet的功能 大概要延迟1分钟才有反馈

**Comment by MliKiowa** [comment]
你连几个就起新的吧

**Comment by MliKiowa** [comment]
暂时没有优化思路

**Comment by airdm** [comment]
> 暂时没有优化思路

可不可以支持post的方式 只有在特别需要的时候我选择性的去调用Packet

**Comment by MliKiowa** [comment]
> > 暂时没有优化思路
> 
> 可不可以支持post的方式 只有在特别需要的时候我选择性的去调用Packet

post效率过低
