### ISSUE TITLE
[BUG] send_private_forward_msg/send_group_forward_msg 接口引用消息时出现报错，PacketServer模式下user_id无法传string

### ISSUE THREAD

**Issue by Sn0wo2** [NapNeko/NapCatQQ#455]
### 系统版本

Windows 11 家庭中文版 23H2

### QQNT 版本

9.9.15-28418 (64位)

### NapCat 版本

NapCat V3.1.0

### OneBot 客户端

Postman

### 发生了什么?

调用接口send_private_forward_msg和send_group_forward_msg接口时填写messages.data.id参数:
```
{
    "action": "send_private_forward_msg",
    "params": {
        "user_id": 123456,
        "messages": [
            {
                "type": "node",
                "data": {
                    "id": "123456"
                }
            }
        ]
    }
}
```
会出现报错:
```
{
    "status": "failed",
    "retcode": 1200,
    "data": null,
    "message": "TypeError: Cannot read properties of undefined (reading 'type')\n    at OneBotMsgApi.createSendElements (file:///D:/NapCat.Shell/napcat.mjs:26947:40)\n    at GoCQHTTPSendPrivateForwardMsg.handleForwardedNodesPacket (file:///D:/NapCat.Shell/napcat.mjs:33738:67)\n    at GoCQHTTPSendPrivateForwardMsg._handle (file:///D:/NapCat.Shell/napcat.mjs:33714:57)\n    at async GoCQHTTPSendPrivateForwardMsg.websocketHandle (file:///D:/NapCat.Shell/napcat.mjs:33624:23)\n    at async OB11PassiveWebSocketAdapter.handleMessage (file:///D:/NapCat.Shell/napcat.mjs:19684:21)",
    "wording": "TypeError: Cannot read properties of undefined (reading 'type')\n    at OneBotMsgApi.createSendElements (file:///D:/NapCat.Shell/napcat.mjs:26947:40)\n    at GoCQHTTPSendPrivateForwardMsg.handleForwardedNodesPacket (file:///D:/NapCat.Shell/napcat.mjs:33738:67)\n    at GoCQHTTPSendPrivateForwardMsg._handle (file:///D:/NapCat.Shell/napcat.mjs:33714:57)\n    at async GoCQHTTPSendPrivateForwardMsg.websocketHandle (file:///D:/NapCat.Shell/napcat.mjs:33624:23)\n    at async OB11PassiveWebSocketAdapter.handleMessage (file:///D:/NapCat.Shell/napcat.mjs:19684:21)",
    "echo": ""
}
```

### 如何复现

data中包含id参数

### 期望的结果?

正常发送引用的合并消息

### NapCat 运行日志

```shell
2024-10-22 10:35:00 [ERROR] NapCatQQ(123456) | 发生错误 TypeError: Cannot read properties of undefined (reading 'type')
    at OneBotMsgApi.createSendElements (file:///D:/NapCat.Shell/napcat.mjs:26947:40)
    at GoCQHTTPSendPrivateForwardMsg.handleForwardedNodesPacket (file:///D:/NapCat.Shell/napcat.mjs:33738:67)
    at GoCQHTTPSendPrivateForwardMsg._handle (file:///D:/NapCat.Shell/napcat.mjs:33714:57)
    at async GoCQHTTPSendPrivateForwardMsg.websocketHandle (file:///D:/NapCat.Shell/napcat.mjs:33624:23)
    at async OB11PassiveWebSocketAdapter.handleMessage (file:///D:/NapCat.Shell/napcat.mjs:19684:21)
```

**Comment by 164ebr** [comment]
{
    "action": "send_group_msg",
    "params": { 
        "group_id": 123456,
        "message": [
			{
				"type": "node",
				"data": {
					"userId": "123456",
					"nickname": "昵称",
					"content": [
						  {"type": "text", "data": {"text": "这是文本1"}}
					]
				}
			},
			{
				"type": "node",
				"data": {
					"userId": "123456",
					"nickname": "昵称",
					"content": [
						  {"type": "text", "data": {"text": "这是文本2"}}
					]
				}
			}
		]
	}
}

你可以用OneBot 11的API，send_group_msg，这样能发送合并消息

**Comment by Sn0wo2** [comment]
> { "action": "send_group_msg", "params": { "group_id": 123456, "message": [ { "type": "node", "data": { "userId": "123456", "nickname": "昵称", "content": [ {"type": "text", "data": {"text": "这是文本1"}} ] } }, { "type": "node", "data": { "userId": "123456", "nickname": "昵称", "content": [ {"type": "text", "data": {"text": "这是文本2"}} ] } } ] } }
> 
> 你可以用OneBot 11的API，send_group_msg，这样能发送合并消息

我是希望类似QQ中的合并转发, 正确显示原始消息, 例如头像和昵称, #61 提到似乎做不到
那感觉也可以选择修复这个id参数只发送content?

**Comment by pk5ls20** [comment]
> > { "action": "send_group_msg", "params": { "group_id": 123456, "message": [ { "type": "node", "data": { "userId": "123456", "nickname": "昵称", "content": [ {"type": "text", "data": {"text": "这是文本1"}} ] } }, { "type": "node", "data": { "userId": "123456", "nickname": "昵称", "content": [ {"type": "text", "data": {"text": "这是文本2"}} ] } } ] } }
> > 你可以用OneBot 11的API，send_group_msg，这样能发送合并消息
> 
> 我是希望类似QQ中的合并转发, 正确显示原始消息, 例如头像和昵称, #61 提到似乎做不到 那感觉也可以选择修复这个id参数只发送content?

连接PacketServer后调用 `send_private_forward_msg` / `send_group_forward_msg` 可以实现

**Comment by Sn0wo2** [comment]
> > > { "action": "send_group_msg", "params": { "group_id": 123456, "message": [ { "type": "node", "data": { "userId": "123456", "nickname": "昵称", "content": [ {"type": "text", "data": {"text": "这是文本1"}} ] } }, { "type": "node", "data": { "userId": "123456", "nickname": "昵称", "content": [ {"type": "text", "data": {"text": "这是文本2"}} ] } } ] } }
> > > 你可以用OneBot 11的API，send_group_msg，这样能发送合并消息
> > 
> > 
> > 我是希望类似QQ中的合并转发, 正确显示原始消息, 例如头像和昵称, #61 提到似乎做不到 那感觉也可以选择修复这个id参数只发送content?
> 
> 连接PacketServer后调用 `send_private_forward_msg` / `send_group_forward_msg` 可以实现且默认实现伪造合并转发

连接到PacketServer调用`send_group_forward_msg`的情况是:
- 合并消息预览状态, 没点进去的发送者nickname伪造成功
- 点开后nickname恢复bot名称
- userId参数始终不生效(包括头像那些)

这是我的参数:
```
{
    "action": "send_group_forward_msg",
    "params": {
        "group_id": 123456,
        "message": [
            {
                "type": "node",
                "data": {
                    "userId": "123456",
                    "nickname": "qq对应nickname",
                    "content": [
                        {
                            "type": "text",
                            "data": {
                                "text": "这是文本1"
                            }
                        }
                    ]
                }
            },
            {
                "type": "node",
                "data": {
                    "userId": "123456",
                    "nickname": "qq对应nickname",
                    "content": [
                        {
                            "type": "text",
                            "data": {
                                "text": "这是文本2"
                            }
                        }
                    ]
                }
            }
        ]
    }
}
```

**Comment by pk5ls20** [comment]
> > > > { "action": "send_group_msg", "params": { "group_id": 123456, "message": [ { "type": "node", "data": { "userId": "123456", "nickname": "昵称", "content": [ {"type": "text", "data": {"text": "这是文本1"}} ] } }, { "type": "node", "data": { "userId": "123456", "nickname": "昵称", "content": [ {"type": "text", "data": {"text": "这是文本2"}} ] } } ] } }
> > > > 你可以用OneBot 11的API，send_group_msg，这样能发送合并消息
> > > 
> > > 
> > > 我是希望类似QQ中的合并转发, 正确显示原始消息, 例如头像和昵称, #61 提到似乎做不到 那感觉也可以选择修复这个id参数只发送content?
> > 
> > 
> > 连接PacketServer后调用 `send_private_forward_msg` / `send_group_forward_msg` 可以实现且默认实现伪造合并转发
> 
> 连接到PacketServer调用`send_group_forward_msg`的情况是:
> 
> * 合并消息预览状态, 没点进去的发送者nickname伪造成功
> * 点开后nickname恢复bot名称
> * userId参数始终不生效(包括头像那些)
> 
> 这是我的参数:
> 
> ```
> {
>     "action": "send_group_forward_msg",
>     "params": {
>         "group_id": 123456,
>         "message": [
>             {
>                 "type": "node",
>                 "data": {
>                     "userId": "123456",
>                     "nickname": "qq对应nickname",
>                     "content": [
>                         {
>                             "type": "text",
>                             "data": {
>                                 "text": "这是文本1"
>                             }
>                         }
>                     ]
>                 }
>             },
>             {
>                 "type": "node",
>                 "data": {
>                     "userId": "123456",
>                     "nickname": "qq对应nickname",
>                     "content": [
>                         {
>                             "type": "text",
>                             "data": {
>                                 "text": "这是文本2"
>                             }
>                         }
>                     ]
>                 }
>             }
>         ]
>     }
> }
> ```

请参考 https://github.com/botuniverse/onebot-11/blob/master/message/segment.md#%E5%90%88%E5%B9%B6%E8%BD%AC%E5%8F%91%E8%87%AA%E5%AE%9A%E4%B9%89%E8%8A%82%E7%82%B9 的例二构造合并转发节点
