### ISSUE TITLE
创造自定义歌曲分享的时候,过段时间就显示消息异常

### ISSUE THREAD

**Issue by yosoro11111111** [NapNeko/NapCatQQ#456]
### 系统版本

win 10

### QQNT 版本

9.9.15

### NapCat 版本

3.1.0

### OneBot 客户端

没有版本号

### 发生了什么?

创造自定义歌曲分享的时候，刚开始是发出来了，但退出群，再进去两次，发出来的东西变成了消息异常
![675f0167d2a945ed74aeaf43ac8d70b8](https://github.com/user-attachments/assets/d0f18a33-2d72-4e88-b86a-f168b6893ad0)
!(*)

### 如何复现

开了packet服务后发送这个cq码
[CQ:music,type=custom,url=https://raw.kiko-play-niptan.one/media/stream/daily/2021-06-06/RJ328774/mp3/1.%E7%94%B7%E3%81%AE%E5%A8%98%E3%81%A0%E3%81%A3%E3%81%A6%E6%B0%97%E3%81%A5%E3%81%8D%E3%82%82%E3%81%97%E3%81%AA%E3%81%84%E3%81%A7%E3%80%81%E8%B5%A4%E3%81%A1%E3%82%83%E3%82%93%E7%94%98%E3%81%88%E3%81%9F%E3%81%A7%E5%8B%83%E8%B5%B7%E3%81%97%E3%81%A1%E3%82%83%E3%81%86%E3%81%AA%E3%82%93%E3%81%A6%E3%81%AA%E3%81%95%E3%81%91%E3%83%BC%E3%81%84.mp3,audio=https://raw.kiko-play-niptan.one/media/stream/daily/2021-06-06/RJ328774/mp3/1.%E7%94%B7%E3%81%AE%E5%A8%98%E3%81%A0%E3%81%A3%E3%81%A6%E6%B0%97%E3%81%A5%E3%81%8D%E3%82%82%E3%81%97%E3%81%AA%E3%81%84%E3%81%A7%E3%80%81%E8%B5%A4%E3%81%A1%E3%82%83%E3%82%93%E7%94%98%E3%81%88%E3%81%9F%E3%81%A7%E5%8B%83%E8%B5%B7%E3%81%97%E3%81%A1%E3%82%83%E3%81%86%E3%81%AA%E3%82%93%E3%81%A6%E3%81%AA%E3%81%95%E3%81%91%E3%83%BC%E3%81%84.mp3,title=1.男の娘だって気づきもしないで、赤ちゃん甘えたで勃起しちゃうなんてなさけーい.mp3,image=https://raw.kiko-play-niptan.one/media/stream/daily/2021-06-06/RJ328774/%E7%89%B9%E5%85%B8%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88/%E7%89%B9%E5%85%B8%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88.png]

### 期望的结果?

发送后永久保存原样，不变化

### NapCat 运行日志

```shell
2024-10-22 15:17:02 [[32mINFO[39m] Ciallo( ∠ ・ ω [ ) ⌒ ☆(2879679841) | 接收 <- 群聊 [小冰、yosoro、neko在…(688948080)] [poi(2869472750)] asmr328774-1
2024-10-22 15:17:05 [[32mINFO[39m] Ciallo( ∠ ・ ω [ ) ⌒ ☆(2879679841) | 发送 -> 群聊 [poi、QQ小冰、Ciallo( ∠ ・  ω [ ) ⌒ ☆(688948080)] [Ciallo( ∠ ・ ω [ ) ⌒ ☆(2879679841)] [卡片消息]
2024-10-22 15:17:15 [[91mERROR[39m] Ciallo( ∠ ・ ω [ ) ⌒ ☆(2879679841) | 发生错误 Error: Timeout: NTEvent serviceAndMethod:NodeIKernelMsgService/sendMsg ListenerName:NodeIKernelMsgListener/onMsgInfoListUpdate EventRet:
{
    "result": 0,
    "errMsg": ""
}

    at Timeout.sendDataCallback [as _onTimeout] (file:///C:/Users/user_47uIjehkK/Desktop/bot/NapCatShell/napcat.mjs:7725:15)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

### OneBot 客户端运行日志

```shell
688948080成功群组发送[CQ:music,type=custom,url=https://raw.kiko-play-niptan.one/media/stream/daily/2021-06-06/RJ328774/mp3/1.%E7%94%B7%E3%81%AE%E5%A8%98%E3%81%A0%E3%81%A3%E3%81%A6%E6%B0%97%E3%81%A5%E3%81%8D%E3%82%82%E3%81%97%E3%81%AA%E3%81%84%E3%81%A7%E3%80%81%E8%B5%A4%E3%81%A1%E3%82%83%E3%82%93%E7%94%98%E3%81%88%E3%81%9F%E3%81%A7%E5%8B%83%E8%B5%B7%E3%81%97%E3%81%A1%E3%82%83%E3%81%86%E3%81%AA%E3%82%93%E3%81%A6%E3%81%AA%E3%81%95%E3%81%91%E3%83%BC%E3%81%84.mp3,audio=https://raw.kiko-play-niptan.one/media/stream/daily/2021-06-06/RJ328774/mp3/1.%E7%94%B7%E3%81%AE%E5%A8%98%E3%81%A0%E3%81%A3%E3%81%A6%E6%B0%97%E3%81%A5%E3%81%8D%E3%82%82%E3%81%97%E3%81%AA%E3%81%84%E3%81%A7%E3%80%81%E8%B5%A4%E3%81%A1%E3%82%83%E3%82%93%E7%94%98%E3%81%88%E3%81%9F%E3%81%A7%E5%8B%83%E8%B5%B7%E3%81%97%E3%81%A1%E3%82%83%E3%81%86%E3%81%AA%E3%82%93%E3%81%A6%E3%81%AA%E3%81%95%E3%81%91%E3%83%BC%E3%81%84.mp3,title=1.男の娘だって気づきもしないで、赤ちゃん甘えたで勃起しちゃうなんてなさけーい.mp3,image=https://raw.kiko-play-niptan.one/media/stream/daily/2021-06-06/RJ328774/%E7%89%B9%E5%85%B8%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88/%E7%89%B9%E5%85%B8%E3%82%A4%E3%83%A9%E3%82%B9%E3%83%88.png]
这个倒是没有报错
```

**Comment by MliKiowa** [comment]
被屏蔽了 无关napcat
