### ISSUE TITLE
[BUG] <get_group_shut_list>调用卡死

### ISSUE THREAD

**Issue by pohgxz** [NapNeko/NapCatQQ#473]
### 系统版本

Windows 11 专业版 24H2

### QQNT 版本

9.9.16-28788

### NapCat 版本

3.3.22

### OneBot 客户端

无

### 发生了什么?

调用<get_group_shut_list>接口时，如果群里有人被禁言则该链接会卡死

### 如何复现

1.禁言群内任意一人
2.调用接口

### 期望的结果?

正确返回结果

**Comment by yoyokity** [comment]
我也遇到了这个问题，目前用get_group_member_list中的shut_up_timestamp自己筛选一下

**Comment by MliKiowa** [comment]
已修复 下个版本更新
