### ISSUE TITLE
[BUG] 无法获取私聊中被引用的单张图片消息

### ISSUE THREAD

**Issue by StarSky919** [NapNeko/NapCatQQ#477]
### 系统版本

Termux proot Debian (bookworm)

### QQNT 版本

Linux 3.2.13-28788

### NapCat 版本

3.3.26

### OneBot 客户端

-

### 发生了什么?

在私聊中引用单张图片会导致获取消息失败。
![Screenshot_2024-10-30-11-13-31-590_com tencent mobileqq-edit](https://github.com/user-attachments/assets/927c4f74-0a89-44f5-bd86-3917e7869045)
![IMG_20241030_111724](https://github.com/user-attachments/assets/1149d5c5-dac9-453b-acd2-3cead467a62f)

### 如何复现

1.在私聊中发送单张图片。
2.发送一条引用了该图片的消息。
3.收到该消息后对被引用的消息调用get_msg（id来自reply元素）。
该问题会随机出现（即发送单张图片有概率获取不到，不能稳定触发），seq可能是0也可能不是0。
群聊中无此问题。

### 期望的结果?

正常获取到消息内容。

**Comment by MliKiowa** [comment]
进下二群 方便测试
