### ISSUE TITLE
在1.4.1版本get_msg无法获取消息

### ISSUE THREAD

**Issue by xiaoxinzhi123** [NapNeko/NapCatQQ#48]
### 系统版本

windows 11

### QQNT 版本

9.9.10-24108

### NapCat 版本

1.4.1

### OneBot 客户端

无

### 发生了什么?

在1.4.1版本中用get_msg无法获取消息
![Uploading 1.png…]()
在1.3.2版本中是可以使用get_msg来获取消息
![2](https://github.com/NapNeko/NapCatQQ/assets/133210570/a6f47429-5d31-4771-a97c-05aa090ed14e)

### 如何复现

![1](https://github.com/NapNeko/NapCatQQ/assets/133210570/95aa4603-fc00-4909-ab60-400b4e876499)

### 期望的结果?

能否跟1.3.2版本一样请求获取

**Comment by MliKiowa** [comment]
post json 传递number类型 
直接作为url参数 传递的是string
