### ISSUE TITLE
[BUG] 群文件上传异常

### ISSUE THREAD

**Issue by ASTWY** [NapNeko/NapCatQQ#483]
### 系统版本

Armbian OS 24.11.0 bookworm

### QQNT 版本

Docker自带

### NapCat 版本

3.4.5

### OneBot 客户端

nonebot-adapter-onebot

### 发生了什么?

无论使用NoneBot2中call_api还是使用apifox向http服务发送post请求，始终返回 Error: 未知文件类型
在移动端测试账号可以正常上传群文件

### 如何复现

API路径：`/upload_group_file`
请求参数：
`
{
    "group_id": 123456,
    "file": "C:/test.jpg",
    "name": "test.jpg"
}
`
返回结果：
`
{
    "status": "failed",
    "retcode": 200,
    "data": null,
    "message": "Error: 未知文件类型",
    "wording": "Error: 未知文件类型",
    "echo": null
}
`

### 期望的结果?

{
  "status": "ok",
  "retcode": 0,
  "data": null,
  "message": "",
  "wording": ""
}

### NapCat 运行日志

```shell
发生错误 Error: 未知文件类型
    at GoCQHTTPUploadGroupFile._handle (file:///app/napcat/napcat.mjs:36324:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async GoCQHTTPUploadGroupFile.handle (file:///app/napcat/napcat.mjs:35215:23)
    at async OB11PassiveHttpAdapter.handleRequest (file:///app/napcat/napcat.mjs:20919:24)
    at async file:///app/napcat/napcat.mjs:20887:7
```

### OneBot 客户端运行日志

```shell
[OneBot] [WebSocket Client] 收到正向Websocket消息 {"action":"upload_group_file","params":{"group_id":123456,"file":"c:/test.jpg","name":"test.jpg"},"echo":"1"}
```

**Comment by MliKiowa** [comment]
docker具有文件隔离 请挂载对应文件目录到容器 或许使用 base64发送
