### ISSUE TITLE
[BUG] 获取文件失败

### ISSUE THREAD

**Issue by A1Panda** [NapNeko/NapCatQQ#486]
### 系统版本

Ubuntu 24.04.1 

### QQNT 版本

29271

### NapCat 版本

3.4.6 版

### OneBot 客户端

Trss-Yunzai 3.1.3

### 发生了什么?

客户端
![image](https://github.com/user-attachments/assets/bcf4565e-1e44-4e8c-8aa8-c92dea9f3f54)

![image](https://github.com/user-attachments/assets/b99ec628-f8e0-4f8d-ae29-6bf95e455cd2)
协议端
![image](https://github.com/user-attachments/assets/67c37ed0-49c6-44cf-b179-a3f0fe8bb711)

### 如何复现

客户端发送视频文件时

### 期望的结果?

正常发送视频

### NapCat 运行日志

```shell
协议端
![image](https://github.com/user-attachments/assets/67c37ed0-49c6-44cf-b179-a3f0fe8bb711)
```

### OneBot 客户端运行日志

```shell
客户端
![image](https://github.com/user-attachments/assets/bcf4565e-1e44-4e8c-8aa8-c92dea9f3f54)

![image](https://github.com/user-attachments/assets/b99ec628-f8e0-4f8d-ae29-6bf95e455cd2)
```

**Comment by MliKiowa** [comment]
你转发napcat接收的video可能需要先行下载

**Comment by A1Panda** [comment]
是需要先把转发的视频与存在该目录下吗

**Comment by MliKiowa** [comment]
先调用getfile类似的接口
