### ISSUE TITLE
[提问] 是否能在日志中保留图片的具体cdn地址或本地地址

### ISSUE THREAD

**Issue by E1xP** [NapNeko/NapCatQQ#487]
目前日志中INFO级别仅对图片显示：[图片]
目前是否有方法能够在日志中保留图片，如cdn地址或者文件名之类的标识？

此外，目前Bot日志是否带按日分页之类的设置，谢谢

**Comment by MliKiowa** [comment]
这样日志更乱了 至于分页会有的

**Comment by E1xP** [comment]
> 这样日志更乱了 至于分页会有的

这个确实，不过日志主要是要记录收到的消息，群聊相当一部分消息都是图片。
如果可以有方案唯一识别或访问图片，对于使用无头/shell来说日志将更有实用价值

**Comment by MliKiowa** [comment]
没有太大价值 如果错了 可以排查应用端日志
