### ISSUE TITLE
[BUG] 文本内容被误判为CQ码（当文本有CQ码时）

### ISSUE THREAD

**Issue by Aimang2002** [NapNeko/NapCatQQ#488]
### 系统版本

Ubuntu22.04LTS

### QQNT 版本

QQ_3.2.12_240927_arm64

### NapCat 版本

NapCat V3.4.7

### OneBot 客户端

通过ws对接的程序

### 发生了什么?

当我将回复内容通过NapCat发送给对方时，我的message消息（在拥有CQ码的情况下，详细见下面）被解析为CQ，导致内容发不出去。

### 如何复现

message中的内容为：
{[CQ:image,file=file:///tmp/LRIVDNQHYF_4K.jpg]
上面这个CQ码正确吗？}
或者
{
上面这个CQ码正确吗？
[CQ:image,file=file:///tmp/LRIVDNQHYF_4K.jpg]
}

(tips：{}是为了区分才加上去的，源消息中没有)

### 期望的结果?

个人建议：
如不跟其他设计冲突，我建议添加判断解决冲突

**Comment by airdm** [comment]
{
  "type": "text",
  "data": {
    "text": "文本"
  }
}
type为text的时候就不会解析CQ码了

**Comment by MliKiowa** [comment]
转义 或者 通过接口参数控制 或者 消息段格式 如上
