### ISSUE TITLE
[BUG] 自定义合并转发消息被二次转发后news显示异常

### ISSUE THREAD

**Issue by ninthseason** [NapNeko/NapCatQQ#492]
### 系统版本

napcat-docker

### QQNT 版本

9.9.16-28788

### NapCat 版本

3.4.6

### OneBot 客户端

nonebot2-2.3.3

### 发生了什么?

使用PacketServer伪造合并转发，转发内容为图片，由机器人发出的转发消息看上去是正常的：
![image](https://github.com/user-attachments/assets/88c284e8-51e2-443f-8058-3b45f1870e26)
但当手动将该伪造的转发消息二次转发后，消息的news显示会变成Nya～
![image](https://github.com/user-attachments/assets/d1b25190-1bfc-4a82-8665-0e9d497f2b1c)

即使手动指定news参数：
```python
await bot.send_private_forward_msg(
        user_id=event.user_id,
        message=msgs,
        news=[{"text": "a"},]
)
```
也只会影响机器人发出的消息：
![image](https://github.com/user-attachments/assets/98bdd334-8741-41f3-b57c-308c340252cf)
而经过二次转发后伪造的图片消息依然会变成Nya～
![image](https://github.com/user-attachments/assets/a3a41f50-bbed-4e3c-8d22-8b27d3d155a3)

### 如何复现

1. 伪造一个合并转发消息，转发消息体为图片，例如：
```python
@matcher.handle()
async def _(bot: Bot, event: PrivateMessageEvent):
    await bot.send_private_forward_msg(
        user_id=event.user_id,
        message=[
            {
                "type": "node",
                "data": {"user_id": "10001", "nickname": "雪雪看不见我", "content": [
                    {"type": "image", "data": {"file": "https://napcat.napneko.icu/assets/logo.png"}}
                ]},
            }
        ],
    )
```
2. 观察到机器人发出的伪造转发显示正常：
![image](https://github.com/user-attachments/assets/9428b285-03fc-4258-ab52-4082b3518777)
3. 将这条伪造转发二次转发
4. 发现转发消息news显示异常：
![image](https://github.com/user-attachments/assets/2308ffc9-22b1-49a6-afd6-d5a2c1c30f59)

### 期望的结果?

伪造的合并转发消息在经二次转发后依然维持“正常”的news显示

**Comment by pk5ls20** [comment]
无法实现期望的结果

**Comment by ninthseason** [comment]
其实我的诉求仅是伪造的图片消息能在二次转发时显示为"[图片]"而非"Nya~"。

对此我有一个粗糙的解决方案：将容器中`/app/napcat/napcat.mjs`中的6处`TextSummary: "Nya~"`替换为`TextSummary: "[图片]"`，对应部分于源码中应在[src/core/packet/packer.ts](https://github.com/NapNeko/NapCatQQ/blob/81dbb9d980501268eee3653aed9196db5491b47b/src/core/packet/packer.ts#L226)

但不知如此操作是否存在副作用，所以写在这仅供有同样需求的人参考。

**Comment by pk5ls20** [comment]
> 其实我的诉求仅是伪造的图片消息能在二次转发时显示为"[图片]"而非"Nya~"。
> 
> 对此我有一个粗糙的解决方案：将容器中`/app/napcat/napcat.mjs`中的6处`TextSummary: "Nya~"`替换为`TextSummary: "[图片]"`，对应部分于源码中应在[src/core/packet/packer.ts](https://github.com/NapNeko/NapCatQQ/blob/81dbb9d980501268eee3653aed9196db5491b47b/src/core/packet/packer.ts#L226)
> 
> 但不知如此操作是否存在副作用，所以写在这仅供有同样需求的人参考。

这个可以实现
