### ISSUE TITLE
[BUG] 发送匿名转发消息失败

### ISSUE THREAD

**Issue by A1Panda** [NapNeko/NapCatQQ#497]
### 系统版本

Linux

### QQNT 版本

更新容器3.5.2之前可以的

### NapCat 版本

3.5.2

### OneBot 客户端

Trss 3.1.3

### 发生了什么?

024-11-06 11:18:29 [ERROR] 星野爱💫(2783939194) | 发生错误 Error: 发送伪造合并转发消息失败: Error: sendCommand timed out after 20000 ms for trpc.group.long_msg_interface.MsgService.SsoSendLongMsg with trace_id qYRLf7d9602eec60fc724bdcf9c1028e9d2e12ac030803120b120938393435343630303918d9e0c6aa032294031f8b080000000000000313dac0c1c5e15b9a5392e95b9c2eb49883eb2b23973c47c38b496a420c4e621c371f1c5bc5acc4f3b467ffd309bdcfb6753c6b5cafc124b49e91234861cdd2a577d834767deebcc266f071ffea9d6c168c0e0c1e0c559318391804182418b45c324a4a0a8aadf4f50bf50a73f2d3f3f592f3f4335213533273d3e35372ec538a4be24b33f36c2d0c2040adb82035d9d6ccc4400da4a0a4b220d536ab20dd882aa6482970c
    at GoCQHTTPSendGroupForwardMsg._handle (file:///app/napcat/napcat.mjs:35606:15)
    at async GoCQHTTPSendGroupForwardMsg.websocketHandle (file:///app/napcat/napcat.mjs:35512:23)
    at async OB11ActiveWebSocketAdapter.handleMessage (file:///app/napcat/napcat.mjs:20634:21) 

### 如何复现

发送匿名消息

### 期望的结果?

正常发送匿名消息

**Comment by A1Panda** [comment]
准确的说是任何聊天记录都发不出去了

**Comment by MliKiowa** [comment]
更新3.6.0
