### ISSUE TITLE
[提问] 删除好友的API为什么没有按照go-cqhttp去实现？

### ISSUE THREAD

**Issue by MinMinGuGu** [NapNeko/NapCatQQ#498]
![image](https://github.com/user-attachments/assets/5c262ac0-31c1-4178-9456-8ef9dc6c5718)
在go-cqhttp中删除好友的参数是`user_id`

![image](https://github.com/user-attachments/assets/f67f7a40-f33b-4b85-8a0e-7b89d7a83fe3)
但napcat中却是`friend_id`

我在用其他框架来接入napcat时就在删除好友时报了错，原因就在于id参数的命名上。
想知道为什么当初实现没有完全按照go-cqhttp的命名方式？
后续会考虑修改与go-cqhttp保持一致吗？

**Comment by MliKiowa** [comment]
请尝试v3.6.1
