### ISSUE TITLE
[OneBot接口]`get_group_member_info`接口返回的`level`字段类型问题

### ISSUE THREAD

**Issue by CuteReimu** [NapNeko/NapCatQQ#50]
### NapCat 版本
1.3.6

### 问题描述

按照OneBot11的接口定义，`get_group_member_info`返回的`level`应该是`string`类型，但是实际上NapCatQQ接口返回的是：

```jsonc
{
    "status": "ok",
    "retcode": 0,
    "data": {
        "group_id": 12345678,
        "user_id": 87654321,
        "nickname": "",
        "card": "xxxxxx",
        "sex": "unknown",
        "age": 0,
        "area": "",
        "level": 1, // number类型
        "qq_level": 0,
        "join_time": 1663751518,
        "last_sent_time": 1717128963,
        "title_expire_time": 0,
        "unfriendly": false,
        "card_changeable": true,
        "is_robot": false,
        "shut_up_timestamp": 0,
        "role": "member",
        "title": "",
        "qage": 13
    },
    "message": "",
    "wording": "",
    "echo": 93
}
```

附：OneBot-11的接口定义

[https://github.com/botuniverse/onebot-11/blob/master/api/public.md](https://github.com/botuniverse/onebot-11/blob/master/api/public.md#get_group_member_info-%E8%8E%B7%E5%8F%96%E7%BE%A4%E6%88%90%E5%91%98%E4%BF%A1%E6%81%AF)

| 字段名 | 数据类型 | 说明 |
| ----- | ------- | --- |
| `group_id` | number (int64) | 群号 |
| `user_id` | number (int64) | QQ 号 |
| `nickname` | string | 昵称 |
| `card` | string | 群名片／备注 |
| `sex` | string | 性别，`male` 或 `female` 或 `unknown` |
| `age` | number (int32) | 年龄 |
| `area` | string | 地区 |
| `join_time` | number (int32) | 加群时间戳 |
| `last_sent_time` | number (int32) | 最后发言时间戳 |
| **`level`** | **string** | **成员等级** |
| `role` | string | 角色，`owner` 或 `admin` 或 `member` |
| `unfriendly` | boolean | 是否不良记录成员 |
| `title` | string | 专属头衔 |
| `title_expire_time` | number (int32) | 专属头衔过期时间戳 |
| `card_changeable` | boolean | 是否允许修改群名片 |

**Comment by MliKiowa** [comment]
下个版本

**Comment by MliKiowa** [comment]
有问题再open

**Comment by CuteReimu** [comment]
@MliKiowa 又变回去了，疑似 cd62e8ca37ff5089cf5d2a9205653658644bd282 引入的BUG

**Comment by CuteReimu** [comment]
> @MliKiowa 又变回去了，疑似 [cd62e8c](https://github.com/NapNeko/NapCatQQ/commit/cd62e8ca37ff5089cf5d2a9205653658644bd282) 引入的BUG

似乎又不是这个原因，好像看这个提交又没什么问题。暂时没发现原因，但结果确实变回数字了
