### ISSUE TITLE
[BUG] /get_group_member_list 返回的群成员名片是旧的

### ISSUE THREAD

**Issue by MQPearth** [NapNeko/NapCatQQ#506]
### 系统版本

Windows 10 Pro 20H2

### QQNT 版本

9.9.15-28498 (64位)

### NapCat 版本

3.6.7

### OneBot 客户端

http

### 发生了什么?

某群员修改了群名片
/get_group_member_list
该接口返回的card仍然是之前的

### 如何复现

1. 群员修改群名片
2. /get_group_member_list

### 期望的结果?

返回最新的card

**Comment by MliKiowa** [comment]
使用 no_cache 设置为true

**Comment by MQPearth** [comment]
仍然一样

**Comment by MliKiowa** [comment]
那就进q2群来调试吧

**Comment by MliKiowa** [comment]
已确认问题 下个版本修复
