### ISSUE TITLE
[BUG] WebUI 的登陆状态不会随账号实际状态更新

### ISSUE THREAD

**Issue by Murasame2333** [NapNeko/NapCatQQ#508]
### 系统版本

Windows 11

### QQNT 版本

9.9.15-28060

### NapCat 版本

3.6.8

### OneBot 客户端

Nonebot2

### 发生了什么?

在运行 Napcat 应用后，进入到 WebUI 的 `/webui/login.html` 下，此时能够正常显示登陆页面。
![image](https://github.com/user-attachments/assets/59b23493-654d-4c3c-88c8-1627ad6b4b2c)
在 Napcat 登陆QQ之后，如果**该账号被动掉线或是主动下线，账号状态变更为离线。**
![屏幕截图 2024-11-10 022420](https://github.com/user-attachments/assets/87824e1a-2e90-483a-a5ae-58d5b553240b)
如果此时再次进入 WebUI 的 `/webui/login.html` 下，尝试扫码登陆，则**会被强制跳转到 `/webui/config.html`** ，**导致无法再次进行登陆**
![image](https://github.com/user-attachments/assets/03bc3728-8fa8-4ada-acb0-6095c20c062f)
即使在 `/webui/login.html` 中尝试使用快速登陆，浏览器也会弹窗告知QQ已登陆。显然WEBUI 未能够同步QQ的实际在线状态。
![image](https://github.com/user-attachments/assets/ae561b8f-46e7-489e-9d2d-c9ba37163c62)
以上情况会一直持续到直到重启 napcat 应用。

### 如何复现

1. 使用 Napcat 登陆QQ号。
2. 使该QQ号下线（如账号自动掉线、或使用另一台PC挤号、或直接使用手机QQ让PC设备下线等）。
3. 进入 WEBUI。

### 期望的结果?

在 Napcat 应用检测到该账号已经离线后，会让 WEBUI 同步该账号状态，提供在 WEBUI 再次登陆的功能。

**Comment by MliKiowa** [comment]
事实上napcat的登录逻辑几乎是一次性的 如果掉线再走一次登录 需要改很多代码 考虑未来的大版本在re过程实现 现在最好的方法就是
1. 用ws监听到状态变更 对napcat进程kill 并尝试快速登录 （用py脚本之类的实现）
2. 手动重启napcat
