### ISSUE TITLE
[BUG] 有头模式登录后白屏无响应时间过长

### ISSUE THREAD

**Issue by HeiZiSama** [NapNeko/NapCatQQ#510]
### 系统版本

Windows 11 专业工作站版 22H2 22621.1778

### QQNT 版本

9.9.16 - 29456

### NapCat 版本

3.6.9

### OneBot 客户端

无

### 发生了什么?

点击登录按钮，显示全屏窗口时，llonebot白屏时间为2s，napcat白屏时间为18s，测试时只启用单独一个插件，无其他插件。

### 如何复现

登录时必现

### 期望的结果?

缩短无响应时间

**Comment by MliKiowa** [comment]
自行处理缓存垃圾与提高配置
