### ISSUE TITLE
请求 MarketFace 上报事件中加入 package id

### ISSUE THREAD

**Issue by abc1763613206** [NapNeko/NapCatQQ#515]
RT，package id 指的是商城表情包的 ID，没想明白为什么 LLOneBot 还有的东西到了 NapCat 就丢了（

NapCat 相关位置： https://github.com/NapNeko/NapCatQQ/blob/704ac11cbb1b9aa886cc7bdbc1a4abe9825b63e5/src/onebot/api/msg.ts#L176-L196

LLOneBot 参考实现：https://github.com/LLOneBot/LLOneBot/blob/0d27ef7ebc0e3af7e41a4405b596ff5acab578c0/src/onebot11/entities.ts#L324-L342

**Comment by MliKiowa** [comment]
下个版本加入

**Comment by MliKiowa** [comment]
file_unique: _.key  不就是key吗

**Comment by abc1763613206** [comment]
> file_unique: _.key 不就是key吗

@MliKiowa 实际上需要的是 packageId，就是原创表情里指向**整个表情包主页**的 ID。

具体而言，以分享链接 https://zb.vip.qq.com/hybrid/emoticonmall/detail?id=235237 为例，此处需要拿到 235237，换句话说，就是 https://github.com/NapNeko/NapCatQQ/blob/main/src/onebot/api/msg.ts#L497
