### ISSUE TITLE
获取转发消息内容，有时的type为json，有时为正确的forward

### ISSUE THREAD

**Issue by mmSerena** [NapNeko/NapCatQQ#516]
json的结果通过获取合并转发内容 /get_forward_msg 接口也无法获得正确结果
错误示例如下：
![image](https://github.com/user-attachments/assets/3472c3c0-6bff-482e-9790-f92fb5a8084e)

**Comment by MliKiowa** [comment]
前往二群来测试

**Comment by MliKiowa** [comment]
自身发送时上报json 接收全为forward 经过测试
