### ISSUE TITLE
转发消息上报缺少数据

### ISSUE THREAD

**Issue by linkstartCC** [NapNeko/NapCatQQ#528]
### 系统版本

Windows 11 专业版 24H2 26120.2222

### QQNT 版本

无

### NapCat 版本

v4.0.3

### OneBot 客户端

v4.0.3

### 发生了什么?

http消息上报 转发消息 缺少数据
![ef08a2572af0dd40aa5acee789e1575e](https://github.com/user-attachments/assets/86f712f4-4fa3-42ec-a1db-dcdc260868fb)

### 如何复现

转发合并的消息记录到机器人，机器人通过http上报的消息内容缺少数据

### 期望的结果?

希望能解析转发的消息记录

**Comment by MliKiowa** [comment]
通过gocq接口获取具体数据
