### ISSUE TITLE
[BUG] 如果在json文件中设置了多个反向ws地址，只有最后一个会正常连接

### ISSUE THREAD

**Issue by ccicnce113424** [NapNeko/NapCatQQ#537]
### 系统版本

Ubuntu 24.04.1 LTS (Noble Numbat)

### QQNT 版本

3.2.13-29456

### NapCat 版本

4.1.5

### OneBot 客户端

(多个）TRSS-Yunzai v3.1.3，Koishi/4.18.1，nonebot2 2.4.0 

### 发生了什么?

在json文件中设置了多个反向ws地址，只有最后一个会被正常连接，其余均没有连接

### 如何复现

1. 编辑对应qq号的onebot11.json文件，在reserveWs的url数组中填入多个反向ws地址
2. 启动nc并登录对应qq号

### 期望的结果?

NapCat应该连接上每一个给定的反向ws地址并正常收发消息

**Comment by fllesser** [comment]
同

**Comment by MliKiowa** [comment]
好的 晚点修复

**Comment by MliKiowa** [comment]
使用webui配置 同时截图你的配置

**Comment by fllesser** [comment]
> 使用webui配置 同时截图你的配置

没用webui配置，更新后自动变成这样的，用webui重新配置一下就可以了吗

![Screenshot_20241118_140659_tech.lolli.toolbox_edit_46138279314833.jpg](https://github.com/user-attachments/assets/80b9c4a4-1004-490c-a3c7-177374b8355d)

**Comment by fllesser** [comment]
我似乎知道了，这个name是不是不能重名

**Comment by MliKiowa** [comment]
> 我似乎知道了，这个name是不是不能重名

是的

**Comment by fllesser** [comment]
修改后可以了
![Screenshot_20241118_141153_tech.lolli.toolbox_edit_46442677461140.jpg](https://github.com/user-attachments/assets/0dbf57a1-5ce0-4ac3-89d3-91370a5d6c40)

> 我似乎知道了，这个name是不是不能重名

**Comment by ccicnce113424** [comment]
> > 我似乎知道了，这个name是不是不能重名
> 
> 是的

我用的是新版配置文件，reverseWs里面只有一个urls数组

**Comment by ccicnce113424** [comment]
> > > 我似乎知道了，这个name是不是不能重名
> > 
> > 
> > 是的
> 
> 我用的是napcat文档中的配置文件格式，reverseWs里面只有一个urls数组，没有地方修改名字

rebuild后已转换为新格式，问题解决

**Comment by howrain** [comment]
找了半天在这解决了，一直用的老配置文件，突然只有一个ws能用（挠头），感谢
