### ISSUE TITLE
[BUG] 合并转发消息内的所有 QQ 号与实际用户的 QQ 号不一致

### ISSUE THREAD

**Issue by Cola-Ace** [NapNeko/NapCatQQ#541]
### 系统版本

Ubuntu 22.04

### QQNT 版本

通过 NapCat.1Panel 安装，也许是 3.2.13-29456

### NapCat 版本

4.1.6

### OneBot 客户端

Koishi 4.18.1 & koishi-plugin-adapter-onebot 6.7.4

### 发生了什么?

在合并转发消息内的所有 QQ 号都为 `1094950020`，这导致了我无法通过 QQ 号来获取发送者的头像。
无论是经过了 koishi 的转发，还是直接通过  NapCat 的 http 接口获取合并转发消息，结果都一样。

### 如何复现

任意合并转发消息都会出现这种情况

### 期望的结果?

正确返回发送者的 QQ 号

**Comment by MliKiowa** [comment]
这是因为QQ在服务器端屏蔽了

**Comment by EatHatsuneShallots** [comment]
> 这是因为QQ在服务器端屏蔽了

貌似 NTQQ 就会这样
所以怎么获得头像呢

**Comment by MliKiowa** [comment]
> > 这是因为QQ在服务器端屏蔽了
> 
> 貌似 NTQQ 就会这样 所以怎么获得头像呢

我之后看看应该可以获取头像
