### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by guobao97811** [NapNeko/NapCatQQ#542]
### 系统版本

win10

### QQNT 版本

9.9.16.29456

### NapCat 版本

4.1.6

### OneBot 客户端

使用NapCatQQ Ddsktop安装的QQ与NapCat

### 发生了什么?

<img width="968" alt="67e2760b632c1b88955a2a1fe9155cd" src="https://github.com/user-attachments/assets/c0e3fd69-5325-4ab3-9770-29d09d7e55eb">
新增加的qq并不会根据默认配置项进行配置
![WeChat截图_20241119134030](https://github.com/user-attachments/assets/0b1cba5f-2590-453b-b883-57a7ee2a0d6f)

### 如何复现

1.删除或卸载QQ
2.删除或卸载NapCat
 重新安装后并且设置与之前不同的安装目录 

### 期望的结果?

正常根据默认配置进行新账号的配置

### NapCat 运行日志

```shell
11-19 13:32:11 [[33mwarn[39m] 二维码已保存到 E:\项目\e项目_最版本QQ机器人\QQ\NapCat\cache\qrcode.png
11-19 13:32:40 [[34mdebug[39m] 本账号数据/缓存目录： D:\qq聊天\Tencent Files\NapCat\data
11-19 13:32:40 [[32minfo[39m] [Core] [Config] 配置文件创建成功!

11-19 13:32:40 [[34mdebug[39m] [Core] [Config] 配置文件E:\项目\e项目_最版本QQ机器人\QQ\NapCat\config\napcat_3753213193.json加载 {"fileLog":false,"consoleLog":
true,"fileLogLevel":"debug","consoleLogLevel":"info","packetServer":""}
11-19 13:32:40 [[33mwarn[39m] [Core] [Packet] wsPacketClient 未配置服务器地址
11-19 13:32:40 [[32minfo[39m] [Core] [Packet] 自动选择 NativePacketClient 作为后端
11-19 13:32:40 [[32minfo[39m] [Notice] [OneBot11] [network] 配置加载
```

### OneBot 客户端运行日志

```shell
11-19 13:32:40 [[32minfo[39m] [Notice] [OneBot11] [network] 配置加载
```

**Comment by guobao97811** [comment]
是需要更改环境变量里面什么信息吗  或者有什么办法可以正常使用这个默认的配置

**Comment by MliKiowa** [comment]
使用webui配置 然后在ncd重启

**Comment by MliKiowa** [comment]
如果还有疑问可以进群询问

**Comment by MliKiowa** [comment]
> 是需要更改环境变量里面什么信息吗 或者有什么办法可以正常使用这个默认的配置

默认配置现在硬编码到napcat本体
