### ISSUE TITLE
[BUG] 新版本 NapCat 事件上报属性丢失

### ISSUE THREAD

**Issue by Murasame2333** [NapNeko/NapCatQQ#543]
### 系统版本

Windows 11

### QQNT 版本

9.9.16-29725

### NapCat 版本

4.1.6

### OneBot 客户端

nonebot 2

### 发生了什么?

在我更新napcat后，`message_sent.private.friend` 与 `message.private.friend` 事件中的 `target_id` 属性丢失，而在之前的版本中，这个属性是存在的。
OneBot 客户端报错：AttributeError: 'PrivateMessageSentEvent' object has no attribute 'target_id'；AttributeError: 'PrivateMessageEvent' object has no attribute 'target_id'。

### 如何复现

在 OneBot 客户端中获取这两个事件的 `target_id` 属性。

### 期望的结果?

`message_sent.private.friend` 与 `message.private.friend` 事件应该正确携带 `target_id` 属性。

**Comment by MliKiowa** [comment]
已修
