### ISSUE TITLE
[可能是BUG？] 图片缓存错误/缓存图片格式不支持

### ISSUE THREAD

**Issue by LinQi2333** [NapNeko/NapCatQQ#546]
### 系统版本

Ubuntu 2204LTS

### QQNT 版本

3.2.13-28788

### NapCat 版本

3.4.7

### OneBot 客户端

Nonebot 2.4.0

### 发生了什么?

发送文本+图片（使用CQ码+本地图片地址发送）时出现如下错误：
![246b2f4ee47c047c8d2e4848fecbe877](https://github.com/user-attachments/assets/5037b8ff-17d1-4a69-acd0-3a49b8a52269)

发送部分的代码如下：
![image](https://github.com/user-attachments/assets/dd4eaa2a-de70-4f78-bce4-a3aabdf6f69b)

代码中msg内容如下：
虚拟LIVE HAPPY BIRTHDAYライブ 一歌 2023 首场即将在北京时间2023年08月10日 23:00:00开始
[CQ:image,file=file:////home/ubuntu/bot/rin/rin/plugins/PrskHelper/resource/Sekai/data/live/img/vlentrance_00246.png]

在其他功能中也存在发送文本+图片（CQ码+本地图片地址）的消息，并没有报错。
本人刚刚接触这一领域内容，了解偏少，在反馈中可能各种各样的问题，如果需要补充信息或者该错误并非napcat造成，还请详细说明，非常感谢！

### 如何复现

发送消息时即出现问题

### 期望的结果?

正常发送文本+图片

**Comment by MliKiowa** [comment]
识别后缀名失败 图片格式不标准 最后你用专业工具查看文件头和文件格式

**Comment by LinQi2333** [comment]
自己查了一下查到问题了，谢谢，多有打扰了
