### ISSUE TITLE
使用旧版手机qq发送的图片，获取不到

### ISSUE THREAD

**Issue by fllesser** [NapNeko/NapCatQQ#547]
### 系统版本

debian 11

### QQNT 版本

3.2.13-29456

### NapCat 版本

4.1.11

### OneBot 客户端

nonebot2 2.4.0

### 发生了什么?

使用安卓8.9.15手机QQ发送的图片，拿不到

### 如何复现

使用安卓手机qq8.9.15发送图片
![Screenshot_20241120_113706_tech lolli toolbox_edit_122045053795438](https://github.com/user-attachments/assets/12295af8-691f-4ab2-86cc-fedc280e679d)
![Screenshot_20241120_113647_tech lolli toolbox](https://github.com/user-attachments/assets/9db28484-aa27-43a7-91b3-5435eeb425ac)

### 期望的结果?

获取到正确的图片链接

**Comment by MliKiowa** [comment]
进群测试
