### ISSUE TITLE
想请问下 是否接收到的是转账消息的接口 在哪里 怎么找不到呢

### ISSUE THREAD

**Issue by 1072394292** [NapNeko/NapCatQQ#549]
### 系统版本

win

### QQNT 版本

9

### NapCat 版本

1

### OneBot 客户端

1

### 发生了什么?

转账消息 和 普通消息 怎么甄别呢 没找到这个接口

### 如何复现

无需复现

### 期望的结果?

期望告知

**Comment by pk5ls20** [comment]
不会实现
