### ISSUE TITLE
[BUG] get_group_root_files 获取内容不完整

### ISSUE THREAD

**Issue by hello-mrShu** [NapNeko/NapCatQQ#557]
### 系统版本

macos 14.5

### QQNT 版本

6.9.56-28418

### NapCat 版本

4.1.8

### OneBot 客户端

不知道

### 发生了什么?

有个群56个文件夹，7份文档。
但是get_group_root_files只能获取到50个文件夹，是不是跟之前的群文件一样，没有做分页的原因？

### 如何复现

最新版本请求群根目录文件

### 期望的结果?

获取群根目录完成的文件夹和文件内容

**Comment by ASTWY** [comment]
我也遇到了相关的问题，获取群文件根目录下的文件只有一部分，大约1000个文件只返回了时间降序的前37个
