### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Suercx** [NapNeko/NapCatQQ#56]
### 系统版本

ubuntu 2204

### QQNT 版本

9.9.7

### NapCat 版本

1.5.0

### OneBot 客户端

v11

### 发生了什么?

无法运行

### 如何复现

. napcat.sh 

### 期望的结果?

. napcat.sh 

### NapCat 运行日志

```shell
. napcat.sh 
/opt/QQ/qq: error while loading shared libraries: libgtk-3.so.0: cannot open shared object file: No such file or directory
```

**Comment by MliKiowa** [comment]
安装libgtk库

**Comment by MliKiowa** [comment]
如果还有问题reopen
