### ISSUE TITLE
[BUG] get_cookies接口，获取domain=pd.qq.com时，响应时间长

### ISSUE THREAD

**Issue by woolsen** [NapNeko/NapCatQQ#562]
### 系统版本

Windows Server 2019

### QQNT 版本

9.9.16-29456

### NapCat 版本

4.1.6

### OneBot 客户端

直接调用http接口

### 发生了什么?

调用get_cookies接口，入参为domain=pd.qq.com，响应需要2分钟
![image](https://github.com/user-attachments/assets/3f55eba2-9d5e-4999-8974-77294f7c18e5)

### 如何复现

调用get_cookies接口，入参为domain=pd.qq.com

### 期望的结果?

正常情况：入参为qun.qq.com，响应时间240ms
![image](https://github.com/user-attachments/assets/51ab5386-469d-4273-b755-cc9d3d63531a)

**Comment by woolsen** [comment]
经验证，llonebot也存在该问题

**Comment by MliKiowa** [comment]
该域cookies获取缓慢主要与tx有关 后面会尝试使用其它方法获取优化

**Comment by MliKiowa** [comment]
现在暂不处理
