### ISSUE TITLE
[BUG]  send_like

### ISSUE THREAD

**Issue by xshaoze** [NapNeko/NapCatQQ#58]
### 系统版本

Windows 11

### QQNT 版本

9.9.10-24108 (64位)

### NapCat 版本

1.5.1

### OneBot 客户端

none

### 发生了什么?

使用http方式访问http://127.0.0.1:3000/send_like?user_id=xxx&times=10的时候发生
`{
    "status": "failed",
    "retcode": 400,
    "data": null,
    "message": "Key: times, Message: must be number",
    "wording": "Key: times, Message: must be number",
    "echo": null
}`

### 如何复现

使用http get请求http://127.0.0.1:3000/send_like?user_id=xxx&times=10

### 期望的结果?

把times传入数据尝试转成int类型，如果失败再报错

### NapCat 运行日志

```shell
2024-06-04 17:14:22 [DEBUG] xx(xxx) 
收到http请求 /send_like {"user_id":"xxx","times":"10"}
```

**Comment by MliKiowa** [comment]
建议使用post json

**Comment by MliKiowa** [comment]
这个想法可能后面会做 但是不是现在 如果有疑问再reopen

**Comment by xshaoze** [comment]
好吧
