### ISSUE TITLE
[BUG] 无法修改群聊名称

### ISSUE THREAD

**Issue by huankong233** [NapNeko/NapCatQQ#581]
### 系统版本

使用docker最新版

`mlikiowa/napcat-docker:latest@sha256:181f254342247cb063e0e0ed1d110bb6054ac9997e6388b3993f9344d50d1c9c`

宿主机: debian 12

### QQNT 版本

`mlikiowa/napcat-docker:latest@sha256:181f254342247cb063e0e0ed1d110bb6054ac9997e6388b3993f9344d50d1c9c`

### NapCat 版本

4.2.8

### OneBot 客户端

node-napcat-ts@0.4.1

### 发生了什么?

无法修改群聊名称为: `金价通知: 615.42`

### 如何复现

1. 使用websocket-server链接napcat
2. 发送 
``` json
{
  "action":"set_group_name",
  "params": { "group_id": 123, "group_name": "金价通知: 615.42" },
  "echo": "aaaaa"
}
```
3. 未生效，但是返回执行成功
![image](https://github.com/user-attachments/assets/a3b3ea93-6732-4e9c-8906-16f112dbfed6)

### 期望的结果?

正确修改群聊名称

**Comment by huankong233** [comment]
补充：

机器人已是管理员

![image](https://github.com/user-attachments/assets/873b4aec-9e55-464f-913e-1f9ab94cbe3f)

**Comment by Fahaxikiii** [comment]
> 补充：
> 
> 机器人已是管理员
> 
> ![image](https://private-user-images.githubusercontent.com/49610758/391209865-873b4aec-9e55-464f-913e-1f9ab94cbe3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MzgwNjUsIm5iZiI6MTczMjkzNzc2NSwicGF0aCI6Ii80OTYxMDc1OC8zOTEyMDk4NjUtODczYjRhZWMtOWU1NS00NjRmLTkxM2UtMWY5YWI5NGNiZTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDAzMzYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZWUwODc2Yzg4ZmZjMmQzNGIzZTAzMWEzZWM2ZWE3ZTQ5YzA0OTI2ZjQwM2E0NDgyMzBiNzgxODczMjJkYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fX_GbT6LGgR-hnrdzbkVGr4HvJ9yvHH9AJV2kG9GnRg)

你的group_id是123？

**Comment by huankong233** [comment]
> > 补充：
> > 机器人已是管理员
> > ![image](https://private-user-images.githubusercontent.com/49610758/391209865-873b4aec-9e55-464f-913e-1f9ab94cbe3f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5MzgwNjUsIm5iZiI6MTczMjkzNzc2NSwicGF0aCI6Ii80OTYxMDc1OC8zOTEyMDk4NjUtODczYjRhZWMtOWU1NS00NjRmLTkxM2UtMWY5YWI5NGNiZTNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDAzMzYwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1ZWUwODc2Yzg4ZmZjMmQzNGIzZTAzMWEzZWM2ZWE3ZTQ5YzA0OTI2ZjQwM2E0NDgyMzBiNzgxODczMjJkYWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fX_GbT6LGgR-hnrdzbkVGr4HvJ9yvHH9AJV2kG9GnRg)
> 
> 你的group_id是123？

脱敏()

![image](https://github.com/user-attachments/assets/722c3a2c-6042-47a1-997e-bc1403355952)

**Comment by huankong233** [comment]
经检查是我的遗老代码逻辑有问题，抱歉🥹

**Comment by Fahaxikiii** [comment]
> 经检查是我的遗老代码逻辑有问题，抱歉🥹

刚想回复你测了能用
![Screenshot_2024-11-30-12-48-52-173_com tencent mobileqq](https://github.com/user-attachments/assets/f6518d5f-3a40-4f2a-bac8-785bad6c548f)

**Comment by huankong233** [comment]
> > 经检查是我的遗老代码逻辑有问题，抱歉🥹
> 
> 刚想回复你测了能用 ![Screenshot_2024-11-30-12-48-52-173_com tencent mobileqq](https://private-user-images.githubusercontent.com/93320886/391212779-f6518d5f-3a40-4f2a-bac8-785bad6c548f.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI5NDI1NTIsIm5iZiI6MTczMjk0MjI1MiwicGF0aCI6Ii85MzMyMDg4Ni8zOTEyMTI3NzktZjY1MThkNWYtM2E0MC00ZjJhLWJhYzgtNzg1YmFkNmM1NDhmLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTMwVDA0NTA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MGE3Y2I3YTZmMGYxODhjZjY3MTI2MGExNzVjNzljNWZmODAxNmMxZTFjMWQwY2M4NmY1NjNmZjg5NGIyOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.hxvAbzzMlMzkpBeQ4C64da6AiNAVypzejJ9_jA7MLEM)

嗯嗯，抱歉
