### ISSUE TITLE
[功能建议]增加群通知里面的申请加群列表API

### ISSUE THREAD

**Issue by WJHXD1B** [NapNeko/NapCatQQ#592]
这样当Bot因一些特殊情况恢复后可以快速的处理加群请求

**Comment by MliKiowa** [comment]
具体描述是啥功能？

**Comment by MliKiowa** [comment]
![image](https://github.com/user-attachments/assets/18fd71eb-6d0a-4360-b0e6-027b97de196a)
https://apifox.com/apidoc/shared-c3bab595-b4a3-429b-a873-cbbe6b9a1f6a/226658660e0

**Comment by WJHXD1B** [comment]
> ![image](https://private-user-images.githubusercontent.com/61873808/391896018-18fd71eb-6d0a-4360-b0e6-027b97de196a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMzMyNTcsIm5iZiI6MTczMzIzMjk1NywicGF0aCI6Ii82MTg3MzgwOC8zOTE4OTYwMTgtMThmZDcxZWItNmQwYS00MzYwLWIwZTYtMDI3Yjk3ZGUxOTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEzMzU1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiNWRkOTkyNTg5Y2QzNDg5ZTk5ZTY3OGMzMzVmMDAyMjE4YjE1ZWJhNTg5ZjIxOWE3OTc4ZDY5M2Q1MjczMDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VRDkqWVYX0IMJ_w9Ale7ommKME19Bgi6k5byXID6-IA) https://apifox.com/apidoc/shared-c3bab595-b4a3-429b-a873-cbbe6b9a1f6a/226658660e0

使用`/get_group_system_msg`获取到申请加群人的`request_id`后,然后用`/set_group_add_request`并且flag使用刚才获取到的request_id时,虽返回成功,但申请人并没用加入群内
```
{
    "status": "ok",
    "retcode": 0,
    "data": null,
    "message": "",
    "wording": ""
}
```

**Comment by MliKiowa** [comment]
> request_id

request_id 不是flag 之后处理

**Comment by WJHXD1B** [comment]
> > request_id
> 
> request_id 不是flag 之后处理

谢谢，麻烦了
