### ISSUE TITLE
开启后插件后，QQ使用一段时间被下线。第一次登录后勾选了下次无需手机验证，但是再次登录的时候提示身份验证失效

### ISSUE THREAD

**Issue by JaychengLeo** [NapNeko/NapCatQQ#593]
### 系统版本

Windows10 专业版 22H2

### QQNT 版本

9.9.16-29927

### NapCat 版本

1.2.3

### OneBot 客户端

webui 1.0.0

### 发生了什么?

开启后QQ使用一段时间被下线，我勾选了下次无需手机验证，但是再次登录的时候提示身份验证失效。

### 如何复现

在LiteLoaderQQNT中开启NapcatQQ插件

### 期望的结果?

不会影响被强制离线

**Comment by MliKiowa** [comment]
建议切换账号

**Comment by JaychengLeo** [comment]
看了下LiteLoaderQQNT的issue，很多人遇到下线的问题，应该不是开启NapcatQQ插件的原因
