### ISSUE TITLE
[BUG] 未能成功获取群系统消息

### ISSUE THREAD

**Issue by WJHXD1B** [NapNeko/NapCatQQ#596]
### 系统版本

Windows 10 企业版 LTSC

### QQNT 版本

9.9.16-29927

### NapCat 版本

4.2.19

### OneBot 客户端

/

### 发生了什么?

使用`/get_group_system_msg`接口获取成功，但返回的并不是群系统消息
POST
http://127.0.0.1:5700/get_group_system_msg?group_id=18******
返回内容
```
{
    "status": "failed",
    "retcode": 200,
    "data": null,
    "message": "this.context.session.getProfileService(...).getUinByUid(...).then is not a function",
    "wording": "this.context.session.getProfileService(...).getUinByUid(...).then is not a function",
    "echo": null
}
```

### 如何复现

使用最新qq和nc然后获取`/get_group_system_msg`接口

### 期望的结果?

正常返回申请加群信息

**Comment by MliKiowa** [comment]
改错了一个地方 现在已经修复 下个版本 即4.2.21修复

**Comment by WJHXD1B** [comment]
> 改错了一个地方 现在已经修复 下个版本 即4.2.21修复

你好，请求和返回都正常了，但是请求时间为50秒，是我的问题还是...

**Comment by MliKiowa** [comment]
> > 改错了一个地方 现在已经修复 下个版本 即4.2.21修复
> 
> 你好，请求和返回都正常了，但是请求返回时间为50秒，是我的问题还是...

进群一下
