### ISSUE TITLE
如何获取群员列表

### ISSUE THREAD

**Issue by hdsnzsr** [NapNeko/NapCatQQ#599]
不知道咋获取群员列表，能教教吗

**Comment by yum-install-apt** [comment]
curl -o napcat.sh https://raw.githubusercontent.com/yum-install-apt/napcat-autoinstall/refs/heads/main/linux.sh && sudo bash napcat.sh

**Comment by MliKiowa** [comment]
> 不知道咋获取群员列表，能教教吗

调用action /get_group_member_list
带上 group_id 作为参数即可
