### ISSUE TITLE
[BUG] 收到好友请求消息上报中未找到 加好友请求 的request上报

### ISSUE THREAD

**Issue by sleepingzw** [NapNeko/NapCatQQ#60]
### 系统版本

Ubuntu 22.04

### QQNT 版本

linux3.2.8-23873

### NapCat 版本

1.5.2

### OneBot 客户端

应该不关键？

### 发生了什么?

在收到好友请求时 只收到了notice上报，log如下：
| ws 消息上报  {"time":1717825502,"self_id":93xxxx365,"post_type":"notice","notice_type":"friend_add","user_id":8xxx67641} 
没有找到对应的加好友请求的request上报 没有对应request的flag值没法处理加好友请求

### 如何复现

找人加一下好友（？）

### 期望的结果?

加个request上报（？）

### NapCat 运行日志

```shell
ws 消息上报  {"time":1717825502,"self_id":93xxxx365,"post_type":"notice","notice_type":"friend_add","user_id":8xxx67641}
```

**Comment by MliKiowa** [comment]
好的，下个版本修复

**Comment by MliKiowa** [comment]
不用flag

**Comment by MliKiowa** [comment]
已修复 https://github.com/NapNeko/NapCatQQ/actions/runs/9436129450

**Comment by MliKiowa** [comment]
可以尝试一下 如果有问题再reopen
