### ISSUE TITLE
natcap桌面版无法正确的保存配置文件了。

### ISSUE THREAD

**Issue by 1825679767** [NapNeko/NapCatQQ#602]
测试发现，新建的qq或者修改添加了上报地址，点击保存以后，配置文件里面没有相关信息，natcap也没有正确的上报。必须在webui里面设置以后才能生效。

**Comment by MliKiowa** [comment]
ncd属于社区产物 不在nc主体维护中

**Comment by 1825679767** [comment]
ncd比较好的就是能自动更新，然后可视化设置，其实可以采纳为主体的 真的很方便
