### ISSUE TITLE
[BUG] 合并转发消息多出nya~

### ISSUE THREAD

**Issue by JerryZRF** [NapNeko/NapCatQQ#607]
### 系统版本

macOS Monterey 12.7.6 (21H1320)

### QQNT 版本

6.9.61-29927

### NapCat 版本

v4.2.27

### OneBot 客户端

Python

### 发生了什么?

合并转发了几条真实消息，如`{"type": "node", "data": {"id":  XXX}`
其中包含回复也就是`[CQ:reply,id=XXXX]XXXXXXX`
然后消息前会出现nya~
Mac端(左侧时打开的合并转发消息, 右侧是被转发的聊天记录):
![a](https://github.com/user-attachments/assets/bdbd01b2-1e4d-4d40-890f-51db96d69dc1)

iPad端:
![b](https://github.com/user-attachments/assets/eeb6d067-9c34-4b38-9386-e01d305d041f)
iPad端还出现回复不能正常查看

Bot Mac端(人机合一):
![QQ_1733568348965](https://github.com/user-attachments/assets/cfeb8acb-20b7-44f6-aae2-450f0259e816)
看不了自己发的合并转发消息

### 如何复现

私聊的消息中中出现回复，并将其合并转发到私聊.
未测试群聊
怀疑是https://github.com/NapNeko/NapCatQQ/blob/4552d6970dc72ae9d6e17570b8cc6aed618593e6/src/core/packet/message/element.ts#L144
因为只有这一行出现了`nya~`

### 期望的结果?

正常转发合并转发消息

### NapCat 运行日志

```shell
12-07 18:48:26 [info] Aria | [Core] [Packet] 上传资源2个，失败0个
12-07 18:48:26 [info] Aria | 发送 -> 私聊 (XXX) [卡片消息]
```

**Comment by MliKiowa** [comment]
请尝试更新 并给出传递给napcat必复现的rawJson

**Comment by JerryZRF** [comment]
> 请尝试更新 并给出传递给napcat必复现的rawJson

![QQ_1733630862224](https://github.com/user-attachments/assets/e7c421ea-53a5-4775-9665-ff61a22da4dc)
Napcat是最新版

Python代码如下
```Python
    msgs = [
        2070639423,
        1873019061,
        792586611,
        914002178,
        691249951,
        1243502784,
        1470515459,
        95780162,
        1375447479,
        406599655,
        1966271811,
        1088521124,
    ]
    await bot.call_api(
        "send_private_forward_msg",
        params={
            "user_id": msg.sender.user_id,
            "messages": [{"type": "node", "data": {"id": msg}} for msg in msgs],
        },
    )
```
实际是转发任意非伪造即用message_id的都这样

**Comment by pk5ls20** [comment]
> 合并转发了几条真实消息，如{"type": "node", "data": {"id":  XXX}
其中包含回复也就是[CQ:reply,id=XXXX]XXXXXXX
然后消息前会出现nya~

已修复

> iPad端还出现回复不能正常查看

预期行为，后续会考虑改进

> Bot Mac端(人机合一):
看不了自己发的合并转发消息

预期行为，后续会考虑改进
