### ISSUE TITLE
[BUG] Napcat无法正常启动

### ISSUE THREAD

**Issue by CNlongY-Py** [NapNeko/NapCatQQ#609]
### 系统版本

Ubuntu 22.04.5 LTS

### QQNT 版本

3.2.13-29927

### NapCat 版本

NapCat V4.2.27

### OneBot 客户端

Re-SimpQ

### 发生了什么?

使用 napcat start qq号
正常启动后提示服务已启动
但是使用 napcat status 显示服务未启动
webui也无法连接，ws无法连接

(尝试过napcat remove ,shell更新新版本)

### 如何复现

napcat start xxx

napcat status

### 期望的结果?

webui正常访问，ws连接正常

### NapCat 运行日志

```shell
>> napcat start xxx

启动 napcat 服务中 QQ: xxx
服务已启动 (PID: 4020182)

>> napcat status
当前正在运行的服务有:
xxx 未运行

>> napcat log xxx
Traceback (most recent call last):
  File "/usr/local/bin/qq", line 5, in <module>
    from qqbot import QTerm
  File "/usr/local/lib/python3.10/dist-packages/qqbot/__init__.py", line 3, in <module>
    from .qqbotcls import QQBot, QQBotSlot, QQBotSched, RunBot, _bot
  File "/usr/local/lib/python3.10/dist-packages/qqbot/qqbotcls.py", line 20, in <module>
    from qqbot.qconf import QConf
  File "/usr/local/lib/python3.10/dist-packages/qqbot/qconf.py", line 198, in <module>
    from qqbot.utf8logger import SetLogLevel, INFO, RAWINPUT, PRINT, ERROR
  File "/usr/local/lib/python3.10/dist-packages/qqbot/utf8logger.py", line 10, in <module>
    from qqbot.common import PY3
  File "/usr/local/lib/python3.10/dist-packages/qqbot/common.py", line 184, in <module>
    import html.parser; htmlUnescape = html.parser.HTMLParser().unescape
AttributeError: 'HTMLParser' object has no attribute 'unescape'
    from .qqbotcls import QQBot, QQBotSlot, QQBotSched, RunBot, _bot
  File "/usr/local/lib/python3.10/dist-packages/qqbot/qqbotcls.py", line 20, in <module>
    from qqbot.qconf import QConf
  File "/usr/local/lib/python3.10/dist-packages/qqbot/qconf.py", line 198, in <module>
    from qqbot.utf8logger import SetLogLevel, INFO, RAWINPUT, PRINT, ERROR
  File "/usr/local/lib/python3.10/dist-packages/qqbot/utf8logger.py", line 10, in <module>
    from qqbot.common import PY3
  File "/usr/local/lib/python3.10/dist-packages/qqbot/common.py", line 184, in <module>
    import html.parser; htmlUnescape = html.parser.HTMLParser().unescape
AttributeError: 'HTMLParser' object has no attribute 'unescape'
```

### OneBot 客户端运行日志

```shell
2024-12-07 20:52:44[ERROR]<websocket>:[Errno 111] Connection refused - goodbye
```

**Comment by MliKiowa** [comment]
你应该尝试直接启动下 qq --no-sandbox

**Comment by CNlongY-Py** [comment]
仍然报错
Traceback (most recent call last):
  File "/usr/local/bin/qq", line 5, in <module>
    from qqbot import QTerm
  File "/usr/local/lib/python3.10/dist-packages/qqbot/__init__.py", line 3, in <module>
    from .qqbotcls import QQBot, QQBotSlot, QQBotSched, RunBot, _bot
  File "/usr/local/lib/python3.10/dist-packages/qqbot/qqbotcls.py", line 20, in <module>
    from qqbot.qconf import QConf
  File "/usr/local/lib/python3.10/dist-packages/qqbot/qconf.py", line 198, in <module>
    from qqbot.utf8logger import SetLogLevel, INFO, RAWINPUT, PRINT, ERROR
  File "/usr/local/lib/python3.10/dist-packages/qqbot/utf8logger.py", line 10, in <module>
    from qqbot.common import PY3
  File "/usr/local/lib/python3.10/dist-packages/qqbot/common.py", line 184, in <module>
    import html.parser; htmlUnescape = html.parser.HTMLParser().unescape
AttributeError: 'HTMLParser' object has no attribute 'unescape'

**Comment by MliKiowa** [comment]
> 仍然报错 Traceback (most recent call last): File "/usr/local/bin/qq", line 5, in from qqbot import QTerm File "/usr/local/lib/python3.10/dist-packages/qqbot/**init**.py", line 3, in from .qqbotcls import QQBot, QQBotSlot, QQBotSched, RunBot, _bot File "/usr/local/lib/python3.10/dist-packages/qqbot/qqbotcls.py", line 20, in from qqbot.qconf import QConf File "/usr/local/lib/python3.10/dist-packages/qqbot/qconf.py", line 198, in from qqbot.utf8logger import SetLogLevel, INFO, RAWINPUT, PRINT, ERROR File "/usr/local/lib/python3.10/dist-packages/qqbot/utf8logger.py", line 10, in from qqbot.common import PY3 File "/usr/local/lib/python3.10/dist-packages/qqbot/common.py", line 184, in import html.parser; htmlUnescape = html.parser.HTMLParser().unescape AttributeError: 'HTMLParser' object has no attribute 'unescape'

进入官方群 来进行远程调试 感觉是你的问题

**Comment by MliKiowa** [comment]
> 仍然报错 Traceback (most recent call last): File "/usr/local/bin/qq", line 5, in from qqbot import QTerm File "/usr/local/lib/python3.10/dist-packages/qqbot/**init**.py", line 3, in from .qqbotcls import QQBot, QQBotSlot, QQBotSched, RunBot, _bot File "/usr/local/lib/python3.10/dist-packages/qqbot/qqbotcls.py", line 20, in from qqbot.qconf import QConf File "/usr/local/lib/python3.10/dist-packages/qqbot/qconf.py", line 198, in from qqbot.utf8logger import SetLogLevel, INFO, RAWINPUT, PRINT, ERROR File "/usr/local/lib/python3.10/dist-packages/qqbot/utf8logger.py", line 10, in from qqbot.common import PY3 File "/usr/local/lib/python3.10/dist-packages/qqbot/common.py", line 184, in import html.parser; htmlUnescape = html.parser.HTMLParser().unescape AttributeError: 'HTMLParser' object has no attribute 'unescape'

进入官方群 来进行远程调试 感觉是你的问题

**Comment by MliKiowa** [comment]
> 仍然报错 Traceback (most recent call last): File "/usr/local/bin/qq", line 5, in from qqbot import QTerm File "/usr/local/lib/python3.10/dist-packages/qqbot/**init**.py", line 3, in from .qqbotcls import QQBot, QQBotSlot, QQBotSched, RunBot, _bot File "/usr/local/lib/python3.10/dist-packages/qqbot/qqbotcls.py", line 20, in from qqbot.qconf import QConf File "/usr/local/lib/python3.10/dist-packages/qqbot/qconf.py", line 198, in from qqbot.utf8logger import SetLogLevel, INFO, RAWINPUT, PRINT, ERROR File "/usr/local/lib/python3.10/dist-packages/qqbot/utf8logger.py", line 10, in from qqbot.common import PY3 File "/usr/local/lib/python3.10/dist-packages/qqbot/common.py", line 184, in import html.parser; htmlUnescape = html.parser.HTMLParser().unescape AttributeError: 'HTMLParser' object has no attribute 'unescape'

readme有群号

**Comment by CNlongY-Py** [comment]
好的

**Comment by MliKiowa** [comment]
819085771 如果群内无法解决再决定此Issue再次开启
