### ISSUE TITLE
[BUG] 群成员缓存无法刷新

### ISSUE THREAD

**Issue by SaarChaffee** [NapNeko/NapCatQQ#610]
### 系统版本

Linux 5.4.0-200-generic 和 6.1.0-28-amd64

### QQNT 版本

docker

### NapCat 版本

v4.2.28

### OneBot 客户端

koishi-plugin-adapter-onebot@6.7.2

### 发生了什么?

调用 getGroupMemberInfo 同时设置 no_cache 为 true，依然无法刷新缓存，可以拿到已经不在群里的人的信息

### 如何复现

1. 先调 getGroupMemberInfo 拿一次群成员信息（因为没特别注意有没有别的因素，这一步是猜的）
2. 把人踢了
3. 再拿一次这个人的信息

### 期望的结果?

不应该返回这个人的信息

### NapCat 运行日志

```shell
[OneBot] [WebSocket Client] 收到正向Websocket消息 {"action":"get_group_member_info","params":{"group_id":114514,"user_id":1919810,"no_cache":true},"echo":50}
```

### OneBot 客户端运行日志

```shell
onebot send { action: 'get_group_member_info', params: { group_id: 114514, user_id: 1919810, no_cache: true }, echo: 50 }
onebot received { group_id: 114514, user_id: 1919810, nickname: '123456', card: '', sex: 'unknown', age: 0, area: '', level: '3', qq_level: 0, join_time: 1733732361, last_sent_time: 1733732361, title_expire_time: 0, unfriendly: false, card_changeable: true, is_robot: false, shut_up_timestamp: 0, role: 'member', title: '' }
```

**Comment by SaarChaffee** [comment]
> 你试试间隔10s 再取看看

我现在的间隔应该是1分钟调一次

**Comment by SaarChaffee** [comment]
尝试了一下另一个和群员相关的 get_group_member_list。
这个就完全正常，即使没设 no_cache 也能马上响应变化。

**Comment by MliKiowa** [comment]
那你应该使用get_group_member_list替代

**Comment by MliKiowa** [comment]
> 尝试了一下另一个和群员相关的 get_group_member_list。 这个就完全正常，即使没设 no_cache 也能马上响应变化。

我在想如果要拉取列表应该用list确定人数 getGroupMemberInfo 的任务是尽可能取到数据

**Comment by SaarChaffee** [comment]
> > 尝试了一下另一个和群员相关的 get_group_member_list。 这个就完全正常，即使没设 no_cache 也能马上响应变化。
> 
> 我在想如果要拉取列表应该用list确定人数 getGroupMemberInfo 的任务是尽可能取到数据

人数有 group_info 拿，这个应该算 group_info 的职责

**Comment by MliKiowa** [comment]
https://github.com/NapNeko/NapCatQQ/actions/runs/12310775365 你可以尝试这个包

**Comment by SaarChaffee** [comment]
> https://github.com/NapNeko/NapCatQQ/actions/runs/12310775365 你可以尝试这个包

ok 修复了，感谢
