### ISSUE TITLE
[Feat]  webui未登录跳转回主界面

### ISSUE THREAD

**Issue by bobandbrony** [NapNeko/NapCatQQ#611]
### 系统版本

乌班图22.04

### QQNT 版本

忘了（应该是最新版，今天装的 ）

### NapCat 版本

4.2.28

### OneBot 客户端

无

### 发生了什么?

不需要token就能进配置界面

### 如何复现

直接访问http://ip:port/webui/#/dashboard就能直接进配置界面，不需要token

### 期望的结果?

新浏览器应该输入token才能访问

**Comment by MapleLeaf2007** [comment]
那您可以更改配置嘛

**Comment by bobandbrony** [comment]
> 那您可以更改配置嘛

啊？怎么改，我是小白，会的不多（

**Comment by MapleLeaf2007** [comment]
进去是空白的，配置不了东西，内置没加拦截罢了

**Comment by sisi0318** [comment]
进去是无法配置的 会进行token鉴权

**Comment by bobandbrony** [comment]
> 进去是空白的，配置不了东西，内置没加拦截罢了

az，刚刚试了确实是这样，但这也是个bug。如果开发者在服务端重装了nap，而网页没关，只是刷新界面，这时修改配置会反复提示“配置保存失败”，这时候开发者也会搞不明白提交议题的，建议修复

**Comment by pk5ls20** [comment]
#616
