### ISSUE TITLE
[BUG] 无法在mcsmanager中打开

### ISSUE THREAD

**Issue by bobandbrony** [NapNeko/NapCatQQ#612]
### 系统版本

乌班图22.04

### QQNT 版本

忘了（应该是最新版，今天装的 ）

### NapCat 版本

4.2.28

### OneBot 客户端

无

### 发生了什么?

报错Trace/breakpoint trap (core dumped)

### 如何复现

尝试在mcsmanager打开napcat，运行指令xvfb-run -a qq --no-sandbox
![image](https://github.com/user-attachments/assets/9faf12ee-38de-46ca-9eb3-a8b2b99b7578)

### 期望的结果?

正常运行

**Comment by MliKiowa** [comment]
docker 或者 你尝试ssh shell启动

**Comment by bobandbrony** [comment]
> docker 或者 你尝试ssh shell启动

我也不清楚怎么以ssh shell启动，启动命令我填的bash

**Comment by bobandbrony** [comment]
> 或许你该试试sudo

已解决，谢谢！
