### ISSUE TITLE
现在还不支持onebot-11请求事件的快速操作吗

### ISSUE THREAD

**Issue by wzgbwxl** [NapNeko/NapCatQQ#619]
![QQ20241211-155341](https://github.com/user-attachments/assets/6e5518cb-093a-49f5-ba63-fa6a3b696f99)
![QQ20241211-155904](https://github.com/user-attachments/assets/e8d4d315-e53c-48d5-bb67-03198a6cd57b)
测试消息事件支持，请求事件不支持

**Comment by MliKiowa** [comment]
是支持的

**Comment by MliKiowa** [comment]
测试是可以的无法复现 如果仍然有问题可以前往官方群询问并现场调试
