### ISSUE TITLE
[Feat] webui多账号管理

### ISSUE THREAD

**Issue by bobandbrony** [NapNeko/NapCatQQ#622]
### 系统版本

乌班图22.04

### QQNT 版本

忘了（应该是最新版 ）

### NapCat 版本

4.2.28

### OneBot 客户端

无

### 发生了什么?

每个账号都要单独打开网页进行管理，较为麻烦

### 如何复现

多开账号，进行web管理

### 期望的结果?

希望能在同一网页进行多账号管理，就像mcsmanager那样（一个前端可以连多个后端）

**Comment by MliKiowa** [comment]
抱歉暂时没有这方面实现的想法 因为后端和vue前端资源都由独立的napcat驱动
