### ISSUE TITLE
[BUG] 无法正确上报拉群邀请事件

### ISSUE THREAD

**Issue by Elan114514** [NapNeko/NapCatQQ#637]
### 系统版本

 Windows Server 2019

### QQNT 版本

9.9.16-29927

### NapCat 版本

4.2.37

### OneBot 客户端

Nonebot2 2.3.2

### 发生了什么?

当接收到拉群邀请时，拉群邀请会被上报为一个空消息和一个json，不会出现正常的request事件

### 如何复现

1.向bot发送一个拉群邀请
2.bot接收到邀请卡片，将其上报为一个空消息和一段json，但并未出现request事件

### 期望的结果?

正常上报拉群事件

### OneBot 客户端运行日志

```shell
12-17 21:50:24 [SUCCESS] nonebot | OneBot V11 *** | [message.private.friend]: Message 2039305722 from *** ''
12-17 21:50:24 [SUCCESS] nonebot | OneBot V11 *** | [message.private.friend]: Message 1524254158 from *** '[json:data={"app":"com.tencent.qun.invite","config":{"autosize":0,"ctime":1734...]'
```

**Comment by airdm** [comment]
同样问题,升级到最新版本后收不到加群的事件.

**Comment by airdm** [comment]
同样问题,升级到最新版本后收不到被邀请进群的事件.

**Comment by MliKiowa** [comment]
已定位问题 疑似tx乱改 下个版本修复
