### ISSUE TITLE
[BUG] 1.5.4版私聊超时

### ISSUE THREAD

**Issue by xiaobaozi233** [NapNeko/NapCatQQ#64]
### 系统版本

win11

### QQNT 版本

1

### NapCat 版本

1.5.4

### OneBot 客户端

1

### 发生了什么?

直接拿1.5.4版覆盖了1.4.2版本后发送http和反向websocket私聊消息全部超时，发送群聊消息正常。
回退了1.4.2版本私聊恢复正常

### 如何复现

1

### 期望的结果?

私聊修复。更新需要完全纯净新装吗？

**Comment by dev-soragoto** [comment]
我这里也是相同的问题，我是使用docker部署的，看起来应该是有其他问题

**Comment by dev-soragoto** [comment]
> 已经修复 v1.5.5

这也太快了!
