### ISSUE TITLE
[BUG] 关于NapCatQQ 专属API的问题

### ISSUE THREAD

**Issue by bingliran** [NapNeko/NapCatQQ#640]
### 系统版本

Docker

### QQNT 版本

未知

### NapCat 版本

NapCat.Core Version: 4.2.28

### OneBot 客户端

非任何主流客户端，按照apifox文档调用

### 发生了什么?

  最近对接了一下NapCatQQ的API做了一些测试，下面有些接口有些问题(群号之类的已经用*隐掉)
        //this.setGroupSign("*") 提示不支持
        //println(this.arkSharePeerUser("*"))
        //println(this.arkShareGroup("*"))
        //println(this.getRobotUinRange())
        //println(this.setOnlineStatus(BotOnlineStatusEnum.EMO))
        //println(this.getFriendsWithCategory())
        //println(this.setQQAvatar(""))
        //println(this.getFileInfo("")) 未测试
        //val message = SendMessage.builder("a").build()
        //this.sendGroup(message, sourceId = "718044489")
        //println(this.translateEn2zh("text")) 会卡死
        //this.setMsgEmojiLike(message.id,"0")
        //this.markPrivateMsgAsRead("*")
        //this.markGroupMsgAsRead("*")
        //println(this.getFriendMsgHistory("*",0))
        //println(this.createCollection("aaa","asdasdsad"))
        //println(this.getCollectionList()) 提示不支持
        //println(this.setSelfSignature("测试"))
        //println(this.getRecentContact())
        //println(this.markAllAsRead())
        //println(this.getProfileLike()) 错误 Cannot read properties of undefined (reading 'voteInfo')
        //println(this.fetchCustomFace())
        //println(this.getGroupInfoEx("*"))
        //println(this.getGroupIgnoreAddRequest())
        //println(this.delGroupNotice("*","")) 无法测试 没有能获取公告列表的api
        //println(this.fetchUserProfileLike("*")) 错误 Cannot read properties of undefined (reading 'toString')
        //println(this.ncGetPacketStatus())
        //println(this.ncGetUserStatus("*"))
        //println(this.ncGetRKey())
        //println(this.getGroupShutList("*")) 出现 ListenerName:NodeIKernelGroupListener/onShutUpMemberListChanged timeout

### 如何复现

/

### 期望的结果?

/

### NapCat 运行日志

```shell
关于这些异常docker中的NapCat并没有异常提示
```

**Comment by MliKiowa** [comment]
大部分接口是无问题的 translateEn2zh 可能有问题
getGroupShutList是由于当前实现问题 没有禁言人员情况会error
