### ISSUE TITLE
[BUG] 使用get_msg获取被撤回的群消息，消息内容始终为空

### ISSUE THREAD

**Issue by zanjie1999** [NapNeko/NapCatQQ#641]
### 系统版本

Linux Docker

### QQNT 版本

docker logs中没有体现

### NapCat 版本

4.2.37

### OneBot 客户端

aiocqhttp

### 发生了什么?

使用group_recall的回调获取到的message_id，调用get_msg获取消息内容，能够获取到发送人信息，但消息内容message始终为空字符串 

### 如何复现

撤回一条消息，group_recall的回调获取到message_id，使用get_msg传递message_id来获取消息内容

### 期望的结果?

返回的message应为撤回的消息的内容

### NapCat 运行日志

```shell
撤回时不会输出日志
```

### OneBot 客户端运行日志

```shell
群消息撤回时收到的内容：
 {'time': 1734504323, 'self_id': bot的qq号, 'post_type': 'notice', 'group_id': 群号, 'user_id': 撤回消息的人qq号, 'notice_type': 'group_recall', 'operator_id': 撤回消息的人qq号, 'message_id': 消息id}

get_msg返回内容：
 {'self_id': bo't, 'user_id': 撤回消息的人qq号, 'time': 1734504320, 'message_id': 消息id, 'message_seq': 消息id, 'real_id': 消息id, 'message_type': 'group', 'sender': {'user_id': 撤回消息的人qq, '
nickname': '昵称', 'card': '', 'role': 'owner'}, 'raw_message': '', 'font': 14, 'sub_type': 'normal', 'message': '', 'message_format': 'string', 'post_type': 'message', 'group_id': 群号}
```

**Comment by zanjie1999** [comment]
因为之前用的大概是3.x的版本是可以获取到的，目前用OrderedDict在内存维护一份消息记录解决了这个问题，不管是不是bug修不修都行，如果你就是这么设计的那你就close掉

**Comment by MliKiowa** [comment]
首先无数据库设计 后期考虑重新实现这部分

**Comment by ColorfulGhost** [comment]
V4.3.5 同样问题 ，期待作者后续版本实现 获取以撤回消息内容。

**Comment by synodriver** [comment]
解决方案：自己存mongodb，然后mock掉get_msg请求，这已经[写好了](https://github.com/synodriver/db4napcat)
