### ISSUE TITLE
[BUG] 连接1分钟自动断开

### ISSUE THREAD

**Issue by kumu7y** [NapNeko/NapCatQQ#642]
### 系统版本

Armbian OS 24.8.0 Jammy

### QQNT 版本

不知道

### NapCat 版本

4.2.37

### OneBot 客户端

MCbot

### 发生了什么?

我这边对接完mcbot的mod发现，它会在一分钟自动
![PixPin_2024-12-18_18-30-24](https://github.com/user-attachments/assets/4faa329f-865a-4587-ba2b-4b8c97a9ae6d)
![PixPin_2024-12-18_18-30-35](https://github.com/user-attachments/assets/0b29bc94-9bcf-478c-95c3-7f869c3a41ed)
断链，但是Windows的LiteLoaderQQNT插件NapCatQQ对接就不会

然后我也用python写了个ws连接测试，发现并不会主动断开

![PixPin_2024-12-18_18-30-50](https://github.com/user-attachments/assets/e8959d52-ebff-46c6-b0a2-0218b115e43f)

### 如何复现

启动minecraft客户端，ws连接成功。
一分钟就会断开连接，抓包发现是服务端主动断开。
但是使用Windows的LiteLoaderQQNT插件NapCatQQ对接就不会，Linux dockers部署对接就会

### 期望的结果?

正常保持ws连接

**Comment by MliKiowa** [comment]
napcat实现无问题 排查自身问题

**Comment by kumu7y** [comment]
![1a8365b1524fb060963048c47add065a](https://github.com/user-attachments/assets/c7a0be29-387f-467c-ac1b-933b32dd4a6c)
和群友讨论，好像[Java-WebSocket](https://github.com/TooTallNate/Java-WebSocket)禁止丢失的连接检测这里的问题，可以尝试禁用
