### ISSUE TITLE
[BUG] 不定时崩溃

### ISSUE THREAD

**Issue by shoucandanghehe** [NapNeko/NapCatQQ#65]
### 系统版本

Ubuntu 22.04.4 LTS

### QQNT 版本

3.2.7-23361

### NapCat 版本

1.5.3

### OneBot 客户端

nonebot2 2.3.1

### 发生了什么?

崩溃

### 如何复现

1. 运行napcat
2. 等待
3. boom

### 期望的结果?

不崩溃（

### NapCat 运行日志

```shell
[BuglyManager.cpp][fatalHandler][165]_fatal_handler signo:  13
[BuglyManager.cpp][printBacktrace][121]backtrace n_ptrs: 5
[BuglyManager.cpp][printBacktrace][126]backtrace_symbols ret: 0x20e4026ef000
[BuglyManager.cpp][printBacktrace][130]++++++++ FATAL ERROR(signal: 13) +++++++
[BuglyManager.cpp][printBacktrace][133]+++ trace: /lib/x86_64-linux-gnu/libc.so.6(+0x42520) [0x7f9128a52520]
[BuglyManager.cpp][printBacktrace][133]+++ trace: /lib/x86_64-linux-gnu/libc.so.6(writev+0x4d) [0x7f9128b2aa8d]
[BuglyManager.cpp][printBacktrace][133]+++ trace: /opt/QQ/qq(+0x248cb09) [0x562c049ceb09]
[BuglyManager.cpp][printBacktrace][136]+++++++++++++++++++++++++++
```

**Comment by shoucandanghehe** [comment]
> 最后操作是什么

收到消息

**Comment by shoucandanghehe** [comment]
![image](https://github.com/NapNeko/NapCatQQ/assets/51957264/b5f0b4d4-becb-48e0-a14b-218b9087d450)

**Comment by MliKiowa** [comment]
试试更新版本到最新版

**Comment by MliKiowa** [comment]
如果仍然有问题请再reopen

**Comment by KirbyScarlet** [comment]
QQ3.2.15 ubuntu24.04 已更新最新内核，也出现了随机崩溃，报错日志和楼主的一样，就很怪啊~
我这儿挂了两个号，都是几乎前后脚同时崩，好几次了
![Screenshot from 2024-12-18 09-42-46](https://github.com/user-attachments/assets/d167013e-c899-482e-88e9-878338e89864)

**Comment by KirbyScarlet** [comment]
一个可能的原因，只要不开着设置页面，好像就不崩溃。
问题复现比较困难，但用隔壁的llonebot也有崩溃问题，那大概不是插件本身的问题了。
