### ISSUE TITLE
[BUG] node_custom中content如果是reply，会显示```原消息已过期```和```nya~```

### ISSUE THREAD

**Issue by yp05327** [NapNeko/NapCatQQ#666]
### 系统版本

docker

### QQNT 版本

未知（使用的是mlikiowa/napcat-docker:v4.2.42中内置的QQNT）

### NapCat 版本

4.2.42

### OneBot 客户端

2.4.6

### 发生了什么?

![image](https://github.com/user-attachments/assets/ca9a5866-d638-4d2b-a3a7-71ac74a4ae9a)

右侧是用户发送的消息
左侧是由以下代码生成的消息
（以上是私聊bot时候的截图，群内也是同样的结果）

``` python
from nonebot.adapters.onebot.v11 import MessageSegment as OneBotMessageSegment
......
await matcher.finish(
    [
        OneBotMessageSegment.node_custom(
            user_id=event.sender.user_id,
            nickname=sender_name,
            content=[
                OneBotMessageSegment.reply(event.reply.message_id),
                OneBotMessageSegment.text(sender_msg),
            ],
        ),
        OneBotMessageSegment.node_custom(user_id=bot.self_id, nickname=nickname, content=resp),
    ]
)
```

理论上来说不需要text，只需要一个reply应该就好了。怀疑可能是协议端出的问题，所以在这里开个issue。

### 如何复现

1. 随便发送一条消息A
2. 引用消息A，并在回复中随意输入一些内容
3. 查看bot生成的消息

### 期望的结果?

左侧的内容应该与右侧一致

### NapCat 运行日志

```shell
没有报错日志
```

### OneBot 客户端运行日志

```shell
没有报错日志
```

**Comment by yp05327** [comment]
Update:
如果使用以下代码：
``` python
await matcher.finish(
    [
        OneBotMessageSegment.node(event.message_id), # 修改这里
        OneBotMessageSegment.node_custom(user_id=bot.self_id, nickname=nickname, content=resp),
    ]
)
```
回复的内容能正常显示，但是reply部分会显示`原消息已过期`
![image](https://github.com/user-attachments/assets/b994f03d-09cf-4679-84b7-877a43ad9319)

**Comment by pk5ls20** [comment]
回复消息显示已过期是预期行为

**Comment by yp05327** [comment]
如果你直接右键这个消息，多选，然后进行合并转发是可以做到左右一致的：
![image](https://github.com/user-attachments/assets/3b0c304a-93dc-4f33-8852-88285b17216d)
难道是需要使用其他方法来构建消息才能实现？

**Comment by pk5ls20** [comment]
理论上是可以的，但我懒得实现了，找时间写一下 (ref: #607)

**Comment by pk5ls20** [comment]
下次重构该部分的时候会修复
