### ISSUE TITLE
[BUG] friend_poke 和 group_poke 调用失败

### ISSUE THREAD

**Issue by lyw182** [NapNeko/NapCatQQ#668]
### 系统版本

ArchLinux linux-6.12.7-zen

### QQNT 版本

3.2.13-29927

### NapCat 版本

4.2.42

### OneBot 客户端

reqable

### 发生了什么?

用reqable调用friend_poke和group_poke时，响应正常但没有戳一戳事件
![image](https://github.com/user-attachments/assets/00219458-9724-4625-a8fc-0198140eaf7f)

### 如何复现

调用friend_poke和group_poke接口

### 期望的结果?

正常实现戳一戳
![image](https://github.com/user-attachments/assets/e964aebc-91b6-4f2e-9368-8862918c5a2d)

**Comment by MliKiowa** [comment]
![image](https://github.com/user-attachments/assets/af98539a-8953-4728-96d2-6e4f926f5a6e)
无法复现 尝试重启 如果有更多问题可在开发群At我
