### ISSUE TITLE
[BUG] 快速登录错误: 登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。

### ISSUE THREAD

**Issue by airdm** [NapNeko/NapCatQQ#68]
### 系统版本

Windows 10

### QQNT 版本

QQ_9.9.11_240606_x64_01

### NapCat 版本

1.5.5

### OneBot 客户端

没有

### 发生了什么?

无法登录 启动NCQQ提示 快速登录错误: 登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。
用NTQQ登录正常

### 如何复现

1.启动
2.提示 快速登录错误: 登录失败，请前往QQ官网im.qq.com下载最新版QQ后重试，或通过问题反馈与我们联系。
3.再次启动
4.变成扫描二维码登录

### 期望的结果?

可以正常登录

**Comment by MliKiowa** [comment]
https://github.com/NapNeko/NapCatQQ/actions/runs/9513286498

**Comment by airdm** [comment]
我得也是 用二维码扫码登录后 控制台会提示 "登录失败 1 "

**Comment by MliKiowa** [comment]
使用1.5.6

**Comment by MliKiowa** [comment]
> QQ更新到指定版本，扫码登录后控制台会出现：登录失败

使用1.5.6版本 1.5.5暴毙了
