### ISSUE TITLE
[BUG] 发生错误 发送超时

### ISSUE THREAD

**Issue by airdm** [NapNeko/NapCatQQ#69]
### 系统版本

Windows 10

### QQNT 版本

QQ_9.9.11_240606_x64_01

### NapCat 版本

1.5.5

### OneBot 客户端

没有

### 发生了什么?

框架运行一段时间后 bot发送任何消息都会提示 发生错误 发送超时 重启框架后恢复,隔一段时间后又会如此循环.

### 如何复现

1.登录
2.过一段时间后  bot发送任何消息都会提示 发生错误 发送超时
3.重启框架
4.恢复正常
5.过一段时间后  bot发送任何消息都会提示 发生错误 发送超时 

### 期望的结果?

崩溃闪退问题也还是会出现.希望修复这个问题顺便修复崩溃闪退的问题

**Comment by MliKiowa** [comment]
请给出崩溃前最后调用的接口 和相关日志

**Comment by airdm** [comment]
> 请给出崩溃前最后调用的接口 和相关日志

它闪退了 直接进程都消失了,怎么样才能给你保留日志看

**Comment by MliKiowa** [comment]
log文件夹 和 ontbot调用侧 
如果闪退消失窗口 请先新建终端再执行cd到nc执行 bat启动

**Comment by airdm** [comment]
> bat启动

我用的就是bat启动 也还是会闪退消失 还有什么办法吗

**Comment by MliKiowa** [comment]
单独新建终端 执行命令cd到目录 然后启动bat 而不是双击 启动
