### ISSUE TITLE
[BUG] 视频消息上报错误 constructMessage error:  {}

### ISSUE THREAD

**Issue by smloli** [NapNeko/NapCatQQ#70]
### 系统版本

debian11

### QQNT 版本

3.2.7_240428

### NapCat 版本

1.5.7

### OneBot 客户端

无

### 发生了什么?

视频消息上报错误

### 如何复现

发送视频

### 期望的结果?

视频消息正常上报

### NapCat 运行日志

```shell
2024-06-14 21:33:13 [ERROR] xxx | constructMessage error:  {}
```

**Comment by smloli** [comment]
自己恢复正常了

**Comment by Starrain08** [comment]
> 自己恢复正常了

这个不是视频上报错误，这个是一起听造成的

**Comment by smloli** [comment]
> > 自己恢复正常了
> 
> 这个不是视频上报错误，这个是一起听造成的
一起听是什么，我没有开这个呀

**Comment by MliKiowa** [comment]
![image](https://github.com/NapNeko/NapCatQQ/assets/61873808/979c64ed-3a2d-47f9-8c16-fc2776569b97)
无法复现 之后如果还有其他人反馈 再进行修复
