### ISSUE TITLE
是否有考虑适配go-cqhttp中图片的subType？

### ISSUE THREAD

**Issue by Monody-S** [NapNeko/NapCatQQ#71]
# 什么是SubType？
go-cqhttp的图片中，有一个“subType”参数，表示图片子类型, 只出现在群聊。
![_R7NHRD8K)8Y_2)9$NNFYA2](https://github.com/NapNeko/NapCatQQ/assets/96714098/5db7c6ca-c657-40c1-9cea-4e7b363a0702)
![~7ED IJ9R}3)}U%A%} QJSY](https://github.com/NapNeko/NapCatQQ/assets/96714098/5c186920-391d-4e92-9c7c-51579485cdb8)

# 为什么需要SubType？
我想让我的Bot自动收集些表情包，同时我想尽可能的减少诸如游戏截图之类的图片，go-cqhttp的subType有效的帮我解决了这一问题
其subType为1时，便表示为“表情包, 在客户端会被分类到表情包图片并缩放显示”

**Comment by MliKiowa** [comment]
考虑加入 但是我记得商城表情上报和普通图片还有其它区别的 你连上ws看看区别

**Comment by Monody-S** [comment]
> 考虑加入 但是我记得商城表情上报和普通图片还有其它区别的 你连上ws看看区别

可能你有点误解我的意思，我是指的“收藏表情”与“普通图片”，而不是“商城表情”💦
因为“收藏表情”是群友们自己添加后发送的，这类图片更符合我这里的需求

**Comment by MliKiowa** [comment]
好的

**Comment by MliKiowa** [comment]
下个版本适配
