### ISSUE TITLE
[BUG?] napcat上传群文件后会在ntqq数据目录下多出来一份原文件

### ISSUE THREAD

**Issue by iona-s** [NapNeko/NapCatQQ#73]
### 系统版本

windows server 2022 datacenter 21H2

### QQNT 版本

9.9.11-24568

### NapCat 版本

1.5.7

### OneBot 客户端

nonebot2 onebotv11

### 发生了什么?

napcat在上传文件后（go-cqhttp的upload_group_file接口）
会在windows下默认为~\Documents\Tencent Files\qid\nt_qq\nt_data\File\Ori的路径中多出来一份原文件
不太清楚是napcat的问题还是ntqq的特性

### 如何复现

在使用nonebot2插件elf-rss向群聊里上传视频，最近发现服务器存储突然爆了才注意到这个问题

### 期望的结果?

在上传完文件后清除ntqq目录下多出来的文件

**Comment by MliKiowa** [comment]
是bug 之后版本将进行处理

**Comment by iona-s** [comment]
emm最近没注意，今天清理服务器磁盘的时候注意到好像又有这个问题了，最老的文件是在7月28号左右

**Comment by iona-s** [comment]
还有同样是在windows环境下~\Documents\Tencent Files\NapCat\temp底下也产生了不少文件，napcat可否进行自带的定时清理呢

**Comment by iona-s** [comment]
@MliKiowa 
尝试了下能稳定复现
qq版本是win9.9.16.29271
napcat v3.6.8
其余同上
