### ISSUE TITLE
windows平台建议支持32位QQ

### ISSUE THREAD

**Issue by cclife520** [NapNeko/NapCatQQ#74]
现在貌似不支持32位QQ，其实主要支持32位比较合理，32位跟64位的区别就是内存使用很多时候就是翻倍的，32位本质上就能减少内存使用，而且通用性也更好，希望能考虑考虑

**Comment by MliKiowa** [comment]
好的 下个版本会尝试的

**Comment by MliKiowa** [comment]
尝试 https://github.com/NapNeko/NapCatQQ/actions/runs/9540825861
