### ISSUE TITLE
[BUG] 已退出的群聊，使用获取群聊list的命令，返回的群list中含有已退出的群

### ISSUE THREAD

**Issue by nanmuye** [NapNeko/NapCatQQ#80]
### 系统版本

linux

### QQNT 版本

9.9.11-24568

### NapCat 版本

1.6.0

### OneBot 客户端

hoshino(nonebot=1.8.0

### 发生了什么?

获取bot在的群聊list中包含了已经退出的群聊，我会向list中的某些群发送消息，最后导致发送失败
具体的代码的这部分发送失败会触发退群命令，且没有触发报错，后面再次获取群list中同样包含此群

### 如何复现

1.获取所在群list
2.返回所在群群list

### 期望的结果?

应当无已退出的群号

### NapCat 运行日志

```shell
2024-06-22 10:20:27 [INFO] bot | 发送消息 给群聊 群[(964029733)] : 消息
2024-06-22 10:20:32 [ERROR] bot | 发生错误 发送超时 
2024-06-22 10:20:32 [INFO] bot | 发送消息 给群聊 群[1()] : 推送失败,群：964029733，错误信息：<ActionFailed status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 1469}>  (这是错误发给反馈群)
```

### OneBot 客户端运行日志

```shell
这是我自己打印的错误日志，都是不存在的群出现的问题
fail_count:1,msg_count:0,err:<ActionFailed status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 1434}>
fail_count:2,msg_count:0,err:<ActionFailed status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 1437}>
fail_count:3,msg_count:0,err:<ActionFailed status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 1440}>
fail_count:4,msg_count:0,err:<ActionFailed status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 1443}>
fail_count:1,msg_count:0,err:<ActionFailed status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 1446}>
fail_count:2,msg_count:0,err:<ActionFailed status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 1450}>
fail_count:3,msg_count:0,err:<ActionFailed status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 1453}>
fail_count:4,msg_count:0,err:<ActionFailed status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 1456}>
fail_count:5,msg_count:0,err:<ActionFailed status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 1459}>
fail_count:6,msg_count:0,err:<ActionFailed status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 1463}>
fail_count:7,msg_count:0,err:<ActionFailed status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 1466}>
fail_count:8,msg_count:0,err:<ActionFailed status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 1469}>
```

**Comment by MliKiowa** [comment]
怎么退出的 主动还是被踢

**Comment by nanmuye** [comment]
> 怎么退出的 主动还是被踢

这个不太清楚，大多数情况是主动退的，这边的代码是无论发送成功或者失败都会再次主动退群，但是下一次获取list还是有。这里的代码是检查bot授权，获取的群list不在授权中的发送消息后主动退群，但是群号一直在获取的群list中，所以就会一直往反馈群里发报错

**Comment by nanmuye** [comment]
> 怎么退出的 主动还是被踢

上手q看群聊也确实不在群，显示无法在已退出的群聊中发送消息

**Comment by nanmuye** [comment]
> 怎么退出的 主动还是被踢

重新启动napcat后就正常了 不包含已退出的群  应该是主动退出的

**Comment by MliKiowa** [comment]
主动退出的话我记得应该没问题啊 退群5s就刷新了

**Comment by MliKiowa** [comment]
![image](https://github.com/NapNeko/NapCatQQ/assets/61873808/872867bf-3582-4c90-bab3-8efd5e6f420d)

**Comment by nanmuye** [comment]
> 主动退出的话我记得应该没问题啊 退群5s就刷新了

刚刚尝试复现成功
{'group_id': 931871772, 'group_name': '测试', 'member_count': 2, 'max_member_count': 200}]
[2024-06-24 11:28:41,810 nonebot]
2024-06-24 11:28:18 [INFO] bot() | 发送消息 给群聊 群[测试(931871772)] : 本群未授权使用即将退群...
上面是主动退群的日志以及获取到的群idlist中包含群

这是半小时后再次获取群列表
{'group_id': 931871772, 'group_name': '', 'member_count': 0, 'max_member_count': 0}]
fail_count:1,msg_count:1,retry:0,gid:931871772,err:<ActionFailed status='failed', retcode=1200, data=None, message='发送超时', wording='发送超时', echo={'seq': 6941}>,msg:本群未授权
2024-06-24 11:58:19 [INFO] bot() | 发送消息 给群聊 群[(931871772)] : 本群未授权使用,即将退群..
2024-06-24 11:58:24 [ERROR] bot() | 发生错误 发送超时

**Comment by nanmuye** [comment]
能获取到已退出的群 但是总人数返回的是0  应该是有bug吧 还是本身就是这么设计的

**Comment by MliKiowa** [comment]
尝试新版本
