### ISSUE TITLE
[BUG] 获取群成员列表失效

### ISSUE THREAD

**Issue by q8018414** [NapNeko/NapCatQQ#83]
### 系统版本

nas - docker

### QQNT 版本

Linux 3.2.9-24815

### NapCat 版本

1.6.1

### OneBot 客户端

docker

### 发生了什么?

get_group_member_list接口获取不到数据.

### 如何复现

传递
{"group_id": 645862714,"no_cache" :false}

### 期望的结果?

正常返回群成员信息

**Comment by MliKiowa** [comment]
重启试试呢

**Comment by q8018414** [comment]
重启了.还是不行..




『無』
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "NapNeko/NapCatQQ"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月23日(星期天) 晚上9:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [NapNeko/NapCatQQ] [BUG] 获取群成员列表失效 (Issue #83)





 
重启试试呢

**Comment by MliKiowa** [comment]
调用接口提示什么吗

**Comment by q8018414** [comment]
麻了.找到问题了..不知道什么时候.貌似返回的字段里面的code变成了retcode,底层在提交返回的时候.字段丢失.默认置空了...烦..
