### ISSUE TITLE
[BUG] webui的开关控制bug？

### ISSUE THREAD

**Issue by layvsan** [NapNeko/NapCatQQ#85]
### 系统版本

centos 7

### QQNT 版本

3.2.4

### NapCat 版本

1.6.1

### OneBot 客户端

11

### 发生了什么?

1.webui的控制bug
在webui中启用启用ws连接后，再次切换为关闭状态时，webui会提示保存成功，但是实际上napcat并不会断开ws连接，而是会继续保持ws连接，要断开只有改一个错误的ws连接地址
2.其他的几个开关是否可以正常关闭暂时不确定，我这没用上
3.在同一napcat目录下登陆多个账号的时候，会出现多个QQ共用一个webui端口的情况，但是webui并没有给切换账号的选项（这个倒是可以通过复制多份napcat解决）

### 如何复现

1.进入webui
2.在反向ws服务开启的状态下，用webui关闭反向websocket的服务

### 期望的结果?

webui可以正常关闭对应服务

**Comment by MliKiowa** [comment]
这是特性(雾)

**Comment by layvsan** [comment]
> 这是特性(雾)

红豆泥得死卡

**Comment by MliKiowa** [comment]
https://github.com/NapNeko/NapCatQQ/actions/runs/9708040348 尝试最新版 如果还有问题 reopen

**Comment by layvsan** [comment]
> https://github.com/NapNeko/NapCatQQ/actions/runs/9708040348 尝试测试版 如果还有问题 reopen

似乎并没有什么用（悲）
