### ISSUE TITLE
[BUG] 在群成员被踢后get_group_member_list仍保留退群成员的信息

### ISSUE THREAD

**Issue by LiLuo-B** [NapNeko/NapCatQQ#88]
### 系统版本

Ubuntu 22.04.4 LTS

### QQNT 版本

3.2.9-24815

### NapCat 版本

1.4.7

### OneBot 客户端

NoneBot 2.3.0

### 发生了什么?

 调用get_group_member_list后群成员被踢不会更新群成员列表信息，目测半小时之内不会自动更新，需要重启napcat才能刷新

### 如何复现
```
@group_list.handle()
async def _(bot: Bot):
    group_member_list = await bot.call_api(
        api="get_group_member_list", group_id=892823321
    )
    print("群成员信息")
    for group_member in group_member_list:
        print(
            f"成员id:{group_member['user_id']} 头衔:{group_member['title']} 权限:{group_member['role']}"
        )
    await group_list.finish()
```
发送指令后获取的信息正常
![image](https://github.com/NapNeko/NapCatQQ/assets/98267824/f34f6f9f-d148-4227-a626-141873ac3e26)
![image](https://github.com/NapNeko/NapCatQQ/assets/98267824/f4241c28-00ec-4437-b172-38c501646106)
当踢人后仍然是之前的信息
![image](https://github.com/NapNeko/NapCatQQ/assets/98267824/06cfd167-61ce-4adc-9729-284de47e86f6)
![image](https://github.com/NapNeko/NapCatQQ/assets/98267824/41d34297-d4a7-4df0-94fc-c232294ef9be)

### 期望的结果?

应当无退群成员的信息

**Comment by MliKiowa** [comment]
是否为管理员

**Comment by MliKiowa** [comment]
尝试新版本

**Comment by LiLuo-B** [comment]
还是不行，已更新最新版
![image](https://github.com/NapNeko/NapCatQQ/assets/98267824/e562b2a8-67d7-4065-a907-0ef231279ff9)
![image](https://github.com/NapNeko/NapCatQQ/assets/98267824/265aa290-5bc3-4fa0-8680-112650382530)
![image](https://github.com/NapNeko/NapCatQQ/assets/98267824/bb126568-f673-4338-815e-0ed343460f42)
![image](https://github.com/NapNeko/NapCatQQ/assets/98267824/315ba65d-3c1f-4bea-87b8-33dc62658c59)
![image](https://github.com/NapNeko/NapCatQQ/assets/98267824/13138136-813d-4b91-8bff-d5726f05042a)

**Comment by MliKiowa** [comment]
好的 下次再修修试试

**Comment by MliKiowa** [comment]
是其它管理员踢的 还是 bot踢的

**Comment by LiLuo-B** [comment]
bot踢的

**Comment by MliKiowa** [comment]
下个版本一定修

**Comment by MliKiowa** [comment]
v1.7.7已修
