### ISSUE TITLE
qq私聊机器人如果带了group id，机器人会把回复错发到群里。

### ISSUE THREAD

**Issue by 1825679767** [NapNeko/NapCatQQ#91]
之前用的gocqhttp，对接NapCatQQ以后发现了这个问题。希望大佬能修复一下

**Comment by MliKiowa** [comment]
调用的send_group_msg吗

**Comment by MliKiowa** [comment]
尝试测试版本 https://github.com/NapNeko/NapCatQQ/actions/runs/9708012242 如果还有问题请reopen issue
