### ISSUE TITLE
[BUG] 收到有人加群事件里 "user_id":0 值无法获取到加群人的QQ

### ISSUE THREAD

**Issue by airdm** [NapNeko/NapCatQQ#92]
### 系统版本

Windows 10

### QQNT 版本

QQ_9.9.11_240606_x64_01

### NapCat 版本

1.6.2

### OneBot 客户端

没有

### 发生了什么?

"user_id"的值大概率获得的值为0 偶尔可以正常获取到加群人的QQ

### 如何复现

无

### 期望的结果?

能获取到"user_id"的值

**Comment by MliKiowa** [comment]
下个版本修复

**Comment by MliKiowa** [comment]
https://github.com/NapNeko/NapCatQQ/actions/runs/9707774296 尝试

**Comment by MliKiowa** [comment]
如何还有问题 reopen
