### ISSUE TITLE
是否计划实现设置群组专属头衔的API？

### ISSUE THREAD

**Issue by pan90** [NapNeko/NapCatQQ#93]
设置群组专属头衔: set_group_special_title

![image](https://github.com/NapNeko/NapCatQQ/assets/40511978/ea7b3c85-5c9b-4e64-b155-177e3e55079d)

**Comment by Starrain08** [comment]
NTQQ本身不支持该功能，无法实现

> 设置群组专属头衔: set_group_special_title
> 
> ![image](https://private-user-images.githubusercontent.com/40511978/344383336-ea7b3c85-5c9b-4e64-b155-177e3e55079d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODYxMjMsIm5iZiI6MTcxOTg4NTgyMywicGF0aCI6Ii80MDUxMTk3OC8zNDQzODMzMzYtZWE3YjNjODUtNWM5Yi00ZTY0LWIxNTUtMTc3ZTNlNTUwNzlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAyMDM0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ODU2YzIyMWE0MWE2N2JhMDFkOWJhMWYzZDM5YzBlYjg0YzQwYmQyZDVlY2JmMjRhMmRiMjA3NGVmNjE2ZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6oXzeqNU5EMGrehG-k5tfyXSY1WysLpzzYJkgHcarzo)

NTQQ本身不支持该功能，无法实现，这是开发者的原话

**Comment by MliKiowa** [comment]
暂时难以支持
