### ISSUE TITLE
[BUG] /ocr_image 一直无响应 某些情况

### ISSUE THREAD

**Issue by rongrong1000** [NapNeko/NapCatQQ#94]
### 系统版本

win server 2012

### QQNT 版本

QQ_9.9.11_240606_x64_01

### NapCat 版本

v1.6.3

### OneBot 客户端

无

### 发生了什么?

/ocr_image 一直无响应 某些情况

### 如何复现

当 ocr 一些png图是. 只是后缀是png, 其实是gif
还有某些情况也会导致, 但不知道原因是什么

### 期望的结果?

有返回 哪怕是错误码

**Comment by MliKiowa** [comment]
也许只能jpg吧

**Comment by rongrong1000** [comment]
> 也许只能jpg吧

也可以png的, 不过还是希望接口能响应数据, 而不是一直不响应

**Comment by rongrong1000** [comment]
然后部分服务器 ocr 普通图片也接口一直无响应
我再找找原因
