### ISSUE TITLE
[BUG] 更新后,磁盘读取量猛增.

### ISSUE THREAD

**Issue by airdm** [NapNeko/NapCatQQ#96]
### 系统版本

Windows 10

### QQNT 版本

QQ_9.9.11_240606_x64_01

### NapCat 版本

1.6.3

### OneBot 客户端

没有

### 发生了什么?

更新到1.6之后 硬盘读取量变得特别大了,不知道在读取什么.写入量还是正常.

### 如何复现

0

### 期望的结果?

希望可以恢复到以前硬盘读写量,现在因为读取量增大导致硬盘100%就会导致卡顿.

**Comment by airdm** [comment]
经过测试,NC重启后 读取硬盘的占用不高,运行一段时间后,读取量暴增.

**Comment by MliKiowa** [comment]
你的配置看看

**Comment by qiuyuyang910** [comment]
同样问题，我用vscode远程连接linux主机后qq磁盘读取量暴增并持续相当一段时间

**Comment by airdm** [comment]
> 你的配置看看

要什么配置 是nc的配置还是电脑的配置 如果是电脑的话 CPU和内存都相当有富余占用不高 硬盘用的M.2 SSD  NC配置如下
{
  "http": {
    "enable": true,
    "host": "",
    "port": ****,
    "secret": "",
    "enableHeart": false,
    "enablePost": true,
    "postUrls": [
      "http://127.0.0.1:1234/**********"
    ]
  },
  "ws": {
    "enable": false,
    "host": "",
    "port": 3001
  },
  "reverseWs": {
    "enable": false,
    "urls": []
  },
  "debug": false,
  "heartInterval": 30000,
  "messagePostFormat": "string",
  "enableLocalFile2Url": true,
  "musicSignUrl": "http://127.0.0.1:1234/*********",
  "reportSelfMessage": false,
  "token": "",
  "GroupLocalTime": {
    "Record": false,
    "RecordList": []
  }
}

**Comment by airdm** [comment]
我把QQ缓存都清理后(包括NC的v2.db还有temp目录),目前没有那么高的硬盘占用了.

**Comment by MliKiowa** [comment]
好的 如果有问题开新issue
